# Generated by Django 5.2.7 on 2025-11-02 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "registration_enabled",
                    models.BooleanField(
                        default=True, help_text="Whether new user registration is enabled"
                    ),
                ),
                (
                    "login_enabled",
                    models.BooleanField(default=True, help_text="Whether user login is enabled"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp when settings were last updated"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin user who last updated the settings",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="system_settings_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "System Settings",
                "verbose_name_plural": "System Settings",
                "db_table": "system_settings",
            },
        ),
    ]
