# Generated by Django 5.2.7 on 2025-11-03 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_add_system_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="oandaaccount",
            name="jurisdiction",
            field=models.CharField(
                choices=[
                    ("US", "United States"),
                    ("JP", "Japan"),
                    ("EU", "European Union"),
                    ("UK", "United Kingdom"),
                    ("AU", "Australia"),
                    ("OTHER", "Other/International"),
                ],
                default="OTHER",
                help_text="Regulatory jurisdiction for this account",
                max_length=10,
            ),
        ),
    ]
