# Generated by Django 5.2.7 on 2025-11-03 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_oandaaccount_jurisdiction"),
    ]

    operations = [
        migrations.AddField(
            model_name="oandaaccount",
            name="enable_position_differentiation",
            field=models.BooleanField(
                default=False,
                help_text="Enable automatic position differentiation for FIFO flexibility",
            ),
        ),
        migrations.AddField(
            model_name="oandaaccount",
            name="position_diff_increment",
            field=models.IntegerField(
                default=1, help_text="Increment amount for position differentiation (1-100 units)"
            ),
        ),
        migrations.AddField(
            model_name="oandaaccount",
            name="position_diff_pattern",
            field=models.CharField(
                choices=[
                    ("increment", "Increment"),
                    ("decrement", "Decrement"),
                    ("alternating", "Alternating"),
                ],
                default="increment",
                help_text="Pattern for position differentiation",
                max_length=20,
            ),
        ),
    ]
