# Generated by Django 5.2.7 on 2025-11-03 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_add_position_differentiation_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verification_sent_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when verification email was last sent", null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="email_verification_token",
            field=models.CharField(
                blank=True, help_text="Token for email verification", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(
                default=False, help_text="Whether the user's email address has been verified"
            ),
        ),
    ]
