# Generated by Django 5.2.7 on 2025-11-03 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_add_email_verification"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="email_whitelist_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Whether email whitelist is enforced for registration and login",
            ),
        ),
        migrations.CreateModel(
            name="WhitelistedEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "email_pattern",
                    models.CharField(
                        db_index=True,
                        help_text=(
                            "Email address or domain pattern "
                            "(e.g., user@example.com or *@example.com)"
                        ),
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Optional description for this whitelist entry",
                        max_length=255,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this whitelist entry is active"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when the entry was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp when the entry was last updated"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin user who created this entry",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="whitelisted_emails_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Whitelisted Email",
                "verbose_name_plural": "Whitelisted Emails",
                "db_table": "whitelisted_emails",
                "ordering": ["email_pattern"],
                "indexes": [
                    models.Index(fields=["email_pattern"], name="whitelisted_email_p_8645e2_idx"),
                    models.Index(fields=["is_active"], name="whitelisted_is_acti_501643_idx"),
                ],
            },
        ),
    ]
