# Generated by Django 5.2.7 on 2025-11-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_add_email_whitelist"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="aws_access_key_id",
            field=models.CharField(
                blank=True, default="", help_text="AWS access key ID for S3 and SES", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="aws_region",
            field=models.CharField(
                default="us-east-1", help_text="Default AWS region", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="aws_s3_bucket",
            field=models.CharField(
                blank=True, default="", help_text="S3 bucket name for file storage", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="aws_secret_access_key",
            field=models.CharField(
                blank=True, default="", help_text="AWS secret access key", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="aws_ses_region",
            field=models.CharField(
                default="us-east-1",
                help_text="AWS SES region (if using SES for email)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="debug_mode",
            field=models.BooleanField(
                default=False, help_text="Enable debug mode (should be False in production)"
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="default_from_email",
            field=models.EmailField(
                default="noreply@example.com",
                help_text="Default sender email address",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="django_log_level",
            field=models.CharField(
                choices=[
                    ("DEBUG", "Debug"),
                    ("INFO", "Info"),
                    ("WARNING", "Warning"),
                    ("ERROR", "Error"),
                    ("CRITICAL", "Critical"),
                ],
                default="INFO",
                help_text="Logging level for Django",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="email_backend_type",
            field=models.CharField(
                choices=[("smtp", "SMTP"), ("ses", "AWS SES")],
                default="smtp",
                help_text="Type of email backend to use",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="email_host",
            field=models.CharField(
                default="smtp.gmail.com", help_text="SMTP server hostname", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="email_host_password",
            field=models.CharField(
                blank=True, default="", help_text="SMTP authentication password", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="email_host_user",
            field=models.CharField(
                blank=True, default="", help_text="SMTP authentication username", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="email_port",
            field=models.IntegerField(default=587, help_text="SMTP server port"),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="email_use_ssl",
            field=models.BooleanField(default=False, help_text="Enable SSL for email connection"),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="email_use_tls",
            field=models.BooleanField(default=True, help_text="Enable TLS for email connection"),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="tick_data_retention_days",
            field=models.IntegerField(
                default=90, help_text="Number of days to retain tick data before cleanup"
            ),
        ),
    ]
