# Generated by Django 5.2.7 on 2025-11-08 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_add_system_settings_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="aws_credential_method",
            field=models.CharField(
                choices=[
                    ("profile", "AWS Profile"),
                    ("profile_role", "AWS Profile + Assume Role"),
                    ("credentials_file", "Credentials File"),
                    ("access_keys", "Access Key ID + Secret"),
                ],
                default="profile",
                help_text="Method for AWS authentication",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="aws_credentials_file_path",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Path to AWS credentials file (for credentials_file method)",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="aws_profile_name",
            field=models.CharField(
                blank=True,
                default="default",
                help_text="AWS profile name (for profile and profile_role methods)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="aws_role_arn",
            field=models.CharField(
                blank=True,
                default="",
                help_text="AWS role ARN to assume (for profile_role method)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="aws_access_key_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="AWS access key ID (for access_keys method)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="aws_secret_access_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="AWS secret access key (for access_keys method)",
                max_length=255,
            ),
        ),
    ]
