# Generated by Django 5.2.7 on 2025-11-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_add_aws_credential_methods"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="oanda_sync_interval_seconds",
            field=models.IntegerField(
                default=300,
                help_text=(
                    "Interval in seconds for OANDA account synchronization "
                    "(default: 300 = 5 minutes)"
                ),
            ),
        ),
    ]
