# Generated by Django 5.2.7 on 2025-11-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_add_oanda_sync_interval"),
    ]

    operations = [
        migrations.AddField(
            model_name="oandaaccount",
            name="is_default",
            field=models.BooleanField(
                default=False,
                help_text="Whether this is the default account for market data collection",
            ),
        ),
        migrations.AddIndex(
            model_name="oandaaccount",
            index=models.Index(
                fields=["user", "is_default"], name="oanda_accou_user_id_3f5a4a_idx"
            ),
        ),
    ]
