# Generated by Django 5.2.7 on 2025-11-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_add_is_default_to_oanda_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="oanda_fetch_duration_days",
            field=models.IntegerField(
                default=365,
                help_text="Number of days to fetch orders and positions (default: 365 days)",
            ),
        ),
    ]
