# Generated by Django 5.2.7 on 2025-11-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_add_oanda_fetch_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemsettings",
            name="oanda_fetch_duration_days",
            field=models.IntegerField(
                default=365,
                help_text=(
                    "Number of days to fetch orders and positions from OANDA "
                    "(default: 365 = 1 year)"
                ),
            ),
        ),
    ]
