# Generated by Django 5.2.7 on 2025-11-12 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_alter_systemsettings_oanda_fetch_duration_days"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="systemsettings",
            name="aws_s3_bucket",
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="athena_database_name",
            field=models.CharField(
                blank=True,
                default="forex_hist_data_db",
                help_text="Athena database name for historical forex data",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="athena_output_bucket",
            field=models.CharField(
                blank=True,
                default="",
                help_text="S3 bucket for Athena query results (e.g., my-athena-results)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="athena_table_name",
            field=models.CharField(
                blank=True,
                default="quotes",
                help_text="Athena table name for historical forex quotes",
                max_length=255,
            ),
        ),
    ]
