# Generated by Django 5.2.7 on 2025-11-12 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_replace_s3_bucket_with_athena_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="athena_instruments",
            field=models.TextField(
                blank=True,
                default="EUR_USD,GBP_USD,USD_JPY,USD_CHF,AUD_USD,USD_CAD,NZD_USD",
                help_text=(
                    "Comma-separated list of instruments to import from "
                    "Athena (e.g., EUR_USD,GBP_USD)"
                ),
            ),
        ),
    ]
