# Generated by Django 5.2.7 on 2025-11-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_add_athena_instruments"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="tick_data_instruments",
            field=models.TextField(
                blank=True,
                default="EUR_USD,GBP_USD,USD_JPY,USD_CHF,AUD_USD,USD_CAD,NZD_USD",
                help_text=(
                    "Comma-separated list of instruments for live tick data collection "
                    "(e.g., EUR_USD,GBP_USD)"
                ),
            ),
        ),
    ]
