# Generated by Django 5.2.7 on 2025-11-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_add_tick_data_instruments"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="system_health_update_interval",
            field=models.IntegerField(
                default=5,
                help_text=(
                    "Interval in seconds for system health updates in admin dashboard "
                    "(default: 5)"
                ),
            ),
        ),
    ]
