# Generated by Django 5.2.7 on 2025-11-13 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_add_system_health_update_interval"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="athena_query_timeout",
            field=models.IntegerField(
                default=600,
                help_text="Maximum time to wait for Athena query completion (in seconds)",
            ),
        ),
    ]
