# Generated by Django 5.2.7 on 2025-11-14 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_add_athena_query_timeout"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="backtest_cpu_limit",
            field=models.IntegerField(
                default=1, help_text="CPU core limit per backtest task (default: 1)"
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="backtest_memory_limit",
            field=models.BigIntegerField(
                default=2147483648,
                help_text="Memory limit per backtest task in bytes (default: 2147483648 = 2GB)",
            ),
        ),
    ]
