# Generated by Django 5.2.8 on 2025-11-15 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_add_backtest_resource_limits"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="external_api_check_interval",
            field=models.IntegerField(
                default=60,
                help_text=(
                    "Interval in seconds for external API health checks "
                    "(e.g., OANDA API) (default: 60)"
                ),
            ),
        ),
    ]
