# Generated by Django 5.2.7 on 2025-11-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_add_external_api_check_interval"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="backtest_day_batch_size",
            field=models.IntegerField(
                default=1,
                help_text=(
                    "Number of days to fetch and process before sending "
                    "progress update (default: 1 = real-time updates per day)"
                ),
            ),
        ),
    ]
