# Generated by Django 5.2.7 on 2025-11-30 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_add_backtest_day_batch_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="celery_task_hard_time_limit",
            field=models.IntegerField(
                default=259200,
                help_text=(
                    "Hard time limit for Celery tasks in seconds. "
                    "Tasks will be terminated (SIGKILL) when this limit is reached "
                    "(default: 259200 = 72 hours)"
                ),
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="celery_task_soft_time_limit",
            field=models.IntegerField(
                default=259200,
                help_text=(
                    "Soft time limit for Celery tasks in seconds. "
                    "Tasks will receive a SoftTimeLimitExceeded exception when this limit "
                    "is reached (default: 259200 = 72 hours)"
                ),
            ),
        ),
    ]
