# Generated by Django 5.2.7 on 2025-11-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0021_add_celery_task_time_limits"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="s3_data_bucket",
            field=models.CharField(
                blank=True,
                default="forex-hist-data-789121567207-us-west-2",
                help_text="S3 bucket name for historical forex data files",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="s3_data_prefix",
            field=models.CharField(
                blank=True,
                default="global_forex/quotes",
                help_text="S3 key prefix for tick data files (e.g., global_forex/quotes)",
                max_length=255,
            ),
        ),
    ]
