# Generated by Django 5.2.7 on 2025-12-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_add_s3_data_source_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="trading_metrics_interval_seconds",
            field=models.IntegerField(
                default=30,
                help_text=(
                    "Interval in seconds for submitting trading task performance metrics "
                    "(default: 30 seconds)"
                ),
            ),
        ),
    ]
