# Generated by Django 5.2.7 on 2025-12-02 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0023_add_trading_metrics_interval"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="systemsettings",
            name="celery_task_hard_time_limit",
        ),
        migrations.RemoveField(
            model_name="systemsettings",
            name="celery_task_soft_time_limit",
        ),
    ]
