# Generated by Django 5.2.7 on 2026-01-25 18:32

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryTaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(db_index=True, max_length=200)),
                ('instance_key', models.CharField(blank=True, db_index=True, default='default', max_length=200)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('worker', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('stop_requested', 'Stop Requested'), ('stopped', 'Stopped'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='running', max_length=32)),
                ('status_message', models.TextField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trading Celery Task Status',
                'verbose_name_plural': 'Trading Celery Task Statuses',
                'db_table': 'trading_celery_tasks',
                'indexes': [models.Index(fields=['task_name', 'status'], name='tcs_tn_st_idx'), models.Index(fields=['celery_task_id'], name='tcs_celery_id_idx'), models.Index(fields=['last_heartbeat_at'], name='tcs_hb_idx')],
                'constraints': [models.UniqueConstraint(fields=('task_name', 'instance_key'), name='uniq_trading_task_name_instance_key')],
            },
        ),
        migrations.CreateModel(
            name='StrategyConfigurations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when this record was last updated')),
                ('name', models.CharField(help_text='Human-readable name for this configuration', max_length=255)),
                ('strategy_type', models.CharField(help_text="Type of strategy (e.g., 'floor', 'ma_crossover', 'rsi')", max_length=50)),
                ('parameters', models.JSONField(default=dict, help_text='Strategy-specific configuration parameters')),
                ('description', models.TextField(blank=True, default='', help_text='Optional description of this configuration')),
                ('user', models.ForeignKey(help_text='User who created this configuration', on_delete=django.db.models.deletion.CASCADE, related_name='strategy_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Strategy Configuration',
                'verbose_name_plural': 'Strategy Configurations',
                'db_table': 'strategy_configurations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BacktestTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable name for this backtest task', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description of this backtest task')),
                ('data_source', models.CharField(choices=[('postgresql', 'PostgreSQL'), ('athena', 'AWS Athena'), ('s3', 'AWS S3')], default='postgresql', help_text='Data source for historical tick data', max_length=20)),
                ('start_time', models.DateTimeField(help_text='Start time for backtest period')),
                ('end_time', models.DateTimeField(help_text='End time for backtest period')),
                ('initial_balance', models.DecimalField(decimal_places=2, default=Decimal('10000'), help_text='Initial account balance for backtest', max_digits=15)),
                ('commission_per_trade', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Commission to apply per trade', max_digits=10)),
                ('instrument', models.CharField(default='USD_JPY', help_text='Trading instrument (e.g., EUR_USD, USD_JPY)', max_length=20)),
                ('_pip_size', models.DecimalField(blank=True, db_column='pip_size', decimal_places=5, default=Decimal('0.01'), help_text='Pip size for the instrument (e.g., 0.0001 for EUR_USD, 0.01 for USD_JPY). If not provided, will be fetched from OANDA account.', max_digits=10, null=True)),
                ('trading_mode', models.CharField(choices=[('netting', 'Netting Mode'), ('hedging', 'Hedging Mode')], default='netting', help_text='Trading mode: netting (aggregated positions) or hedging (independent trades)', max_length=20)),
                ('status', models.CharField(choices=[('created', 'Created'), ('running', 'Running'), ('paused', 'Paused'), ('stopped', 'Stopped'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='created', help_text='Current task status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the task was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the task was last updated')),
                ('celery_task_id', models.CharField(blank=True, db_index=True, help_text='Celery task ID for tracking execution', max_length=255, null=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='Timestamp when the task execution started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when the task execution completed', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if task failed', null=True)),
                ('error_traceback', models.TextField(blank=True, help_text='Full error traceback if task failed', null=True)),
                ('retry_count', models.IntegerField(default=0, help_text='Number of times this task has been retried')),
                ('max_retries', models.IntegerField(default=3, help_text='Maximum number of retries allowed')),
                ('result_data', models.JSONField(blank=True, help_text='Execution results data', null=True)),
                ('result_data_external_ref', models.CharField(blank=True, help_text='Reference to externally stored result data (e.g., fs://path or s3://bucket/key)', max_length=500, null=True)),
                ('user', models.ForeignKey(help_text='User who created this backtest task', on_delete=django.db.models.deletion.CASCADE, related_name='backtest_tasks', to=settings.AUTH_USER_MODEL)),
                ('config', models.ForeignKey(help_text='Strategy configuration used by this task', on_delete=django.db.models.deletion.PROTECT, related_name='backtest_tasks', to='trading.strategyconfigurations')),
            ],
            options={
                'verbose_name': 'Backtest Task',
                'verbose_name_plural': 'Backtest Tasks',
                'db_table': 'backtest_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this log entry', primary_key=True, serialize=False)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, help_text='Celery task ID for this execution', max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When this log entry was created')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', help_text='Log severity level', max_length=20)),
                ('message', models.TextField(help_text='Log message content')),
                ('task', models.ForeignKey(help_text='Task this log entry belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='trading.backtesttasks')),
            ],
            options={
                'verbose_name': 'Task Log',
                'verbose_name_plural': 'Task Logs',
                'db_table': 'task_logs',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TaskMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this metric entry', primary_key=True, serialize=False)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, help_text='Celery task ID for this execution', max_length=255, null=True)),
                ('metric_name', models.CharField(help_text="Name of the metric (e.g., 'equity', 'drawdown', 'trades_count')", max_length=255)),
                ('metric_value', models.FloatField(help_text='Numeric value of the metric')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When this metric was recorded')),
                ('metadata', models.JSONField(blank=True, help_text='Optional additional metadata for this metric', null=True)),
                ('task', models.ForeignKey(help_text='Task this metric belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='trading.backtesttasks')),
            ],
            options={
                'verbose_name': 'Task Metric',
                'verbose_name_plural': 'Task Metrics',
                'db_table': 'task_metrics',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TradingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('severity', models.CharField(db_index=True, default='info', max_length=16)),
                ('description', models.TextField()),
                ('instrument', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('task_type', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('task_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trading_events', to='market.oandaaccounts')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trading_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trading Event',
                'verbose_name_plural': 'Trading Events',
                'db_table': 'trading_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TradingTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable name for this trading task', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description of this trading task')),
                ('status', models.CharField(choices=[('created', 'Created'), ('running', 'Running'), ('paused', 'Paused'), ('stopped', 'Stopped'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='created', help_text='Current task status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the task was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the task was last updated')),
                ('celery_task_id', models.CharField(blank=True, db_index=True, help_text='Celery task ID for tracking execution', max_length=255, null=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='Timestamp when the task execution started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when the task execution completed', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if task failed', null=True)),
                ('error_traceback', models.TextField(blank=True, help_text='Full error traceback if task failed', null=True)),
                ('retry_count', models.IntegerField(default=0, help_text='Number of times this task has been retried')),
                ('max_retries', models.IntegerField(default=3, help_text='Maximum number of retries allowed')),
                ('result_data', models.JSONField(blank=True, help_text='Execution results data', null=True)),
                ('result_data_external_ref', models.CharField(blank=True, help_text='Reference to externally stored result data (e.g., fs://path or s3://bucket/key)', max_length=500, null=True)),
                ('sell_on_stop', models.BooleanField(default=False, help_text='Close all positions when task is stopped')),
                ('instrument', models.CharField(default='USD_JPY', help_text='Trading instrument (e.g., EUR_USD, USD_JPY)', max_length=20)),
                ('_pip_size', models.DecimalField(blank=True, db_column='pip_size', decimal_places=5, default=Decimal('0.01'), help_text='Pip size for the instrument (e.g., 0.0001 for EUR_USD, 0.01 for USD_JPY). If not provided, will be fetched from OANDA account.', max_digits=10, null=True)),
                ('trading_mode', models.CharField(choices=[('netting', 'Netting Mode'), ('hedging', 'Hedging Mode')], default='netting', help_text='Trading mode: netting (aggregated positions) or hedging (independent trades)', max_length=20)),
                ('strategy_state', models.JSONField(blank=True, default=dict, help_text='Strategy-specific state for persistence across restarts')),
                ('config', models.ForeignKey(help_text='Strategy configuration used by this task', on_delete=django.db.models.deletion.PROTECT, related_name='trading_tasks', to='trading.strategyconfigurations')),
                ('oanda_account', models.ForeignKey(help_text='OANDA account used for trading', on_delete=django.db.models.deletion.PROTECT, related_name='trading_tasks', to='market.oandaaccounts')),
                ('user', models.ForeignKey(help_text='User who created this trading task', on_delete=django.db.models.deletion.CASCADE, related_name='trading_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trading Task',
                'verbose_name_plural': 'Trading Tasks',
                'db_table': 'trading_tasks',
                'ordering': ['-created_at'],
            },
        ),

        migrations.CreateModel(
            name='ExecutionEquity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this equity point', primary_key=True, serialize=False)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, help_text='Celery task ID for this execution', max_length=255, null=True)),
                ('timestamp', models.DateTimeField(help_text='Timestamp of this equity snapshot')),
                ('balance', models.DecimalField(decimal_places=2, help_text='Account balance at this timestamp', max_digits=20)),
                ('ticks_processed', models.IntegerField(default=0, help_text='Number of ticks processed at this point')),
                ('task', models.ForeignKey(help_text='Task this equity point belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='equity_points', to='trading.backtesttasks')),
            ],
            options={
                'verbose_name': 'Execution Equity',
                'verbose_name_plural': 'Execution Equity',
                'db_table': 'execution_equity_points',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['task', 'timestamp'], name='execution_e_task_id_d4f41c_idx'), models.Index(fields=['task', 'celery_task_id'], name='execution_e_task_id_5aa924_idx')],
                'constraints': [models.UniqueConstraint(fields=('task', 'celery_task_id', 'timestamp'), name='unique_task_execution_equity_timestamp')],
            },
        ),
        migrations.CreateModel(
            name='ExecutionTrade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this trade', primary_key=True, serialize=False)),
                ('direction', models.CharField(help_text='Trade direction (long/short)', max_length=10)),
                ('units', models.IntegerField(help_text='Number of units traded')),
                ('entry_price', models.DecimalField(decimal_places=5, help_text='Entry price', max_digits=20)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=5, help_text='Exit price', max_digits=20, null=True)),
                ('pnl', models.DecimalField(blank=True, decimal_places=5, help_text='Profit/loss in account currency', max_digits=20, null=True)),
                ('pips', models.DecimalField(blank=True, decimal_places=5, help_text='Profit/loss in pips', max_digits=20, null=True)),
                ('entry_timestamp', models.DateTimeField(help_text='When the position was opened')),
                ('exit_timestamp', models.DateTimeField(blank=True, help_text='When the position was closed', null=True)),
                ('exit_reason', models.CharField(blank=True, help_text='Reason for exit (take_profit, stop_loss, etc.)', max_length=50, null=True)),
                ('layer_number', models.IntegerField(default=0, help_text='Layer number for multi-layer strategies')),
                ('task', models.ForeignKey(help_text='Task this trade belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='trading.backtesttasks')),
            ],
            options={
                'verbose_name': 'Execution Trade',
                'verbose_name_plural': 'Execution Trades',
                'db_table': 'execution_trades',
                'ordering': ['entry_timestamp'],
                'indexes': [models.Index(fields=['task', 'entry_timestamp'], name='execution_t_task_id_29d63d_idx'), models.Index(fields=['task', 'exit_timestamp'], name='execution_t_task_id_5d1ae0_idx'), models.Index(fields=['task', 'direction'], name='execution_t_task_id_134860_idx')],
            },
        ),

        migrations.AddIndex(
            model_name='strategyconfigurations',
            index=models.Index(fields=['user', 'strategy_type'], name='strategy_co_user_id_6ca4ea_idx'),
        ),
        migrations.AddIndex(
            model_name='strategyconfigurations',
            index=models.Index(fields=['created_at'], name='strategy_co_created_f5a377_idx'),
        ),
        migrations.AddConstraint(
            model_name='strategyconfigurations',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_user_config_name'),
        ),
        migrations.AddIndex(
            model_name='backtesttasks',
            index=models.Index(fields=['user', 'status'], name='backtest_ta_user_id_a299d0_idx'),
        ),
        migrations.AddIndex(
            model_name='backtesttasks',
            index=models.Index(fields=['user', 'config'], name='backtest_ta_user_id_e6137e_idx'),
        ),
        migrations.AddIndex(
            model_name='backtesttasks',
            index=models.Index(fields=['created_at'], name='backtest_ta_created_81ebbe_idx'),
        ),
        migrations.AddIndex(
            model_name='backtesttasks',
            index=models.Index(fields=['celery_task_id'], name='backtest_ta_celery__9504ee_idx'),
        ),
        migrations.AddIndex(
            model_name='backtesttasks',
            index=models.Index(fields=['status', 'created_at'], name='backtest_ta_status_dde84b_idx'),
        ),
        migrations.AddConstraint(
            model_name='backtesttasks',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_user_backtest_task_name'),
        ),
        migrations.AddIndex(
            model_name='tasklog',
            index=models.Index(fields=['task', 'timestamp'], name='task_logs_task_id_0d6ce6_idx'),
        ),
        migrations.AddIndex(
            model_name='tasklog',
            index=models.Index(fields=['task', 'level'], name='task_logs_task_id_8914fc_idx'),
        ),
        migrations.AddIndex(
            model_name='tasklog',
            index=models.Index(fields=['task', 'celery_task_id'], name='task_logs_task_id_153ad2_idx'),
        ),
        migrations.AddIndex(
            model_name='taskmetric',
            index=models.Index(fields=['task', 'metric_name', 'timestamp'], name='task_metric_task_id_e392a9_idx'),
        ),
        migrations.AddIndex(
            model_name='taskmetric',
            index=models.Index(fields=['task', 'celery_task_id'], name='task_metric_task_id_4760f3_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingtasks',
            index=models.Index(fields=['user', 'status'], name='trading_tas_user_id_83de91_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingtasks',
            index=models.Index(fields=['user', 'config'], name='trading_tas_user_id_3c6fc1_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingtasks',
            index=models.Index(fields=['oanda_account', 'status'], name='trading_tas_oanda_a_4cf7d8_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingtasks',
            index=models.Index(fields=['created_at'], name='trading_tas_created_e23628_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingtasks',
            index=models.Index(fields=['celery_task_id'], name='trading_tas_celery__9cfcfe_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingtasks',
            index=models.Index(fields=['status', 'created_at'], name='trading_tas_status_4811fe_idx'),
        ),
        migrations.AddConstraint(
            model_name='tradingtasks',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_user_trading_task_name'),
        ),
        migrations.AddConstraint(
            model_name='tradingtasks',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['created', 'created', 'running', 'stopped', 'completed', 'failed', 'stopped'])), name='valid_trading_task_status'),
        ),

    ]
