# Generated by Django 5.2.11 on 2026-02-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricsnapshot',
            name='metrics',
            field=models.JSONField(blank=True, default=dict, help_text='Strategy-specific metrics as JSON (e.g., RSI, MACD, custom indicators)'),
        ),
    ]
