# Generated by Django 5.2.7 on 2026-01-25 23:07

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
        ('trading', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equities',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this equity point', primary_key=True, serialize=False)),
                ('task_type', models.CharField(db_index=True, help_text='Type of task (backtest or trading)', max_length=32)),
                ('task_id', models.UUIDField(db_index=True, help_text='UUID of the task this equity point belongs to')),
                ('celery_task_id', models.CharField(blank=True, db_index=True, help_text='Celery task ID for this execution', max_length=255, null=True)),
                ('timestamp', models.DateTimeField(help_text='Timestamp of this equity snapshot')),
                ('balance', models.DecimalField(decimal_places=2, help_text='Account balance at this timestamp', max_digits=20)),
                ('ticks_processed', models.IntegerField(default=0, help_text='Number of ticks processed at this point')),
            ],
            options={
                'verbose_name': 'Equity',
                'verbose_name_plural': 'Equities',
                'db_table': 'equities',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ExecutionState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when this record was last updated')),
                ('task_type', models.CharField(db_index=True, help_text="Type of task: 'backtest' or 'trading'", max_length=32)),
                ('task_id', models.UUIDField(db_index=True, help_text='UUID of the associated task')),
                ('celery_task_id', models.CharField(db_index=True, help_text='Celery task ID for tracking execution', max_length=255)),
                ('strategy_state', models.JSONField(blank=True, default=dict, help_text='Strategy-specific state as JSON')),
                ('current_balance', models.DecimalField(decimal_places=10, help_text='Current account balance', max_digits=20)),
                ('ticks_processed', models.IntegerField(default=0, help_text='Number of ticks processed so far')),
                ('last_tick_timestamp', models.DateTimeField(blank=True, help_text='Timestamp of the last processed tick', null=True)),
            ],
            options={
                'verbose_name': 'Execution State',
                'verbose_name_plural': 'Execution States',
                'db_table': 'execution_state',
            },
        ),
        migrations.CreateModel(
            name='Trades',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this trade', primary_key=True, serialize=False)),
                ('task_type', models.CharField(db_index=True, help_text='Type of task (backtest or trading)', max_length=32)),
                ('task_id', models.UUIDField(db_index=True, help_text='UUID of the task this trade belongs to')),
                ('timestamp', models.DateTimeField(db_index=True, help_text='When the trade was executed')),
                ('direction', models.CharField(help_text='Trade direction (LONG/SHORT)', max_length=10)),
                ('units', models.IntegerField(help_text='Number of units traded')),
                ('instrument', models.CharField(help_text='Trading instrument (e.g., EUR_USD)', max_length=32)),
                ('price', models.DecimalField(decimal_places=10, help_text='Execution price', max_digits=20)),
                ('execution_method', models.CharField(help_text='Event type that triggered trade (e.g., INITIAL_ENTRY, RETRACEMENT)', max_length=64)),
                ('pnl', models.DecimalField(blank=True, decimal_places=10, help_text='Profit/loss for this trade (for closes)', max_digits=20, null=True)),
            ],
            options={
                'verbose_name': 'Trade',
                'verbose_name_plural': 'Trades',
                'db_table': 'trades',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TradingEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('severity', models.CharField(db_index=True, default='info', max_length=16)),
                ('description', models.TextField()),
                ('instrument', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('task_type', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('task_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, help_text='Celery task ID for tracking specific execution', max_length=255, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Trading Events',
                'verbose_name_plural': 'Trading Events',
                'db_table': 'trading_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='executionequity',
            name='task',
        ),
        migrations.RemoveField(
            model_name='executiontrade',
            name='task',
        ),
        migrations.RemoveField(
            model_name='tradingevent',
            name='account',
        ),
        migrations.RemoveField(
            model_name='tradingevent',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='backtesttasks',
            options={'verbose_name': 'Backtest Task', 'verbose_name_plural': 'Backtest Tasks'},
        ),
        migrations.RemoveIndex(
            model_name='backtesttasks',
            name='backtest_ta_created_81ebbe_idx',
        ),
        migrations.RemoveIndex(
            model_name='tasklog',
            name='task_logs_task_id_0d6ce6_idx',
        ),
        migrations.RemoveIndex(
            model_name='tasklog',
            name='task_logs_task_id_8914fc_idx',
        ),
        migrations.RemoveIndex(
            model_name='tasklog',
            name='task_logs_task_id_153ad2_idx',
        ),
        migrations.RemoveIndex(
            model_name='taskmetric',
            name='task_metric_task_id_e392a9_idx',
        ),
        migrations.RemoveIndex(
            model_name='taskmetric',
            name='task_metric_task_id_4760f3_idx',
        ),
        migrations.RemoveField(
            model_name='backtesttasks',
            name='_pip_size',
        ),
        migrations.RemoveField(
            model_name='backtesttasks',
            name='result_data',
        ),
        migrations.RemoveField(
            model_name='backtesttasks',
            name='result_data_external_ref',
        ),
        migrations.RemoveField(
            model_name='tasklog',
            name='task',
        ),
        migrations.RemoveField(
            model_name='taskmetric',
            name='task',
        ),
        migrations.RemoveField(
            model_name='tradingtasks',
            name='_pip_size',
        ),
        migrations.RemoveField(
            model_name='tradingtasks',
            name='result_data',
        ),
        migrations.RemoveField(
            model_name='tradingtasks',
            name='result_data_external_ref',
        ),
        migrations.AddField(
            model_name='backtesttasks',
            name='pip_size',
            field=models.DecimalField(blank=True, decimal_places=5, default=Decimal('0.01'), help_text='Pip size for the instrument (e.g., 0.0001 for EUR_USD, 0.01 for USD_JPY). If not provided, will be fetched from OANDA account.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='details',
            field=models.JSONField(blank=True, default=dict, help_text='Additional structured log details'),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='task_id',
            field=models.UUIDField(db_index=True, default='00000000-0000-0000-0000-000000000000', help_text='UUID of the task this log entry belongs to'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasklog',
            name='task_type',
            field=models.CharField(choices=[('backtest', 'Backtest'), ('trading', 'Trading')], db_index=True, default='backtest', help_text='Type of task (backtest or trading)', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskmetric',
            name='task_id',
            field=models.UUIDField(db_index=True, default='00000000-0000-0000-0000-000000000000', help_text='UUID of the task this metric belongs to'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskmetric',
            name='task_type',
            field=models.CharField(choices=[('backtest', 'Backtest'), ('trading', 'Trading')], db_index=True, default='backtest', help_text='Type of task (backtest or trading)', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradingtasks',
            name='pip_size',
            field=models.DecimalField(blank=True, decimal_places=5, default=Decimal('0.01'), help_text='Pip size for the instrument (e.g., 0.0001 for EUR_USD, 0.01 for USD_JPY). If not provided, will be fetched from OANDA account.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='backtesttasks',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created'),
        ),
        migrations.AlterField(
            model_name='backtesttasks',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='backtesttasks',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when this record was last updated'),
        ),
        migrations.AlterField(
            model_name='tradingtasks',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created'),
        ),
        migrations.AlterField(
            model_name='tradingtasks',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tradingtasks',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when this record was last updated'),
        ),
        migrations.AddIndex(
            model_name='tasklog',
            index=models.Index(fields=['task_type', 'task_id', 'timestamp'], name='task_logs_task_ty_22eb43_idx'),
        ),
        migrations.AddIndex(
            model_name='tasklog',
            index=models.Index(fields=['task_type', 'task_id', 'level'], name='task_logs_task_ty_9c7a1d_idx'),
        ),
        migrations.AddIndex(
            model_name='tasklog',
            index=models.Index(fields=['celery_task_id'], name='task_logs_celery__7cc863_idx'),
        ),
        migrations.AddIndex(
            model_name='taskmetric',
            index=models.Index(fields=['task_type', 'task_id', 'metric_name', 'timestamp'], name='task_metric_task_ty_b4ea55_idx'),
        ),
        migrations.AddIndex(
            model_name='taskmetric',
            index=models.Index(fields=['celery_task_id'], name='task_metric_celery__2273a3_idx'),
        ),
        migrations.AddIndex(
            model_name='equities',
            index=models.Index(fields=['task_type', 'task_id', 'timestamp'], name='equities_task_ty_4915f3_idx'),
        ),
        migrations.AddIndex(
            model_name='equities',
            index=models.Index(fields=['task_type', 'task_id', 'celery_task_id'], name='equities_task_ty_acb8b3_idx'),
        ),
        migrations.AddConstraint(
            model_name='equities',
            constraint=models.UniqueConstraint(fields=('task_type', 'task_id', 'celery_task_id', 'timestamp'), name='unique_task_execution_equity_timestamp'),
        ),
        migrations.AddIndex(
            model_name='executionstate',
            index=models.Index(fields=['task_type', 'task_id', 'celery_task_id'], name='execution_s_task_ty_5f4789_idx'),
        ),
        migrations.AddIndex(
            model_name='executionstate',
            index=models.Index(fields=['task_type', 'task_id'], name='execution_s_task_ty_532801_idx'),
        ),
        migrations.AddIndex(
            model_name='executionstate',
            index=models.Index(fields=['celery_task_id'], name='execution_s_celery__7fb117_idx'),
        ),
        migrations.AddConstraint(
            model_name='executionstate',
            constraint=models.UniqueConstraint(fields=('task_type', 'task_id', 'celery_task_id'), name='unique_task_celery_execution_state'),
        ),
        migrations.AddIndex(
            model_name='trades',
            index=models.Index(fields=['task_type', 'task_id', '-timestamp'], name='trades_task_ty_2bf74d_idx'),
        ),
        migrations.AddIndex(
            model_name='trades',
            index=models.Index(fields=['task_type', 'task_id', 'instrument'], name='trades_task_ty_d5b9df_idx'),
        ),
        migrations.AddIndex(
            model_name='trades',
            index=models.Index(fields=['execution_method'], name='trades_executi_04f520_idx'),
        ),
        migrations.AddField(
            model_name='tradingevents',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trading_events', to='market.oandaaccounts'),
        ),
        migrations.AddField(
            model_name='tradingevents',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trading_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ExecutionEquity',
        ),
        migrations.DeleteModel(
            name='ExecutionTrade',
        ),
        migrations.DeleteModel(
            name='TradingEvent',
        ),
        migrations.AddIndex(
            model_name='tradingevents',
            index=models.Index(fields=['task_type', 'task_id', '-created_at'], name='trading_eve_task_ty_4446c7_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingevents',
            index=models.Index(fields=['task_type', 'task_id', 'celery_task_id', '-created_at'], name='trading_eve_task_ty_08d514_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingevents',
            index=models.Index(fields=['event_type', '-created_at'], name='trading_eve_event_t_cf3485_idx'),
        ),
    ]
