# Generated by Django 5.2.7 on 2026-01-25 18:49

import uuid
from django.db import migrations, models


def generate_uuids(apps, schema_editor):
    """Generate UUIDs for existing BacktestTasks records."""
    BacktestTasks = apps.get_model('trading', 'BacktestTasks')
    for task in BacktestTasks.objects.all():
        task.uuid_id = uuid.uuid4()
        task.save(update_fields=['uuid_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        # Step 1: Add temporary UUID field
        migrations.AddField(
            model_name='backtesttasks',
            name='uuid_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),

        # Step 2: Populate UUIDs for existing records
        migrations.RunPython(generate_uuids, reverse_code=migrations.RunPython.noop),

        # Step 3: Make UUID field non-nullable
        migrations.AlterField(
            model_name='backtesttasks',
            name='uuid_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),

        # Step 4: Remove old id field and rename uuid_id to id
        migrations.RemoveField(
            model_name='backtesttasks',
            name='id',
        ),
        migrations.RenameField(
            model_name='backtesttasks',
            old_name='uuid_id',
            new_name='id',
        ),

        # Step 5: Make id the primary key
        migrations.AlterField(
            model_name='backtesttasks',
            name='id',
            field=models.UUIDField(
                primary_key=True,
                default=uuid.uuid4,
                editable=False,
                help_text='Unique identifier for this record',
            ),
        ),

        # Step 6: Update created_at and updated_at to match UUIDModel
        migrations.AlterField(
            model_name='backtesttasks',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text='Timestamp when this record was created',
            ),
        ),
        migrations.AlterField(
            model_name='backtesttasks',
            name='updated_at',
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text='Timestamp when this record was last updated',
            ),
        ),

        # Step 7: Update model options and remove standalone created_at index
        migrations.AlterModelOptions(
            name='backtesttasks',
            options={
                'verbose_name': 'Backtest Task',
                'verbose_name_plural': 'Backtest Tasks',
            },
        ),
        migrations.RemoveIndex(
            model_name='backtesttasks',
            name='backtest_ta_created_81ebbe_idx',
        ),
    ]
