# Generated by Django 5.2.11 on 2026-02-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionstate',
            name='last_tick_ask',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='Ask price of the last processed tick', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='executionstate',
            name='last_tick_bid',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='Bid price of the last processed tick', max_digits=20, null=True),
        ),
    ]
