# Generated by Django 5.2.7 on 2025-11-02 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0001_initial"),
        ("trading", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the event occurred",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("trading", "Trading"),
                            ("system", "System"),
                            ("security", "Security"),
                            ("admin", "Admin"),
                        ],
                        db_index=True,
                        help_text="Event category (trading, system, security, admin)",
                        max_length=50,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        db_index=True,
                        help_text="Specific event type (e.g., 'order_submitted', 'login_failed')",
                        max_length=100,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("debug", "Debug"),
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        help_text="Event severity level",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Human-readable description of the event"),
                ),
                (
                    "details",
                    models.JSONField(
                        default=dict, help_text="Additional event details in JSON format"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address associated with the event", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, help_text="User agent string (for HTTP requests)", null=True
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        help_text="OANDA account associated with this event",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="market.oandaaccount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User associated with this event",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "db_table": "events",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the notification was created",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        help_text=(
                            "Type of notification " "(e.g., 'margin_warning', 'connection_failure')"
                        ),
                        max_length=50,
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Notification title", max_length=200),
                ),
                ("message", models.TextField(help_text="Notification message")),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        help_text="Notification severity level",
                        max_length=20,
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether the notification has been read",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when the notification was created"
                    ),
                ),
                (
                    "related_event",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related event that triggered this notification",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="trading.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notifications",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["timestamp", "category"], name="events_timesta_1ed05e_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["timestamp", "severity"], name="events_timesta_c37c15_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["user", "timestamp"], name="events_user_id_f7b1ba_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["category", "event_type"], name="events_categor_953432_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["severity", "timestamp"], name="events_severit_0918a0_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["timestamp", "is_read"], name="notificatio_timesta_65366c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["severity", "is_read"], name="notificatio_severit_3c0cd2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["notification_type"], name="notificatio_notific_19df93_idx"),
        ),
    ]
