# Generated by Django 5.2.11 on 2026-02-24 05:14

from django.db import migrations, models


def _table_exists(schema_editor, table_name: str) -> bool:
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        table_names = connection.introspection.table_names(cursor)
    return table_name in table_names


def _column_exists(schema_editor, table_name: str, column_name: str) -> bool:
    connection = schema_editor.connection
    if not _table_exists(schema_editor, table_name):
        return False
    with connection.cursor() as cursor:
        description = connection.introspection.get_table_description(cursor, table_name)
    return any(getattr(column, "name", column[0]) == column_name for column in description)


def _add_metrics_column(apps, schema_editor):
    _ = apps
    table_name = None
    if _table_exists(schema_editor, "metric_snapshots"):
        table_name = "metric_snapshots"
    elif _table_exists(schema_editor, "metrics"):
        table_name = "metrics"
    if not table_name or _column_exists(schema_editor, table_name, "metrics"):
        return
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(
            f"ALTER TABLE {table_name} ADD COLUMN metrics jsonb NOT NULL DEFAULT '{{}}'::jsonb"
        )
    else:
        schema_editor.execute(f"ALTER TABLE {table_name} ADD COLUMN metrics text")


def _remove_metrics_column(apps, schema_editor):
    _ = apps
    for table_name in ("metrics", "metric_snapshots"):
        if _table_exists(schema_editor, table_name) and _column_exists(
            schema_editor, table_name, "metrics"
        ):
            schema_editor.execute(f"ALTER TABLE {table_name} DROP COLUMN metrics")
            return


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(_add_metrics_column, _remove_metrics_column),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="metricsnapshot",
                    name="metrics",
                    field=models.JSONField(
                        blank=True,
                        default=dict,
                        help_text=(
                            "Strategy-specific metrics as JSON "
                            "(e.g., RSI, MACD, custom indicators)"
                        ),
                    ),
                ),
            ],
        ),
    ]
