# Generated by Django 5.2.11 on 2026-02-24 06:43

from django.db import migrations, models


def _column_exists(schema_editor, table_name: str, column_name: str) -> bool:
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        table_names = connection.introspection.table_names(cursor)
        if table_name not in table_names:
            return False
        description = connection.introspection.get_table_description(cursor, table_name)
    return any(getattr(column, "name", column[0]) == column_name for column in description)


def _add_tick_bid_ask_columns(apps, schema_editor):
    _ = apps
    if not _column_exists(schema_editor, "execution_state", "last_tick_bid"):
        schema_editor.execute(
            "ALTER TABLE execution_state ADD COLUMN last_tick_bid numeric(20,10) NULL"
        )
    if not _column_exists(schema_editor, "execution_state", "last_tick_ask"):
        schema_editor.execute(
            "ALTER TABLE execution_state ADD COLUMN last_tick_ask numeric(20,10) NULL"
        )


def _drop_tick_bid_ask_columns(apps, schema_editor):
    _ = apps
    if _column_exists(schema_editor, "execution_state", "last_tick_ask"):
        schema_editor.execute("ALTER TABLE execution_state DROP COLUMN last_tick_ask")
    if _column_exists(schema_editor, "execution_state", "last_tick_bid"):
        schema_editor.execute("ALTER TABLE execution_state DROP COLUMN last_tick_bid")


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(_add_tick_bid_ask_columns, _drop_tick_bid_ask_columns),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="executionstate",
                    name="last_tick_ask",
                    field=models.DecimalField(
                        blank=True,
                        decimal_places=10,
                        help_text="Ask price of the last processed tick",
                        max_digits=20,
                        null=True,
                    ),
                ),
                migrations.AddField(
                    model_name="executionstate",
                    name="last_tick_bid",
                    field=models.DecimalField(
                        blank=True,
                        decimal_places=10,
                        help_text="Bid price of the last processed tick",
                        max_digits=20,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
