# Generated by Django 5.2.7 on 2026-02-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasklog",
            name="component",
            field=models.CharField(
                db_index=True,
                default="unknown",
                help_text="Component/logger name that emitted this log",
                max_length=255,
            ),
        ),
        migrations.AddIndex(
            model_name="tasklog",
            index=models.Index(
                fields=["task_type", "task_id", "component"],
                name="task_logs_task_ty_c42984_idx",
            ),
        ),
    ]
