# Generated by Django 5.2.7 on 2026-01-25 19:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_migrate_backtest_tasks_to_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backtesttasks',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False),
        ),
    ]
