# Generated by Django 5.2.7 on 2026-02-16 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_tasklog_component'),
        ('trading', '0002_trade_layer_index'),
    ]

    operations = [
    ]
