# Generated by Django 5.2.7 on 2026-01-26 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_equities_executionstate_trades_tradingevents_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskMetric',
        ),
    ]
