# Generated by Django 5.2.7 on 2026-01-25 04:51

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
        ('trading', '0003_add_external_storage_reference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tradingtasks',
            name='valid_trading_task_status',
        ),
        migrations.RenameIndex(
            model_name='backtesttasks',
            new_name='backtest_ta_celery__9504ee_idx',
            old_name='backtest_ta_celery__idx',
        ),
        migrations.RenameIndex(
            model_name='backtesttasks',
            new_name='backtest_ta_status_dde84b_idx',
            old_name='backtest_ta_status__idx',
        ),
        migrations.RenameIndex(
            model_name='tasklog',
            new_name='task_logs_task_id_0d6ce6_idx',
            old_name='task_logs_task_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='tasklog',
            new_name='task_logs_task_id_8914fc_idx',
            old_name='task_logs_task_level_idx',
        ),
        migrations.RenameIndex(
            model_name='taskmetric',
            new_name='task_metric_task_id_e392a9_idx',
            old_name='task_metrics_task_name_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='tradingtasks',
            new_name='trading_tas_celery__9cfcfe_idx',
            old_name='trading_tas_celery__idx',
        ),
        migrations.RenameIndex(
            model_name='tradingtasks',
            new_name='trading_tas_status_4811fe_idx',
            old_name='trading_tas_status__idx',
        ),
        migrations.AlterField(
            model_name='backtesttasks',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('running', 'Running'), ('paused', 'Paused'), ('stopped', 'Stopped'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='created', help_text='Current task status', max_length=20),
        ),
        migrations.AlterField(
            model_name='floorstrategytaskstate',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('running', 'Running'), ('paused', 'Paused'), ('stopped', 'Stopped'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='created', help_text='Persisted strategy lifecycle status', max_length=20),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this log entry', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='level',
            field=models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', help_text='Log severity level', max_length=20),
        ),
        migrations.AlterField(
            model_name='taskmetric',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this metric entry', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='taskmetric',
            name='metric_name',
            field=models.CharField(help_text="Name of the metric (e.g., 'equity', 'drawdown', 'trades_count')", max_length=255),
        ),
        migrations.AlterField(
            model_name='tradingtasks',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('running', 'Running'), ('paused', 'Paused'), ('stopped', 'Stopped'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='created', help_text='Current task status', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='tradingtasks',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['created', 'created', 'running', 'stopped', 'completed', 'failed', 'stopped'])), name='valid_trading_task_status'),
        ),
    ]
