# Generated by Django 5.2.7 on 2026-02-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_merge_0002_tasklog_component_0002_trade_layer_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='celery_task_id',
            field=models.CharField(blank=True, db_index=True, help_text='Celery task ID for tracking execution run', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['task_type', 'task_id', 'celery_task_id', '-timestamp'], name='trades_task_ty_765da6_idx'),
        ),
    ]
