# Generated by Django 5.2.7 on 2026-01-25 19:10

import uuid
from django.db import migrations, models


def generate_uuids_for_trading_tasks(apps, schema_editor):
    """Generate UUIDs for existing TradingTasks records."""
    TradingTasks = apps.get_model('trading', 'TradingTasks')
    db_alias = schema_editor.connection.alias

    # Add a temporary UUID column
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            'ALTER TABLE trading_tasks ADD COLUMN new_id UUID DEFAULT uuid_generate_v4()'
        )

    # Update all existing records with UUIDs
    for task in TradingTasks.objects.using(db_alias).all():
        task.save()


def drop_old_id_and_rename(apps, schema_editor):
    """Drop old id column and rename new_id to id."""
    with schema_editor.connection.cursor() as cursor:
        # Drop the old id column
        cursor.execute('ALTER TABLE trading_tasks DROP COLUMN id CASCADE')

        # Rename new_id to id
        cursor.execute('ALTER TABLE trading_tasks RENAME COLUMN new_id TO id')

        # Add primary key constraint
        cursor.execute('ALTER TABLE trading_tasks ADD PRIMARY KEY (id)')


def reverse_migration(apps, schema_editor):
    """Reverse the migration by converting back to integer IDs."""
    with schema_editor.connection.cursor() as cursor:
        # Add temporary integer id column
        cursor.execute(
            'ALTER TABLE trading_tasks ADD COLUMN new_id SERIAL'
        )

        # Drop UUID id column
        cursor.execute('ALTER TABLE trading_tasks DROP COLUMN id CASCADE')

        # Rename new_id to id
        cursor.execute('ALTER TABLE trading_tasks RENAME COLUMN new_id TO id')

        # Add primary key constraint
        cursor.execute('ALTER TABLE trading_tasks ADD PRIMARY KEY (id)')


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_alter_backtesttasks_id'),
    ]

    operations = [
        # Ensure uuid-ossp extension is enabled
        migrations.RunSQL(
            'CREATE EXTENSION IF NOT EXISTS "uuid-ossp"',
            reverse_sql='DROP EXTENSION IF EXISTS "uuid-ossp"',
        ),

        # Generate UUIDs for existing records
        migrations.RunPython(
            generate_uuids_for_trading_tasks,
            reverse_code=migrations.RunPython.noop,
        ),

        # Drop old id and rename new_id to id
        migrations.RunPython(
            drop_old_id_and_rename,
            reverse_code=reverse_migration,
        ),

        # Update the model field definitions
        migrations.AlterField(
            model_name='tradingtasks',
            name='id',
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text='Unique identifier for this record',
                primary_key=True,
                serialize=False
            ),
        ),
        migrations.AlterField(
            model_name='tradingtasks',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text='Timestamp when this record was created'
            ),
        ),
        migrations.AlterField(
            model_name='tradingtasks',
            name='updated_at',
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text='Timestamp when this record was last updated'
            ),
        ),
    ]
