# Generated by Django 5.2.7 on 2025-11-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0004_add_tick_data_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="backtest",
            name="cpu_limit_cores",
            field=models.IntegerField(
                blank=True, help_text="CPU cores limit configured for backtest", null=True
            ),
        ),
        migrations.AddField(
            model_name="backtest",
            name="equity_curve",
            field=models.JSONField(default=list, help_text="Equity curve data"),
        ),
        migrations.AddField(
            model_name="backtest",
            name="final_balance",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Final balance after backtest",
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="backtest",
            name="losing_trades",
            field=models.IntegerField(default=0, help_text="Number of losing trades in backtest"),
        ),
        migrations.AddField(
            model_name="backtest",
            name="memory_limit_mb",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Memory limit in MB configured for backtest",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="backtest",
            name="peak_memory_mb",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Peak memory usage in MB during backtest execution",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="backtest",
            name="total_return",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="Total return from backtest", max_digits=15
            ),
        ),
        migrations.AddField(
            model_name="backtest",
            name="total_trades",
            field=models.IntegerField(
                default=0, help_text="Total number of trades executed in backtest"
            ),
        ),
        migrations.AddField(
            model_name="backtest",
            name="trade_log",
            field=models.JSONField(default=list, help_text="Trade log data"),
        ),
        migrations.AddField(
            model_name="backtest",
            name="win_rate",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="Win rate as a percentage", max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="backtest",
            name="winning_trades",
            field=models.IntegerField(default=0, help_text="Number of winning trades in backtest"),
        ),
        migrations.AlterField(
            model_name="backtest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                    ("terminated", "Terminated"),
                ],
                db_index=True,
                default="pending",
                help_text="Current backtest execution status",
                max_length=20,
            ),
        ),
    ]
