# Generated by Django 5.2.7 on 2026-02-17 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_trade_celery_task_id_trade_trades_task_ty_765da6_idx'),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                'ALTER TABLE backtest_tasks '
                'DROP COLUMN IF EXISTS retry_count, '
                'DROP COLUMN IF EXISTS max_retries, '
                'DROP COLUMN IF EXISTS result_data, '
                'DROP COLUMN IF EXISTS result_data_external_ref;'
            ),
            reverse_sql=(
                'ALTER TABLE backtest_tasks '
                'ADD COLUMN IF NOT EXISTS retry_count integer NOT NULL DEFAULT 0, '
                'ADD COLUMN IF NOT EXISTS max_retries integer NOT NULL DEFAULT 3, '
                'ADD COLUMN IF NOT EXISTS result_data jsonb, '
                'ADD COLUMN IF NOT EXISTS result_data_external_ref varchar(500);'
            ),
        ),
    ]
