# Generated by Django 5.2.11 on 2026-02-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_rename_table_metric_snapshots_to_metrics'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='metrics',
            name='unique_metric_snapshot_timestamp',
        ),
        migrations.RenameIndex(
            model_name='metrics',
            new_name='metrics_task_ty_62aaf4_idx',
            old_name='metric_snap_task_ty_3909a0_idx',
        ),
        migrations.RenameIndex(
            model_name='metrics',
            new_name='metrics_task_ty_309c89_idx',
            old_name='metric_snap_task_ty_cc1ce9_idx',
        ),
        migrations.AddConstraint(
            model_name='metrics',
            constraint=models.UniqueConstraint(fields=('task_type', 'task_id', 'celery_task_id', 'timestamp'), name='unique_metric_timestamp'),
        ),
    ]
