# Generated by Django 5.2.11 on 2026-02-25 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_add_tick_bid_ask_to_execution_state'),
        ('trading', '0004_rename_table_metric_snapshots_to_metrics'),
    ]

    operations = [
    ]
