# Generated by Django 5.2.7 on 2026-01-27 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_rename_models_to_singular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backtesttask',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('starting', 'Starting'), ('running', 'Running'), ('paused', 'Paused'), ('stopping', 'Stopping'), ('stopped', 'Stopped'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='created', help_text='Current task status', max_length=20),
        ),
        migrations.AlterField(
            model_name='celerytaskstatus',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='running', max_length=32),
        ),
        migrations.AlterField(
            model_name='tradingtask',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('starting', 'Starting'), ('running', 'Running'), ('paused', 'Paused'), ('stopping', 'Stopping'), ('stopped', 'Stopped'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='created', help_text='Current task status', max_length=20),
        ),
    ]
