# Generated by Django 5.2.7 on 2026-01-25 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
        ('trading', '0004_migrate_trading_tasks_to_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backtesttasks',
            name='result_data',
        ),
        migrations.RemoveField(
            model_name='backtesttasks',
            name='result_data_external_ref',
        ),
        migrations.RemoveField(
            model_name='tradingtasks',
            name='result_data',
        ),
        migrations.RemoveField(
            model_name='tradingtasks',
            name='result_data_external_ref',
        ),
        migrations.CreateModel(
            name='TradingEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('severity', models.CharField(db_index=True, default='info', max_length=16)),
                ('description', models.TextField()),
                ('instrument', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('task_type', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('task_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, help_text='Celery task ID for tracking specific execution', max_length=255, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trading_events', to='market.oandaaccounts')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trading_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trading Events',
                'verbose_name_plural': 'Trading Events',
                'db_table': 'trading_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='TradingEvent',
        ),
        migrations.AddIndex(
            model_name='tradingevents',
            index=models.Index(fields=['task_type', 'task_id', '-created_at'], name='trading_eve_task_ty_4446c7_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingevents',
            index=models.Index(fields=['task_type', 'task_id', 'celery_task_id', '-created_at'], name='trading_eve_task_ty_08d514_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingevents',
            index=models.Index(fields=['event_type', '-created_at'], name='trading_eve_event_t_cf3485_idx'),
        ),
    ]
