# Generated by Django 5.2.7 on 2026-01-25 05:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_add_execution_trades_and_equity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionEquity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this equity point', primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(help_text='Timestamp of this equity snapshot')),
                ('balance', models.DecimalField(decimal_places=2, help_text='Account balance at this timestamp', max_digits=20)),
                ('ticks_processed', models.IntegerField(default=0, help_text='Number of ticks processed at this point')),
                ('task', models.ForeignKey(help_text='Task this equity point belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='equity_points', to='trading.backtesttasks')),
            ],
            options={
                'verbose_name': 'Execution Equity',
                'verbose_name_plural': 'Execution Equity',
                'db_table': 'execution_equity_points',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['task', 'timestamp'], name='execution_e_task_id_d4f41c_idx')],
                'constraints': [models.UniqueConstraint(fields=('task', 'timestamp'), name='unique_task_equity_timestamp')],
            },
        ),
        migrations.CreateModel(
            name='ExecutionTrade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this trade', primary_key=True, serialize=False)),
                ('direction', models.CharField(help_text='Trade direction (long/short)', max_length=10)),
                ('units', models.IntegerField(help_text='Number of units traded')),
                ('entry_price', models.DecimalField(decimal_places=5, help_text='Entry price', max_digits=20)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=5, help_text='Exit price', max_digits=20, null=True)),
                ('pnl', models.DecimalField(blank=True, decimal_places=5, help_text='Profit/loss in account currency', max_digits=20, null=True)),
                ('pips', models.DecimalField(blank=True, decimal_places=5, help_text='Profit/loss in pips', max_digits=20, null=True)),
                ('entry_timestamp', models.DateTimeField(help_text='When the position was opened')),
                ('exit_timestamp', models.DateTimeField(blank=True, help_text='When the position was closed', null=True)),
                ('exit_reason', models.CharField(blank=True, help_text='Reason for exit (take_profit, stop_loss, etc.)', max_length=50, null=True)),
                ('layer_number', models.IntegerField(default=0, help_text='Layer number for multi-layer strategies')),
                ('task', models.ForeignKey(help_text='Task this trade belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='trading.backtesttasks')),
            ],
            options={
                'verbose_name': 'Execution Trade',
                'verbose_name_plural': 'Execution Trades',
                'db_table': 'execution_trades',
                'ordering': ['entry_timestamp'],
                'indexes': [models.Index(fields=['task', 'entry_timestamp'], name='execution_t_task_id_29d63d_idx'), models.Index(fields=['task', 'exit_timestamp'], name='execution_t_task_id_5d1ae0_idx'), models.Index(fields=['task', 'direction'], name='execution_t_task_id_134860_idx')],
            },
        ),
    ]
