# Generated by Django 5.2.7 on 2026-01-25 20:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_rename_tradingevent_to_tradingevents_add_celery_task_id'),
    ]

    operations = [
        # Create new Trades model
        migrations.CreateModel(
            name='Trades',
            fields=[
                ('id', models.UUIDField(
                    default=uuid.uuid4,
                    editable=False,
                    help_text='Unique identifier for this trade',
                    primary_key=True,
                    serialize=False,
                )),
                ('task_type', models.CharField(
                    db_index=True,
                    help_text='Type of task (backtest or trading)',
                    max_length=32,
                )),
                ('task_id', models.UUIDField(
                    db_index=True,
                    help_text='UUID of the task this trade belongs to',
                )),
                ('timestamp', models.DateTimeField(
                    db_index=True,
                    help_text='When the trade was executed',
                )),
                ('direction', models.CharField(
                    help_text='Trade direction (LONG/SHORT)',
                    max_length=10,
                )),
                ('units', models.IntegerField(
                    help_text='Number of units traded',
                )),
                ('instrument', models.CharField(
                    help_text='Trading instrument (e.g., EUR_USD)',
                    max_length=32,
                )),
                ('price', models.DecimalField(
                    decimal_places=10,
                    help_text='Execution price',
                    max_digits=20,
                )),
                ('execution_method', models.CharField(
                    help_text='Event type that triggered trade (e.g., INITIAL_ENTRY, RETRACEMENT)',
                    max_length=64,
                )),
                ('pnl', models.DecimalField(
                    blank=True,
                    decimal_places=10,
                    help_text='Profit/loss for this trade (for closes)',
                    max_digits=20,
                    null=True,
                )),
            ],
            options={
                'verbose_name': 'Trade',
                'verbose_name_plural': 'Trades',
                'db_table': 'trades',
                'ordering': ['timestamp'],
            },
        ),

        # Add indexes
        migrations.AddIndex(
            model_name='trades',
            index=models.Index(
                fields=['task_type', 'task_id', '-timestamp'],
                name='trades_task_ty_2bf74d_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='trades',
            index=models.Index(
                fields=['task_type', 'task_id', 'instrument'],
                name='trades_task_ty_d5b9df_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='trades',
            index=models.Index(
                fields=['execution_method'],
                name='trades_executi_04f520_idx',
            ),
        ),

        # Delete old ExecutionTrade model
        migrations.DeleteModel(
            name='ExecutionTrade',
        ),
    ]
