# Generated by Django 5.2.7 on 2026-01-28 04:39

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_alter_backtesttask_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this order', primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('backtest', 'Backtest'), ('trading', 'Trading')], db_index=True, help_text='Type of task (backtest or trading)', max_length=32)),
                ('task_id', models.UUIDField(db_index=True, help_text='UUID of the task this order belongs to')),
                ('broker_order_id', models.CharField(blank=True, db_index=True, help_text='Order ID from the broker (OANDA)', max_length=255, null=True)),
                ('instrument', models.CharField(db_index=True, help_text='Trading instrument (e.g., EUR_USD)', max_length=32)),
                ('order_type', models.CharField(choices=[('market', 'Market Order'), ('limit', 'Limit Order'), ('stop', 'Stop Order'), ('oco', 'OCO Order')], help_text='Type of order (market, limit, stop, oco)', max_length=20)),
                ('direction', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], help_text='Order direction (LONG/SHORT)', max_length=10)),
                ('units', models.IntegerField(help_text='Number of units to trade (positive for long, negative for short)')),
                ('requested_price', models.DecimalField(blank=True, decimal_places=10, help_text='Requested price for limit/stop orders (null for market orders)', max_digits=20, null=True)),
                ('fill_price', models.DecimalField(blank=True, decimal_places=10, help_text='Actual fill price (null if not filled)', max_digits=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('filled', 'Filled'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('triggered', 'Triggered')], db_index=True, default='pending', help_text='Current order status', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the order was submitted')),
                ('filled_at', models.DateTimeField(blank=True, help_text='When the order was filled (null if not filled)', null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='When the order was cancelled (null if not cancelled)', null=True)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=10, help_text='Take profit price (optional)', max_digits=20, null=True)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=10, help_text='Stop loss price (optional)', max_digits=20, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if order was rejected', null=True)),
                ('is_dry_run', models.BooleanField(db_index=True, default=False, help_text='Whether this was a dry-run order (backtest/simulation)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['task_type', 'task_id', '-submitted_at'], name='orders_task_ty_c6be5d_idx'), models.Index(fields=['task_type', 'task_id', 'instrument', 'status'], name='orders_task_ty_cd6ff6_idx'), models.Index(fields=['status', '-submitted_at'], name='orders_status_cdd6b8_idx'), models.Index(fields=['broker_order_id'], name='orders_broker__a04e54_idx'), models.Index(fields=['is_dry_run', 'status'], name='orders_is_dry__4944d3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this position', primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('backtest', 'Backtest'), ('trading', 'Trading')], db_index=True, help_text='Type of task (backtest or trading)', max_length=32)),
                ('task_id', models.UUIDField(db_index=True, help_text='UUID of the task this position belongs to')),
                ('instrument', models.CharField(db_index=True, help_text='Trading instrument (e.g., EUR_USD)', max_length=32)),
                ('direction', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], help_text='Position direction (LONG/SHORT)', max_length=10)),
                ('units', models.IntegerField(help_text='Number of units in position (positive for long, negative for short)')),
                ('entry_price', models.DecimalField(decimal_places=10, help_text='Average entry price', max_digits=20)),
                ('entry_time', models.DateTimeField(db_index=True, help_text='When the position was opened')),
                ('exit_price', models.DecimalField(blank=True, decimal_places=10, help_text='Exit price (null if position is still open)', max_digits=20, null=True)),
                ('exit_time', models.DateTimeField(blank=True, help_text='When the position was closed (null if still open)', null=True)),
                ('realized_pnl', models.DecimalField(blank=True, decimal_places=10, help_text='Realized profit/loss (null if position is still open)', max_digits=20, null=True)),
                ('unrealized_pnl', models.DecimalField(decimal_places=10, default=Decimal('0'), help_text='Current unrealized profit/loss (updated periodically for open positions)', max_digits=20)),
                ('is_open', models.BooleanField(db_index=True, default=True, help_text='Whether the position is currently open')),
                ('layer_index', models.IntegerField(blank=True, help_text='Layer index for Floor strategy (null for other strategies)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
                'db_table': 'positions',
                'ordering': ['-entry_time'],
                'indexes': [models.Index(fields=['task_type', 'task_id', '-entry_time'], name='positions_task_ty_8657bd_idx'), models.Index(fields=['task_type', 'task_id', 'instrument', 'is_open'], name='positions_task_ty_70be65_idx'), models.Index(fields=['is_open', '-entry_time'], name='positions_is_open_dc1d05_idx'), models.Index(fields=['instrument', 'is_open'], name='positions_instrum_c96ed4_idx')],
            },
        ),
    ]
