# Generated by Django 5.2.7 on 2026-01-25 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_rename_execution_equity_point'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='executionequity',
            name='unique_task_equity_timestamp',
        ),
        migrations.AddField(
            model_name='executionequity',
            name='celery_task_id',
            field=models.CharField(blank=True, db_index=True, help_text='Celery task ID for this execution', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='celery_task_id',
            field=models.CharField(blank=True, db_index=True, help_text='Celery task ID for this execution', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='taskmetric',
            name='celery_task_id',
            field=models.CharField(blank=True, db_index=True, help_text='Celery task ID for this execution', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='executionequity',
            index=models.Index(fields=['task', 'celery_task_id'], name='execution_e_task_id_5aa924_idx'),
        ),
        migrations.AddIndex(
            model_name='tasklog',
            index=models.Index(fields=['task', 'celery_task_id'], name='task_logs_task_id_153ad2_idx'),
        ),
        migrations.AddIndex(
            model_name='taskmetric',
            index=models.Index(fields=['task', 'celery_task_id'], name='task_metric_task_id_4760f3_idx'),
        ),
        migrations.AddConstraint(
            model_name='executionequity',
            constraint=models.UniqueConstraint(fields=('task', 'celery_task_id', 'timestamp'), name='unique_task_execution_equity_timestamp'),
        ),
    ]
