# Generated by Django 5.2.7 on 2026-02-09 02:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_order_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this layer', primary_key=True, serialize=False)),
                ('task_id', models.UUIDField(db_index=True, help_text='UUID of the task this layer belongs to')),
                ('index', models.IntegerField(help_text='Layer index (0, 1, 2, ...)')),
                ('direction', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], help_text='Layer direction (LONG/SHORT)', max_length=10)),
                ('retracement_count', models.IntegerField(default=0, help_text='Number of retracements in this layer')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether the layer is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this layer was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this layer was last updated')),
            ],
            options={
                'verbose_name': 'Floor Layer',
                'verbose_name_plural': 'Floor Layers',
                'db_table': 'floor_layers',
                'ordering': ['task_id', 'index'],
                'indexes': [models.Index(fields=['task_id', 'is_active', 'index'], name='floor_layer_task_id_b8e8d2_idx'), models.Index(fields=['task_id', 'index'], name='floor_layer_task_id_c81a43_idx')],
                'constraints': [models.UniqueConstraint(fields=('task_id', 'index'), name='unique_task_layer_index')],
            },
        ),
    ]
