# Generated by Django 5.2.7 on 2025-11-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0006_add_strategy_comparison_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="backtest",
            name="slippage_pips",
        ),
        migrations.RemoveField(
            model_name="strategycomparison",
            name="slippage_pips",
        ),
        migrations.AlterField(
            model_name="backtest",
            name="commission_per_trade",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Commission to apply per trade (bid/ask spread already in tick data)",
                max_digits=10,
            ),
        ),
    ]
