# Generated by Django 5.2.7 on 2026-02-18 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_trade_open_close_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionstate',
            name='last_tick_price',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='Mid price of the last processed tick', max_digits=20, null=True),
        ),
    ]
