# Generated by Django 5.2.11 on 2026-02-25 07:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_celerytaskstatus_status'),
        ('trading', '0006_merge_20260225_1300'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='executionstate',
            name='unique_task_celery_execution_state',
        ),
        migrations.RemoveConstraint(
            model_name='metrics',
            name='unique_metric_timestamp',
        ),
        migrations.RemoveIndex(
            model_name='executionstate',
            name='execution_s_task_ty_532801_idx',
        ),
        migrations.RemoveIndex(
            model_name='metrics',
            name='metrics_task_ty_62aaf4_idx',
        ),
        migrations.AddField(
            model_name='backtesttask',
            name='execution_run_id',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Monotonic execution run identifier incremented on every start/restart/resume'),
        ),
        migrations.AddField(
            model_name='executionstate',
            name='execution_run_id',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Execution run identifier to isolate state per run'),
        ),
        migrations.AddField(
            model_name='metrics',
            name='execution_run_id',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Execution run identifier to isolate metrics per run'),
        ),
        migrations.AddField(
            model_name='order',
            name='execution_run_id',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Execution run identifier for run-scoped order queries'),
        ),
        migrations.AddField(
            model_name='position',
            name='execution_run_id',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Execution run identifier for run-scoped position queries'),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='execution_run_id',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Execution run identifier for run-scoped log queries'),
        ),
        migrations.AddField(
            model_name='trade',
            name='execution_run_id',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Execution run identifier for run-scoped trade queries'),
        ),
        migrations.AddField(
            model_name='tradingevent',
            name='execution_run_id',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Execution run identifier for run-scoped event queries'),
        ),
        migrations.AddField(
            model_name='tradingtask',
            name='execution_run_id',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Monotonic execution run identifier incremented on every start/restart/resume'),
        ),
        migrations.AddIndex(
            model_name='executionstate',
            index=models.Index(fields=['task_type', 'task_id', 'execution_run_id'], name='execution_s_task_ty_2650b5_idx'),
        ),
        migrations.AddIndex(
            model_name='metrics',
            index=models.Index(fields=['task_type', 'task_id', 'execution_run_id', 'timestamp'], name='metrics_task_ty_bd39fc_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['task_type', 'task_id', 'execution_run_id', '-submitted_at'], name='orders_task_ty_71dc0b_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['task_type', 'task_id', 'execution_run_id', '-entry_time'], name='positions_task_ty_c2c96f_idx'),
        ),
        migrations.AddIndex(
            model_name='tasklog',
            index=models.Index(fields=['task_type', 'task_id', 'execution_run_id', 'timestamp'], name='task_logs_task_ty_7067c6_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['task_type', 'task_id', 'execution_run_id', '-timestamp'], name='trades_task_ty_56c536_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingevent',
            index=models.Index(fields=['task_type', 'task_id', 'execution_run_id', '-created_at'], name='trading_eve_task_ty_8f3162_idx'),
        ),
        migrations.AddConstraint(
            model_name='executionstate',
            constraint=models.UniqueConstraint(fields=('task_type', 'task_id', 'execution_run_id'), name='unique_task_run_execution_state'),
        ),
        migrations.AddConstraint(
            model_name='metrics',
            constraint=models.UniqueConstraint(fields=('task_type', 'task_id', 'execution_run_id', 'timestamp'), name='unique_metric_timestamp_per_run'),
        ),
        migrations.AddConstraint(
            model_name='tradingtask',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['starting', 'running', 'stopping'])), fields=('oanda_account',), name='uniq_active_trading_task_per_account'),
        ),
    ]
