# Generated by Django 5.2.7 on 2025-11-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0007_remove_backtest_slippage_pips_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="backtest",
            name="data_source",
            field=models.CharField(
                choices=[("postgresql", "PostgreSQL"), ("s3", "AWS S3 + Athena")],
                default="postgresql",
                help_text="Data source for historical tick data",
                max_length=20,
            ),
        ),
    ]
