# Generated by Django 5.2.7 on 2026-02-19 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_add_last_tick_price_to_execution_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='retracement_count',
            field=models.IntegerField(blank=True, help_text='Number of retracements in the layer at the time of this trade', null=True),
        ),
    ]
