# Generated by Django 5.2.11 on 2026-02-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_remove_executionstate_unique_task_celery_execution_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingevent',
            name='is_processed',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this event has been fully executed by the event handler'),
        ),
        migrations.AddField(
            model_name='tradingevent',
            name='processed_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when event execution was completed', null=True),
        ),
        migrations.AddField(
            model_name='tradingevent',
            name='processing_error',
            field=models.TextField(blank=True, default='', help_text='Last processing error for retry diagnostics'),
        ),
    ]
