# Generated by Django 5.2.7 on 2026-01-25 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0008_update_tasklog_polymorphic_reference'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tasklog',
            new_name='task_logs_task_ty_22eb43_idx',
            old_name='task_logs_task_ty_3c3c3c_idx',
        ),
        migrations.RenameIndex(
            model_name='tasklog',
            new_name='task_logs_task_ty_9c7a1d_idx',
            old_name='task_logs_task_ty_4d4d4d_idx',
        ),
        migrations.RenameIndex(
            model_name='tasklog',
            new_name='task_logs_celery__7cc863_idx',
            old_name='task_logs_celery__5e5e5e_idx',
        ),
        migrations.RenameIndex(
            model_name='taskmetric',
            new_name='task_metric_task_ty_b4ea55_idx',
            old_name='task_metric_task_ty_6f6f6f_idx',
        ),
        migrations.RenameIndex(
            model_name='taskmetric',
            new_name='task_metric_celery__2273a3_idx',
            old_name='task_metric_celery__7a7a7a_idx',
        ),
    ]
