# Generated by Django 5.2.7 on 2026-02-09 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0008_alter_tradingevent_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backtesttask',
            name='max_retries',
        ),
        migrations.RemoveField(
            model_name='backtesttask',
            name='retry_count',
        ),
        migrations.RemoveField(
            model_name='tradingtask',
            name='max_retries',
        ),
        migrations.RemoveField(
            model_name='tradingtask',
            name='retry_count',
        ),
    ]
