# Generated by Django 5.2.11 on 2026-02-26 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0009_strategyeventrecord'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='strategyeventrecord',
            new_name='strategy_ev_task_ty_4e27cc_idx',
            old_name='strategy_ev_task_ty_6200fd_idx',
        ),
        migrations.RenameIndex(
            model_name='strategyeventrecord',
            new_name='strategy_ev_task_ty_fac977_idx',
            old_name='strategy_ev_task_ty_2b7ae0_idx',
        ),
        migrations.RenameIndex(
            model_name='strategyeventrecord',
            new_name='strategy_ev_event_t_341451_idx',
            old_name='strategy_ev_event_t_80f0f9_idx',
        ),
        migrations.AlterField(
            model_name='trade',
            name='direction',
            field=models.CharField(blank=True, help_text='Trade direction (LONG/SHORT). Null for close-only trades.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='execution_method',
            field=models.CharField(help_text='Event type that triggered trade (e.g., OPEN_POSITION, CLOSE_POSITION)', max_length=64),
        ),
    ]
