# Generated by Django 5.2.7 on 2026-02-19 20:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0009_populate_pip_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(db_index=True, max_length=32)),
                ('task_id', models.UUIDField(db_index=True)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField()),
                ('margin_ratio', models.DecimalField(blank=True, decimal_places=6, help_text='Required margin / NAV', max_digits=10, null=True)),
                ('current_atr', models.DecimalField(blank=True, decimal_places=10, help_text='Current ATR in pips', max_digits=20, null=True)),
                ('baseline_atr', models.DecimalField(blank=True, decimal_places=10, help_text='Baseline ATR in pips', max_digits=20, null=True)),
                ('volatility_threshold', models.DecimalField(blank=True, decimal_places=10, help_text='baseline_atr * volatility_lock_multiplier', max_digits=20, null=True)),
            ],
            options={
                'db_table': 'metric_snapshots',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['task_type', 'task_id', 'timestamp'], name='metric_snap_task_ty_3909a0_idx'), models.Index(fields=['task_type', 'task_id', 'celery_task_id'], name='metric_snap_task_ty_cc1ce9_idx')],
                'constraints': [models.UniqueConstraint(fields=('task_type', 'task_id', 'celery_task_id', 'timestamp'), name='unique_metric_snapshot_timestamp')],
            },
        ),
    ]
