# Generated by Django 5.2.7 on 2026-02-20 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0010_add_metric_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklog',
            name='component',
            field=models.CharField(blank=True, db_index=True, default='unknown', help_text='Component/logger name that emitted this log', max_length=255, null=True),
        ),
    ]
