# Generated by Django 5.2.7 on 2025-11-08 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0010_migrate_status_values"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StrategyConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name for this configuration", max_length=255
                    ),
                ),
                (
                    "strategy_type",
                    models.CharField(
                        help_text="Type of strategy (e.g., 'floor', 'ma_crossover', 'rsi')",
                        max_length=50,
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        default=dict, help_text="Strategy-specific configuration parameters"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional description of this configuration",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when the configuration was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp when the configuration was last updated"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who created this configuration",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="strategy_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Strategy Configuration",
                "verbose_name_plural": "Strategy Configurations",
                "db_table": "strategy_configs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "strategy_type"], name="strategy_co_user_id_066081_idx"
                    ),
                    models.Index(fields=["created_at"], name="strategy_co_created_2933f3_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("user", "name"), name="unique_user_config_name")
                ],
            },
        ),
    ]
