# Generated by Django 5.2.7 on 2026-02-20 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0011_allow_null_component_on_task_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='celery_task_id',
            field=models.CharField(blank=True, db_index=True, help_text='Celery task ID for tracking which execution run created this position', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['task_type', 'task_id', 'celery_task_id', '-entry_time'], name='positions_task_ty_07222e_idx'),
        ),
    ]
