# Generated by Django 5.2.11 on 2026-03-05 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0012_relax_trades_direction_nullability'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingtask',
            name='dry_run',
            field=models.BooleanField(default=False, help_text='Simulate order execution without placing real orders on OANDA'),
        ),
    ]
