# Generated by Django 5.2.7 on 2025-11-08 03:36

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0012_add_task_execution_and_metrics"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BacktestTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name for this backtest task", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional description of this backtest task",
                    ),
                ),
                (
                    "data_source",
                    models.CharField(
                        choices=[("postgresql", "PostgreSQL"), ("athena", "AWS Athena")],
                        default="postgresql",
                        help_text="Data source for historical tick data",
                        max_length=20,
                    ),
                ),
                ("start_time", models.DateTimeField(help_text="Start time for backtest period")),
                ("end_time", models.DateTimeField(help_text="End time for backtest period")),
                (
                    "initial_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10000"),
                        help_text="Initial account balance for backtest",
                        max_digits=15,
                    ),
                ),
                (
                    "commission_per_trade",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Commission to apply per trade",
                        max_digits=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("running", "Running"),
                            ("stopped", "Stopped"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="created",
                        help_text="Current task status",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when the task was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp when the task was last updated"
                    ),
                ),
                (
                    "config",
                    models.ForeignKey(
                        help_text="Strategy configuration used by this task",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="backtest_tasks",
                        to="trading.strategyconfig",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who created this backtest task",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backtest_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Backtest Task",
                "verbose_name_plural": "Backtest Tasks",
                "db_table": "backtest_tasks",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "status"], name="backtest_ta_user_id_a299d0_idx"),
                    models.Index(fields=["user", "config"], name="backtest_ta_user_id_e6137e_idx"),
                    models.Index(fields=["created_at"], name="backtest_ta_created_81ebbe_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "name"), name="unique_user_backtest_task_name"
                    )
                ],
            },
        ),
    ]
