# Generated by Django 5.2.11 on 2026-03-08 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0013_add_dry_run_to_trading_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtesttask',
            name='hedging_enabled',
            field=models.BooleanField(default=True, help_text='Allow simultaneous long and short positions (hedging) during backtest.'),
        ),
        migrations.AddField(
            model_name='tradingtask',
            name='hedging_enabled',
            field=models.BooleanField(default=True, help_text='Allow simultaneous long and short positions (hedging). Requires a hedging-enabled OANDA account.'),
        ),
    ]
