# Generated by Django 5.2.11 on 2026-03-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0014_add_hedging_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='layer_index',
            field=models.IntegerField(blank=True, help_text='Layer index (cycle number for Snowball, layer number for Floor)', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='retracement_count',
            field=models.IntegerField(blank=True, help_text='Retracement count (add count for Snowball, retracement count for Floor)', null=True),
        ),
    ]
