# Generated by Django 5.2.7 on 2026-02-21 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0015_remove_trade_pnl'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtesttask',
            name='account_currency',
            field=models.CharField(default='USD', help_text='Account base currency (e.g., USD, JPY)', max_length=3),
        ),
    ]
