# Generated by Django 5.2.7 on 2026-02-21 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0016_add_backtest_account_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='unrealized_pnl',
        ),
    ]
