# Generated by Django 5.2.11 on 2026-03-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0016_add_planned_exit_price_to_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Strategy decision description (e.g., first layer take-profit, add position due to pip gap)'),
        ),
    ]
