# Generated by Django 5.2.11 on 2026-03-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0017_add_description_to_trade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='direction',
            field=models.CharField(blank=True, choices=[('long', 'Long'), ('short', 'Short')], help_text='Order direction (LONG/SHORT). Matches the original position direction for close orders.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='direction',
            field=models.CharField(blank=True, help_text='Trade direction (LONG/SHORT). Matches the original position direction for close trades.', max_length=10, null=True),
        ),
    ]
