# Generated by Django 5.2.8 on 2025-11-15 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0017_add_execution_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskexecution",
            name="logs",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Execution logs as list of {timestamp, level, message} objects",
            ),
        ),
    ]
