# Generated by Django 5.2.7 on 2026-02-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0019_add_trade_timestamps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backtesttask',
            name='trading_mode',
            field=models.CharField(choices=[('netting', 'Netting Mode'), ('hedging', 'Hedging Mode')], default='hedging', help_text='Trading mode: netting (aggregated positions) or hedging (independent trades)', max_length=20),
        ),
        migrations.AlterField(
            model_name='tradingtask',
            name='trading_mode',
            field=models.CharField(choices=[('netting', 'Netting Mode'), ('hedging', 'Hedging Mode')], default='hedging', help_text='Trading mode: netting (aggregated positions) or hedging (independent trades)', max_length=20),
        ),
    ]
