# Generated by Django 5.2.7 on 2025-11-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0020_add_strategy_events_to_execution_metrics"),
    ]

    operations = [
        migrations.AddField(
            model_name="backtest",
            name="sell_at_completion",
            field=models.BooleanField(
                default=False, help_text="Close all positions at backtest completion"
            ),
        ),
    ]
