# Generated by Django 5.2.7 on 2025-11-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0021_add_sell_at_completion_to_backtest"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradingtask",
            name="sell_on_stop",
            field=models.BooleanField(
                default=False, help_text="Close all positions when task is stopped"
            ),
        ),
    ]
