# Generated by Django 5.2.11 on 2026-03-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0022_simplify_metrics_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrics',
            name='execution_id',
            field=models.UUIDField(blank=True, help_text='Execution run UUID (shared with Celery task_id)', null=True),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='metrics',
            field=models.JSONField(blank=True, default=dict, help_text='Strategy-specific metrics as JSON'),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='task_id',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='task_type',
            field=models.CharField(max_length=32),
        ),
    ]
