# Generated by Django 5.2.7 on 2025-11-27 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0022_add_sell_on_stop_to_trading_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="executionmetrics",
            name="realized_pnl",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Realized profit/loss from closed positions",
                max_digits=15,
            ),
        ),
        migrations.AddField(
            model_name="executionmetrics",
            name="unrealized_pnl",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Unrealized profit/loss from open positions",
                max_digits=15,
            ),
        ),
    ]
