"""Fix trading_tasks.id column type from bigint to uuid.

The database table was created with a bigint id column, but the model
and initial migration define it as UUIDField. This migration alters
the column in-place using raw SQL.
"""

import uuid

from django.db import migrations


def gen_uuid_for_existing_rows(apps, schema_editor):
    """Generate UUIDs for any existing rows that have bigint IDs."""
    # This is a no-op if the table is empty or already has UUIDs.
    # The ALTER below handles the type conversion; this function exists
    # as a safety net in case there are rows with integer IDs.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0023_add_retracement_count_to_position_and_celery_task_id_to_order"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                # 1. Drop the FK constraint on floor_strategy_task_states that references trading_tasks.id
                "ALTER TABLE floor_strategy_task_states DROP CONSTRAINT IF EXISTS floor_strategy_task__trading_task_id_02de5df0_fk_trading_t;",
                # 2. Convert floor_strategy_task_states.trading_task_id from bigint to uuid
                "ALTER TABLE floor_strategy_task_states ALTER COLUMN trading_task_id TYPE uuid USING gen_random_uuid();",
                # 3. Fix trading_tasks.id: drop identity, drop default, convert type, set new default
                "ALTER TABLE trading_tasks ALTER COLUMN id DROP IDENTITY IF EXISTS;",
                "ALTER TABLE trading_tasks ALTER COLUMN id DROP DEFAULT;",
                "ALTER TABLE trading_tasks ALTER COLUMN id TYPE uuid USING gen_random_uuid();",
                "ALTER TABLE trading_tasks ALTER COLUMN id SET DEFAULT gen_random_uuid();",
                # 4. Re-add the FK constraint
                "ALTER TABLE floor_strategy_task_states ADD CONSTRAINT floor_strategy_task__trading_task_id_02de5df0_fk_trading_t FOREIGN KEY (trading_task_id) REFERENCES trading_tasks(id) DEFERRABLE INITIALLY DEFERRED;",
            ],
            reverse_sql=[
                "ALTER TABLE floor_strategy_task_states DROP CONSTRAINT IF EXISTS floor_strategy_task__trading_task_id_02de5df0_fk_trading_t;",
                "ALTER TABLE floor_strategy_task_states ALTER COLUMN trading_task_id TYPE bigint USING 0;",
                "ALTER TABLE trading_tasks ALTER COLUMN id DROP DEFAULT;",
                "ALTER TABLE trading_tasks ALTER COLUMN id TYPE bigint USING 0;",
                "ALTER TABLE trading_tasks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;",
                "ALTER TABLE floor_strategy_task_states ADD CONSTRAINT floor_strategy_task__trading_task_id_02de5df0_fk_trading_t FOREIGN KEY (trading_task_id) REFERENCES trading_tasks(id) DEFERRABLE INITIALLY DEFERRED;",
            ],
            state_operations=[],
        ),
    ]
