# Generated by Django 5.2.7 on 2025-11-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0023_add_realized_unrealized_pnl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backtest",
            name="data_source",
            field=models.CharField(
                choices=[("postgresql", "PostgreSQL"), ("athena", "AWS Athena"), ("s3", "AWS S3")],
                default="postgresql",
                help_text="Data source for historical tick data",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="backtesttask",
            name="data_source",
            field=models.CharField(
                choices=[("postgresql", "PostgreSQL"), ("athena", "AWS Athena"), ("s3", "AWS S3")],
                default="athena",
                help_text="Data source for historical tick data",
                max_length=20,
            ),
        ),
    ]
