# Generated by Django 5.2.11 on 2026-03-20 01:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_celerytaskstatus_status'),
        ('trading', '0024_restore_trading_mode_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='strategyeventrecord',
            name='actual_exit_price',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='strategyeventrecord',
            name='actual_interval_pips',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='strategyeventrecord',
            name='actual_tp_pips',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='strategyeventrecord',
            name='basket',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='strategyeventrecord',
            name='close_reason',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='strategyeventrecord',
            name='direction',
            field=models.CharField(blank=True, db_index=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='strategyeventrecord',
            name='entry_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='strategyeventrecord',
            name='event_timestamp',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='strategyeventrecord',
            name='expected_exit_price',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='strategyeventrecord',
            name='expected_interval_pips',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='strategyeventrecord',
            name='expected_tp_pips',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='strategyeventrecord',
            name='parent_entry_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='strategyeventrecord',
            name='position_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='strategyeventrecord',
            name='root_entry_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='strategyeventrecord',
            name='step',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strategyeventrecord',
            name='strategy_type',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='strategyeventrecord',
            name='validation_status',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='strategyeventrecord',
            name='validation_tolerance_pips',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='strategyeventrecord',
            name='visual_group_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='tradingevent',
            name='actual_exit_price',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='tradingevent',
            name='actual_interval_pips',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='tradingevent',
            name='actual_tp_pips',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='tradingevent',
            name='basket',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='tradingevent',
            name='close_reason',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='tradingevent',
            name='direction',
            field=models.CharField(blank=True, db_index=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='tradingevent',
            name='entry_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='tradingevent',
            name='event_timestamp',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='tradingevent',
            name='expected_exit_price',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='tradingevent',
            name='expected_interval_pips',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='tradingevent',
            name='expected_tp_pips',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='tradingevent',
            name='parent_entry_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='tradingevent',
            name='position_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='tradingevent',
            name='root_entry_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='tradingevent',
            name='step',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradingevent',
            name='strategy_type',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='tradingevent',
            name='validation_status',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='tradingevent',
            name='validation_tolerance_pips',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='tradingevent',
            name='visual_group_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AddIndex(
            model_name='strategyeventrecord',
            index=models.Index(fields=['task_type', 'task_id', 'execution_id', 'strategy_type', '-event_timestamp'], name='strategy_ev_task_ty_73a367_idx'),
        ),
        migrations.AddIndex(
            model_name='strategyeventrecord',
            index=models.Index(fields=['task_type', 'task_id', 'execution_id', 'visual_group_id', 'event_timestamp'], name='strategy_ev_task_ty_7f143d_idx'),
        ),
        migrations.AddIndex(
            model_name='strategyeventrecord',
            index=models.Index(fields=['task_type', 'task_id', 'execution_id', 'root_entry_id', 'event_timestamp'], name='strategy_ev_task_ty_0e5e3b_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingevent',
            index=models.Index(fields=['task_type', 'task_id', 'execution_id', 'strategy_type', '-event_timestamp'], name='trading_eve_task_ty_ee92e1_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingevent',
            index=models.Index(fields=['task_type', 'task_id', 'execution_id', 'visual_group_id', 'event_timestamp'], name='trading_eve_task_ty_319b62_idx'),
        ),
    ]
