# Generated by Django 5.2.11 on 2026-03-22 02:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0025_strategyeventrecord_actual_exit_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskExecutionSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when this record was last updated')),
                ('task_type', models.CharField(choices=[('backtest', 'Backtest'), ('trading', 'Trading')], db_index=True, help_text='Task type for this execution snapshot', max_length=20)),
                ('task_id', models.UUIDField(db_index=True, help_text='UUID of the parent task')),
                ('execution_id', models.UUIDField(db_index=True, help_text='Execution run UUID')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when the execution finished', null=True)),
                ('summary', models.JSONField(blank=True, default=dict, help_text='Serialized task summary snapshot')),
                ('metrics', models.JSONField(blank=True, default=dict, help_text='Serialized execution metrics snapshot')),
            ],
            options={
                'verbose_name': 'Task Execution Snapshot',
                'verbose_name_plural': 'Task Execution Snapshots',
                'db_table': 'task_execution_snapshots',
                'indexes': [models.Index(fields=['task_type', 'task_id'], name='task_execut_task_ty_eb0731_idx'), models.Index(fields=['task_type', 'task_id', 'execution_id'], name='task_execut_task_ty_fbb065_idx'), models.Index(fields=['completed_at'], name='task_execut_complet_6a53bd_idx')],
                'constraints': [models.UniqueConstraint(fields=('task_type', 'task_id', 'execution_id'), name='uniq_task_execution_snapshot')],
            },
        ),
    ]
