# Generated by Django 5.2 on 2024-12-03

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add strategy_state JSONField to TradingTask for state persistence."""

    dependencies = [
        ("trading", "0025_add_trading_task_to_order_and_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradingtask",
            name="strategy_state",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Strategy-specific state for persistence across restarts",
            ),
        ),
    ]
