# Generated by Django 5.2.11 on 2026-03-23 19:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_celerytaskstatus_status'),
        ('trading', '0026_taskexecutionsnapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='backtesttask',
            index=models.Index(fields=['user', '-created_at'], name='backtest_ta_user_id_b3962f_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingtask',
            index=models.Index(fields=['user', '-created_at'], name='trading_tas_user_id_6a2745_idx'),
        ),
    ]
