# Generated by Django 5.2.7 on 2026-02-21 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0026_drop_orphaned_trading_tasks_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='direction',
            field=models.CharField(blank=True, choices=[('long', 'Long'), ('short', 'Short')], help_text='Order direction (LONG/SHORT). Null for trade-close orders (e.g. take profit).', max_length=10, null=True),
        ),
    ]
