# Generated by Django 5.2.11 on 2026-03-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0027_add_user_created_at_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Strategy reasoning for this trade (e.g. layer 1 take profit, retracement entry)'),
        ),
    ]
