# Generated by Django 5.2.11 on 2026-03-25 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0028_alter_trade_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='cycle_id',
            field=models.UUIDField(blank=True, db_index=True, help_text="Cycle identifier grouping all trades from one Initial Entry through to its close. Equal to the Trade.id of the cycle's first open trade. NULL for strategies that do not use cycles.", null=True),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['task_type', 'task_id', 'cycle_id', 'timestamp'], name='trades_task_ty_1da793_idx'),
        ),
    ]
