# Generated by Django 5.2.7 on 2026-02-22 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0028_remove_trading_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='position',
            field=models.ForeignKey(blank=True, help_text='Position this order belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='trading.position'),
        ),
        migrations.AddField(
            model_name='trade',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Order that resulted in this trade', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='trading.order'),
        ),
        migrations.AddField(
            model_name='trade',
            name='position',
            field=models.ForeignKey(blank=True, help_text='Position this trade belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='trading.position'),
        ),
    ]
