# Generated by Django 5.2.7 on 2026-02-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0029_add_position_order_fk_relations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='index',
            field=models.IntegerField(help_text='Layer index (1, 2, 3, ...)'),
        ),
    ]
