# Generated by Django 5.2.11 on 2026-03-26 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0029_add_cycle_id_to_trade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trade',
            options={'ordering': ['timestamp', 'sequence_number'], 'verbose_name': 'Trade', 'verbose_name_plural': 'Trades'},
        ),
        migrations.AddField(
            model_name='strategyeventrecord',
            name='sequence_number',
            field=models.PositiveIntegerField(default=0, help_text='Monotonically increasing counter within a single tick batch. Preserves the logical ordering of events that share the same timestamp.'),
        ),
        migrations.AddField(
            model_name='trade',
            name='sequence_number',
            field=models.PositiveIntegerField(default=0, help_text='Monotonically increasing counter within a single tick batch. Preserves the logical ordering of events that share the same timestamp.'),
        ),
        migrations.AddField(
            model_name='tradingevent',
            name='sequence_number',
            field=models.PositiveIntegerField(default=0, help_text='Monotonically increasing counter within a single tick batch. Preserves the logical ordering of events that share the same timestamp.'),
        ),
    ]
