# Generated by Django 5.2.11 on 2026-03-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0030_add_sequence_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='planned_exit_price_formula',
            field=models.TextField(blank=True, help_text="Human-readable formula used to calculate planned_exit_price (e.g. '1.12345 + 0.00500')", null=True),
        ),
    ]
