# Generated by Django 5.2.11 on 2026-04-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0031_change_planned_exit_price_formula_to_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtesttask',
            name='debug_options',
            field=models.JSONField(blank=True, default=dict, help_text='Debug settings. Supported: {"tracemalloc": true}'),
        ),
        migrations.AddField(
            model_name='tradingtask',
            name='debug_options',
            field=models.JSONField(blank=True, default=dict, help_text='Debug settings. Supported: {"tracemalloc": true}'),
        ),
    ]
