# Generated by Django 5.2.7 on 2025-12-17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0008_rename_market_celery_tasks_table"),
        ("trading", "0031_remove_legacy_trade_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="TradingEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=64)),
                (
                    "severity",
                    models.CharField(db_index=True, default="info", max_length=16),
                ),
                ("description", models.TextField()),
                (
                    "instrument",
                    models.CharField(blank=True, db_index=True, max_length=32, null=True),
                ),
                (
                    "task_type",
                    models.CharField(blank=True, db_index=True, default="", max_length=32),
                ),
                ("task_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trading_events",
                        to="market.oandaaccount",
                    ),
                ),
                (
                    "execution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trading_events",
                        to="trading.taskexecution",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trading_events",
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "db_table": "trading_events",
                "verbose_name": "Trading Event",
                "verbose_name_plural": "Trading Events",
                "ordering": ["-created_at"],
            },
        ),
    ]
