# Generated by Django 5.2.7 on 2025-12-17 22:34

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0032_trading_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorStrategyLayerState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_index', models.PositiveIntegerField(help_text='0-based layer index')),
                ('is_open', models.BooleanField(default=False)),
                ('entry_price', models.DecimalField(blank=True, decimal_places=6, help_text='Price where this layer was opened', max_digits=15, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('close_price', models.DecimalField(blank=True, decimal_places=6, help_text='Price where this layer was closed', max_digits=15, null=True)),
                ('units', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Units allocated to this layer', max_digits=15)),
                ('realized_pnl', models.DecimalField(blank=True, decimal_places=2, help_text='Realized P&L when the layer is closed', max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Floor Strategy Layer State',
                'verbose_name_plural': 'Floor Strategy Layer States',
                'db_table': 'floor_strategy_layer_states',
            },
        ),
        migrations.CreateModel(
            name='FloorStrategyTaskState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Created'), ('running', 'Running'), ('stopped', 'Stopped'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='created', help_text='Persisted strategy lifecycle status', max_length=20)),
                ('side', models.CharField(blank=True, choices=[('long', 'Long'), ('short', 'Short')], help_text='Current floor strategy side (long/short)', max_length=10, null=True)),
                ('reference_price', models.DecimalField(blank=True, decimal_places=6, help_text='Reference price used to build/anchor floor layers', max_digits=15, null=True)),
                ('last_tick_at', models.DateTimeField(blank=True, help_text='Timestamp of the last processed tick (best-effort)', null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Floor Strategy Task State',
                'verbose_name_plural': 'Floor Strategy Task States',
                'db_table': 'floor_strategy_task_states',
            },
        ),
        migrations.RemoveField(
            model_name='backtest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='backtestresult',
            name='backtest',
        ),
        migrations.RemoveField(
            model_name='event',
            name='account',
        ),
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='related_event',
        ),
        migrations.RemoveField(
            model_name='strategycomparison',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tickdata',
            name='account',
        ),
        migrations.RenameIndex(
            model_name='celerytaskstatus',
            new_name='tcs_tn_st_idx',
            old_name='trading_mana_task_name_status_idx',
        ),
        migrations.RenameIndex(
            model_name='celerytaskstatus',
            new_name='tcs_celery_id_idx',
            old_name='trading_mana_celery_task_id_idx',
        ),
        migrations.RenameIndex(
            model_name='celerytaskstatus',
            new_name='tcs_hb_idx',
            old_name='trading_mana_last_heartbeat_at_idx',
        ),
        migrations.RenameIndex(
            model_name='taskexecutionresult',
            new_name='task_execut_task_ty_27908a_idx',
            old_name='task_execut_task_ty_0ed513_idx',
        ),
        migrations.RenameIndex(
            model_name='taskexecutionresult',
            new_name='task_execut_success_7c71fa_idx',
            old_name='task_execut_success_61d1aa_idx',
        ),
        migrations.RemoveField(
            model_name='backtesttask',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='backtesttask',
            name='oanda_account',
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='cpu_limit_cores',
            field=models.IntegerField(blank=True, help_text='CPU cores limit configured for execution', null=True),
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='memory_limit_mb',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Memory limit in MB configured for execution', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='peak_memory_mb',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peak memory usage in MB during execution', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='backtesttask',
            name='data_source',
            field=models.CharField(choices=[('postgresql', 'PostgreSQL'), ('athena', 'AWS Athena'), ('s3', 'AWS S3')], default='postgresql', help_text='Data source for historical tick data', max_length=20),
        ),
        migrations.AlterField(
            model_name='tradingtask',
            name='name',
            field=models.CharField(help_text='Human-readable name for this trading task', max_length=255),
        ),
        migrations.AddField(
            model_name='floorstrategytaskstate',
            name='backtest_task',
            field=models.OneToOneField(blank=True, help_text='Associated backtest task (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='floor_state', to='trading.backtesttask'),
        ),
        migrations.AddField(
            model_name='floorstrategytaskstate',
            name='trading_task',
            field=models.OneToOneField(blank=True, help_text='Associated live trading task (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='floor_state', to='trading.tradingtask'),
        ),
        migrations.AddField(
            model_name='floorstrategylayerstate',
            name='floor_state',
            field=models.ForeignKey(help_text='Owning floor strategy task state', on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='trading.floorstrategytaskstate'),
        ),
        migrations.DeleteModel(
            name='Backtest',
        ),
        migrations.DeleteModel(
            name='BacktestResult',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='StrategyComparison',
        ),
        migrations.DeleteModel(
            name='TickData',
        ),
        migrations.AddIndex(
            model_name='floorstrategytaskstate',
            index=models.Index(fields=['status', 'updated_at'], name='floor_strat_status_dd2b69_idx'),
        ),
        migrations.AddConstraint(
            model_name='floorstrategytaskstate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('trading_task__isnull', False), ('backtest_task__isnull', True)), models.Q(('trading_task__isnull', True), ('backtest_task__isnull', False)), _connector='OR'), name='floor_state_exactly_one_task'),
        ),
        migrations.AddIndex(
            model_name='floorstrategylayerstate',
            index=models.Index(fields=['floor_state', 'is_open'], name='floor_strat_floor_s_f620d2_idx'),
        ),
        migrations.AddConstraint(
            model_name='floorstrategylayerstate',
            constraint=models.UniqueConstraint(fields=('floor_state', 'layer_index'), name='unique_floor_layer_per_state'),
        ),
    ]
