# Generated by Django 5.2.11 on 2026-04-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0032_add_debug_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='adverse_pips',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Pips distance from the previous entry when this position was opened', max_digits=12, null=True),
        ),
    ]
