# Generated by Django 5.2.7 on 2025-12-22 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0033_floorstrategylayerstate_floorstrategytaskstate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionEquityPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(help_text='Monotonic per-execution sequence')),
                ('timestamp', models.DateTimeField(blank=True, help_text='Point timestamp (best-effort)', null=True)),
                ('timestamp_raw', models.CharField(blank=True, default='', help_text='Original timestamp string when parsing fails', max_length=64)),
                ('balance', models.DecimalField(decimal_places=2, help_text='Account balance after applying realized P&L', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution', models.ForeignKey(help_text='Owning task execution', on_delete=django.db.models.deletion.CASCADE, related_name='equity_point_rows', to='trading.taskexecution')),
            ],
            options={
                'verbose_name': 'Execution Equity Point',
                'verbose_name_plural': 'Execution Equity Points',
                'db_table': 'execution_equity_points',
                'ordering': ['sequence', 'id'],
                'indexes': [models.Index(fields=['execution', 'sequence'], name='execution_e_executi_c39f41_idx'), models.Index(fields=['execution', 'timestamp'], name='execution_e_executi_c5a318_idx')],
                'constraints': [models.UniqueConstraint(fields=('execution', 'sequence'), name='uniq_execution_equity_point_sequence')],
            },
        ),
        migrations.CreateModel(
            name='ExecutionMetricsCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed', models.IntegerField(blank=True, help_text='Best-effort ticks processed', null=True)),
                ('total_return', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('realized_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('unrealized_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_trades', models.IntegerField(default=0)),
                ('winning_trades', models.IntegerField(default=0)),
                ('losing_trades', models.IntegerField(default=0)),
                ('win_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('max_drawdown', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sharpe_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('profit_factor', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('average_win', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('average_loss', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution', models.ForeignKey(help_text='Owning task execution', on_delete=django.db.models.deletion.CASCADE, related_name='metrics_checkpoints', to='trading.taskexecution')),
            ],
            options={
                'verbose_name': 'Execution Metrics Checkpoint',
                'verbose_name_plural': 'Execution Metrics Checkpoints',
                'db_table': 'execution_metrics_checkpoints',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['execution', 'created_at'], name='execution_m_executi_c07880_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExecutionStrategyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(help_text='Monotonic per-execution sequence')),
                ('event_type', models.CharField(blank=True, db_index=True, default='', help_text="Best-effort event['type'] for filtering/debug", max_length=64)),
                ('event', models.JSONField(default=dict, help_text='Raw strategy event payload')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution', models.ForeignKey(help_text='Owning task execution', on_delete=django.db.models.deletion.CASCADE, related_name='strategy_event_rows', to='trading.taskexecution')),
            ],
            options={
                'verbose_name': 'Execution Strategy Event',
                'verbose_name_plural': 'Execution Strategy Events',
                'db_table': 'execution_strategy_events',
                'ordering': ['sequence', 'id'],
                'indexes': [models.Index(fields=['execution', 'sequence'], name='execution_s_executi_cda605_idx'), models.Index(fields=['execution', 'created_at'], name='execution_s_executi_e015eb_idx')],
                'constraints': [models.UniqueConstraint(fields=('execution', 'sequence'), name='uniq_execution_strategy_event_sequence')],
            },
        ),
        migrations.CreateModel(
            name='ExecutionTradeLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(help_text='Monotonic per-execution sequence')),
                ('trade', models.JSONField(default=dict, help_text='Raw trade payload')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution', models.ForeignKey(help_text='Owning task execution', on_delete=django.db.models.deletion.CASCADE, related_name='trade_log_rows', to='trading.taskexecution')),
            ],
            options={
                'verbose_name': 'Execution Trade Log Entry',
                'verbose_name_plural': 'Execution Trade Log Entries',
                'db_table': 'execution_trade_logs',
                'ordering': ['sequence', 'id'],
                'indexes': [models.Index(fields=['execution', 'sequence'], name='execution_t_executi_1e4ead_idx'), models.Index(fields=['execution', 'created_at'], name='execution_t_executi_a587bd_idx')],
                'constraints': [models.UniqueConstraint(fields=('execution', 'sequence'), name='uniq_execution_trade_log_sequence')],
            },
        ),
    ]
