# Generated by Django 5.2.11 on 2026-04-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0033_add_adverse_pips_to_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='margin_ratio',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Margin closeout ratio at the time this trade was executed. Stored as a fraction (e.g. 0.791 = 79.1%).', max_digits=10, null=True),
        ),
    ]
