# Generated by Django 5.2.11 on 2026-04-05 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0034_add_margin_ratio_to_trade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='layer_index',
            field=models.IntegerField(blank=True, help_text='Layer index for Floor strategy (1-based: L1, L2, ...; null for other strategies)', null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='retracement_count',
            field=models.IntegerField(blank=True, help_text='Retracement index for this position (0-based: R0=initial entry, R1=first retracement, ...)', null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='layer_index',
            field=models.IntegerField(blank=True, db_index=True, help_text='Layer index for Floor strategy-related trades (1-based: L1, L2, ...)', null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='retracement_count',
            field=models.IntegerField(blank=True, help_text='Retracement index at the time of this trade (0-based: R0=initial, R1=first retracement, ...)', null=True),
        ),
    ]
