# Generated by Django 5.2.7 on 2026-01-10 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0034_executionequitypoint_executionmetricscheckpoint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtesttask',
            name='pip_size',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='Pip size for the instrument (e.g., 0.0001 for EUR_USD). If not provided, will be fetched from OANDA account.', max_digits=10, null=True),
        ),
    ]
