# Generated by Django 5.2.7 on 2026-01-10 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0035_add_pip_size_to_backtest_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtesttask',
            name='instrument',
            field=models.CharField(default='USD_JPY', help_text='Trading instrument (e.g., EUR_USD, USD_JPY)', max_length=20),
        ),
    ]
