# Generated by Django 5.2.7 on 2026-01-10 01:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0036_add_instrument_field_to_backtest_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingtask',
            name='instrument',
            field=models.CharField(default='USD_JPY', help_text='Trading instrument (e.g., EUR_USD, USD_JPY)', max_length=20),
        ),
        migrations.AlterField(
            model_name='backtesttask',
            name='pip_size',
            field=models.DecimalField(blank=True, decimal_places=5, default=Decimal('0.01'), help_text='Pip size for the instrument (e.g., 0.0001 for EUR_USD, 0.01 for USD_JPY). If not provided, will be fetched from OANDA account.', max_digits=10, null=True),
        ),
    ]
