# Generated by Django 5.2.7 on 2026-01-10 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0037_add_instrument_to_trading_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionStateSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(help_text='Monotonic sequence number for this execution')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the snapshot was created')),
                ('strategy_state', models.JSONField(default=dict, help_text='Strategy-specific state dictionary')),
                ('current_balance', models.DecimalField(decimal_places=2, help_text='Current account balance', max_digits=15)),
                ('open_positions', models.JSONField(default=list, help_text='List of open position dictionaries')),
                ('ticks_processed', models.IntegerField(default=0, help_text='Number of ticks processed so far')),
                ('last_tick_timestamp', models.CharField(blank=True, default='', help_text='ISO format timestamp of last processed tick', max_length=64)),
                ('metrics', models.JSONField(default=dict, help_text='Current performance metrics dictionary')),
                ('execution', models.ForeignKey(help_text='Associated task execution', on_delete=django.db.models.deletion.CASCADE, related_name='state_snapshots', to='trading.taskexecution')),
            ],
            options={
                'verbose_name': 'Execution State Snapshot',
                'verbose_name_plural': 'Execution State Snapshots',
                'db_table': 'execution_state_snapshots',
                'ordering': ['-sequence'],
                'indexes': [models.Index(fields=['execution', 'sequence'], name='execution_s_executi_98c0c2_idx'), models.Index(fields=['execution', 'timestamp'], name='execution_s_executi_49bb7d_idx')],
                'constraints': [models.UniqueConstraint(fields=('execution', 'sequence'), name='unique_execution_state_snapshot')],
            },
        ),
    ]
