# Generated by Django 5.2.13 on 2026-04-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0038_include_paused_in_active_trading_account_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celerytaskstatus',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('paused', 'Paused'), ('stopped', 'Stopped'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='running', max_length=32),
        ),
    ]
