# Generated by Django 5.2.7 on 2026-01-10 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0038_add_execution_state_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionstrategyevent',
            name='strategy_type',
            field=models.CharField(blank=True, db_index=True, default='', help_text="Strategy type identifier (e.g., 'floor', 'momentum') for filtering and registry lookup", max_length=64),
        ),
        migrations.AddField(
            model_name='executionstrategyevent',
            name='timestamp',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Event timestamp parsed from event data, used for chronological ordering', null=True),
        ),
        migrations.AddIndex(
            model_name='executionstrategyevent',
            index=models.Index(fields=['execution', 'strategy_type'], name='execution_s_executi_b146a9_idx'),
        ),
        migrations.AddIndex(
            model_name='executionstrategyevent',
            index=models.Index(fields=['execution', 'timestamp'], name='execution_s_executi_286e38_idx'),
        ),
    ]
