# Generated by Django 5.2.7 on 2026-01-13 00:42

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_rename_oanda_api_h_account_fbf8a3_idx_oanda_api_h_account_b788ad_idx_and_more'),
        ('trading', '0039_add_strategy_type_and_timestamp_to_execution_strategy_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tradingtask',
            name='valid_trading_task_status',
        ),
        migrations.AlterField(
            model_name='backtesttask',
            name='pip_size',
            field=models.DecimalField(blank=True, db_column='pip_size', decimal_places=5, default=Decimal('0.01'), help_text='Pip size for the instrument (e.g., 0.0001 for EUR_USD, 0.01 for USD_JPY). If not provided, will be fetched from OANDA account.', max_digits=10, null=True),
        ),
        migrations.RenameField(
            model_name='backtesttask',
            old_name='pip_size',
            new_name='_pip_size',
        ),
        migrations.AddField(
            model_name='tradingtask',
            name='_pip_size',
            field=models.DecimalField(blank=True, db_column='pip_size', decimal_places=5, default=Decimal('0.01'), help_text='Pip size for the instrument (e.g., 0.0001 for EUR_USD, 0.01 for USD_JPY). If not provided, will be fetched from OANDA account.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='backtesttask',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('running', 'Running'), ('stopped', 'Stopped'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='created', help_text='Current task status', max_length=20),
        ),
        migrations.AlterField(
            model_name='floorstrategytaskstate',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('running', 'Running'), ('stopped', 'Stopped'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='created', help_text='Persisted strategy lifecycle status', max_length=20),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('running', 'Running'), ('stopped', 'Stopped'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='created', help_text='Current execution status', max_length=20),
        ),
        migrations.AlterField(
            model_name='tradingtask',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('running', 'Running'), ('stopped', 'Stopped'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='created', help_text='Current task status', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='tradingtask',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['created', 'running', 'stopped', 'failed'])), name='valid_trading_task_status'),
        ),
    ]
