# Generated by Django 5.2.13 on 2026-04-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0040_add_replay_markers_to_execution_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskexecutionsnapshot',
            name='strategy_config',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot of StrategyConfiguration at execution start (name, type, parameters)'),
        ),
        migrations.AddField(
            model_name='taskexecutionsnapshot',
            name='task_config',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot of task-level settings at execution start (instrument, balance, etc.)'),
        ),
    ]
