# Generated by Django 5.2.7 on 2026-01-13 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0040_remove_tradingtask_valid_trading_task_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtesttask',
            name='trading_mode',
            field=models.CharField(choices=[('netting', 'Netting Mode'), ('hedging', 'Hedging Mode')], default='netting', help_text='Trading mode: netting (aggregated positions) or hedging (independent trades)', max_length=20),
        ),
        migrations.AddField(
            model_name='tradingtask',
            name='trading_mode',
            field=models.CharField(choices=[('netting', 'Netting Mode'), ('hedging', 'Hedging Mode')], default='netting', help_text='Trading mode: netting (aggregated positions) or hedging (independent trades)', max_length=20),
        ),
    ]
