# Generated by Django 5.2.13 on 2026-04-16 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0041_add_config_snapshots_to_execution'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Layer',
        ),
    ]
