# Generated by Django 5.2.7 on 2026-01-18 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0041_add_trading_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floorstrategytaskstate',
            name='backtest_task',
        ),
        migrations.RemoveField(
            model_name='floorstrategytaskstate',
            name='trading_task',
        ),
        migrations.RemoveField(
            model_name='taskexecutionresult',
            name='account',
        ),
        migrations.RemoveField(
            model_name='taskexecutionresult',
            name='execution',
        ),
        migrations.RemoveField(
            model_name='tradingevent',
            name='account',
        ),
        migrations.RemoveField(
            model_name='tradingevent',
            name='execution',
        ),
        migrations.RemoveField(
            model_name='tradingevent',
            name='user',
        ),
        migrations.DeleteModel(
            name='FloorStrategyLayerState',
        ),
        migrations.DeleteModel(
            name='FloorStrategyTaskState',
        ),
        migrations.DeleteModel(
            name='TaskExecutionResult',
        ),
        migrations.DeleteModel(
            name='TradingEvent',
        ),
    ]
