# Generated by Django 5.2.13 on 2026-04-17 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0042_delete_layer'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskexecutionsnapshot',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='User-provided notes for this execution'),
        ),
    ]
