# Generated by Django 5.2.7 on 2026-01-18 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0042_remove_floorstrategytaskstate_backtest_task_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='celerytaskstatus',
            options={'verbose_name': 'Celery Task Status', 'verbose_name_plural': 'Celery Task Statuses'},
        ),
    ]
