# Generated by Django 5.2.7 on 2026-01-18 04:37

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_rename_oanda_api_h_account_fbf8a3_idx_oanda_api_h_account_b788ad_idx_and_more'),
        ('trading', '0043_alter_celerytaskstatus_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='celerytaskstatus',
            options={'verbose_name': 'Trading Celery Task Status', 'verbose_name_plural': 'Trading Celery Task Statuses'},
        ),
        migrations.CreateModel(
            name='FloorStrategyTaskState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Created'), ('running', 'Running'), ('stopped', 'Stopped'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='created', help_text='Persisted strategy lifecycle status', max_length=20)),
                ('side', models.CharField(blank=True, choices=[('long', 'Long'), ('short', 'Short')], help_text='Current floor strategy side (long/short)', max_length=10, null=True)),
                ('reference_price', models.DecimalField(blank=True, decimal_places=6, help_text='Reference price used to build/anchor floor layers', max_digits=15, null=True)),
                ('last_tick_at', models.DateTimeField(blank=True, help_text='Timestamp of the last processed tick (best-effort)', null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('backtest_task', models.OneToOneField(blank=True, help_text='Associated backtest task (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='floor_state', to='trading.backtesttask')),
                ('trading_task', models.OneToOneField(blank=True, help_text='Associated live trading task (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='floor_state', to='trading.tradingtask')),
            ],
            options={
                'verbose_name': 'Floor Strategy Task State',
                'verbose_name_plural': 'Floor Strategy Task States',
                'db_table': 'floor_strategy_task_states',
            },
        ),
        migrations.CreateModel(
            name='FloorStrategyLayerState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_index', models.PositiveIntegerField(help_text='0-based layer index')),
                ('is_open', models.BooleanField(default=False)),
                ('entry_price', models.DecimalField(blank=True, decimal_places=6, help_text='Price where this layer was opened', max_digits=15, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('close_price', models.DecimalField(blank=True, decimal_places=6, help_text='Price where this layer was closed', max_digits=15, null=True)),
                ('units', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Units allocated to this layer', max_digits=15)),
                ('realized_pnl', models.DecimalField(blank=True, decimal_places=2, help_text='Realized P&L when the layer is closed', max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('floor_state', models.ForeignKey(help_text='Owning floor strategy task state', on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='trading.floorstrategytaskstate')),
            ],
            options={
                'verbose_name': 'Floor Strategy Layer State',
                'verbose_name_plural': 'Floor Strategy Layer States',
                'db_table': 'floor_strategy_layer_states',
            },
        ),
        migrations.CreateModel(
            name='TaskExecutionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('backtest', 'Backtest'), ('trading', 'Trading')], db_index=True, help_text='Type of task (backtest or trading)', max_length=20)),
                ('task_id', models.IntegerField(db_index=True, help_text='ID of the task that was executed (matches TaskExecution.task_id)')),
                ('success', models.BooleanField(default=False, help_text='Whether execution completed successfully')),
                ('error', models.TextField(blank=True, default='', help_text='Error message if failed')),
                ('oanda_account_id', models.CharField(blank=True, default='', help_text='OANDA account ID string (for trading tasks)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the result record was created')),
                ('account', models.ForeignKey(blank=True, help_text='OANDA account used (for trading tasks)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_execution_results', to='market.oandaaccounts')),
                ('execution', models.OneToOneField(blank=True, help_text='Associated TaskExecution record (if created)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result', to='trading.taskexecution')),
            ],
            options={
                'verbose_name': 'Task Execution Result',
                'verbose_name_plural': 'Task Execution Results',
                'db_table': 'task_execution_results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TradingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('severity', models.CharField(db_index=True, default='info', max_length=16)),
                ('description', models.TextField()),
                ('instrument', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('task_type', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('task_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trading_events', to='market.oandaaccounts')),
                ('execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trading_events', to='trading.taskexecution')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trading_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trading Event',
                'verbose_name_plural': 'Trading Events',
                'db_table': 'trading_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TradingMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(help_text='Monotonic sequence number for ordering within execution')),
                ('timestamp', models.DateTimeField(help_text='Timestamp of the tick that generated this snapshot')),
                ('realized_pnl', models.DecimalField(decimal_places=5, help_text='Realized profit/loss from closed positions', max_digits=20)),
                ('unrealized_pnl', models.DecimalField(decimal_places=5, help_text='Unrealized profit/loss from open positions', max_digits=20)),
                ('total_pnl', models.DecimalField(decimal_places=5, help_text='Total profit/loss (realized + unrealized)', max_digits=20)),
                ('open_positions', models.IntegerField(help_text='Number of open positions at this tick')),
                ('total_trades', models.IntegerField(help_text='Total number of trades executed up to this tick')),
                ('tick_ask_min', models.DecimalField(decimal_places=5, help_text='Minimum ask price in this tick', max_digits=20)),
                ('tick_ask_max', models.DecimalField(decimal_places=5, help_text='Maximum ask price in this tick', max_digits=20)),
                ('tick_ask_avg', models.DecimalField(decimal_places=5, help_text='Average ask price in this tick', max_digits=20)),
                ('tick_bid_min', models.DecimalField(decimal_places=5, help_text='Minimum bid price in this tick', max_digits=20)),
                ('tick_bid_max', models.DecimalField(decimal_places=5, help_text='Maximum bid price in this tick', max_digits=20)),
                ('tick_bid_avg', models.DecimalField(decimal_places=5, help_text='Average bid price in this tick', max_digits=20)),
                ('tick_mid_min', models.DecimalField(decimal_places=5, help_text='Minimum mid price in this tick', max_digits=20)),
                ('tick_mid_max', models.DecimalField(decimal_places=5, help_text='Maximum mid price in this tick', max_digits=20)),
                ('tick_mid_avg', models.DecimalField(decimal_places=5, help_text='Average mid price in this tick', max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update timestamp')),
                ('execution', models.ForeignKey(help_text='Associated task execution', on_delete=django.db.models.deletion.CASCADE, related_name='trading_metrics', to='trading.taskexecution')),
            ],
            options={
                'verbose_name': 'Trading Metrics',
                'verbose_name_plural': 'Trading Metrics',
                'db_table': 'trading_metrics',
                'ordering': ['execution', 'sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='floorstrategytaskstate',
            index=models.Index(fields=['status', 'updated_at'], name='floor_strat_status_dd2b69_idx'),
        ),
        migrations.AddConstraint(
            model_name='floorstrategytaskstate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('trading_task__isnull', False), ('backtest_task__isnull', True)), models.Q(('trading_task__isnull', True), ('backtest_task__isnull', False)), _connector='OR'), name='floor_state_exactly_one_task'),
        ),
        migrations.AddIndex(
            model_name='floorstrategylayerstate',
            index=models.Index(fields=['floor_state', 'is_open'], name='floor_strat_floor_s_f620d2_idx'),
        ),
        migrations.AddConstraint(
            model_name='floorstrategylayerstate',
            constraint=models.UniqueConstraint(fields=('floor_state', 'layer_index'), name='unique_floor_layer_per_state'),
        ),
        migrations.AddIndex(
            model_name='taskexecutionresult',
            index=models.Index(fields=['task_type', 'task_id', 'created_at'], name='task_execut_task_ty_27908a_idx'),
        ),
        migrations.AddIndex(
            model_name='taskexecutionresult',
            index=models.Index(fields=['success'], name='task_execut_success_7c71fa_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingmetrics',
            index=models.Index(fields=['execution', 'sequence'], name='trading_met_executi_4ed60f_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingmetrics',
            index=models.Index(fields=['execution', 'timestamp'], name='trading_met_executi_18e0c7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tradingmetrics',
            unique_together={('execution', 'sequence')},
        ),
    ]
