# Generated by Django 5.2.13 on 2026-04-18 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0044_task_lifecycle_enhancements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backtesttask',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('starting', 'Starting'), ('running', 'Running'), ('paused', 'Paused'), ('idle', 'Idle'), ('draining', 'Draining'), ('stopping', 'Stopping'), ('stopped', 'Stopped'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='created', help_text='Current task status', max_length=20),
        ),
        migrations.AlterField(
            model_name='tradingtask',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('starting', 'Starting'), ('running', 'Running'), ('paused', 'Paused'), ('idle', 'Idle'), ('draining', 'Draining'), ('stopping', 'Stopping'), ('stopped', 'Stopped'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='created', help_text='Current task status', max_length=20),
        ),
    ]
