# Generated by Django 5.2.13 on 2026-04-19 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0045_alter_backtesttask_status_alter_tradingtask_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtesttask',
            name='sell_on_stop',
            field=models.BooleanField(default=False, help_text='Close all positions at current tick price when the task is stopped'),
        ),
    ]
