# Generated by Django 5.2.13 on 2026-04-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0046_backtesttask_sell_on_stop'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtesttask',
            name='celery_task_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Celery task_id for the current worker invocation', null=True),
        ),
        migrations.AddField(
            model_name='tradingtask',
            name='celery_task_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Celery task_id for the current worker invocation', null=True),
        ),
        migrations.AlterField(
            model_name='backtesttask',
            name='execution_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='UUID identifying the current execution run', null=True),
        ),
        migrations.AlterField(
            model_name='tradingtask',
            name='execution_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='UUID identifying the current execution run', null=True),
        ),
    ]
