# Generated by Django 5.2.13 on 2026-04-19 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0047_add_celery_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtesttask',
            name='market_idle_pre_close_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Switch to IDLE this many minutes before the market closes. 0 disables pre-close idling.'),
        ),
        migrations.AddField(
            model_name='backtesttask',
            name='market_idle_resume_delay_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Wait this many minutes after the market reopens before resuming trading. 0 disables the resume delay.'),
        ),
    ]
