# Generated by Django 5.2.13 on 2026-04-19 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0048_add_backtest_market_idle_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtesttask',
            name='market_close_enabled',
            field=models.BooleanField(default=True, help_text='Apply a weekly market-close window during the backtest. When disabled, market-idle thresholds are ignored.'),
        ),
        migrations.AddField(
            model_name='backtesttask',
            name='market_close_hour_utc',
            field=models.PositiveSmallIntegerField(default=21, help_text='Hour (UTC) at which the market closes on close weekday. 0–23.'),
        ),
        migrations.AddField(
            model_name='backtesttask',
            name='market_close_weekday',
            field=models.PositiveSmallIntegerField(default=4, help_text='Weekday the market closes (0 = Monday, 6 = Sunday). Default: 4 (Friday).'),
        ),
        migrations.AddField(
            model_name='backtesttask',
            name='market_open_hour_utc',
            field=models.PositiveSmallIntegerField(default=21, help_text='Hour (UTC) at which the market reopens on open weekday. 0–23.'),
        ),
        migrations.AddField(
            model_name='backtesttask',
            name='market_open_weekday',
            field=models.PositiveSmallIntegerField(default=6, help_text='Weekday the market reopens (0 = Monday, 6 = Sunday). Default: 6 (Sunday).'),
        ),
    ]
