# Generated by Django 5.2.13 on 2026-04-24 16:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0050_backtesttask_max_tick_gap_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtesttask',
            name='dispatch_idempotency_key',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Idempotency key rotated for each dispatch. Workers skip stale redeliveries with mismatched keys.'),
        ),
        migrations.AddField(
            model_name='executionstate',
            name='resume_cursor_timestamp',
            field=models.DateTimeField(blank=True, help_text='Exclusive cursor for resume/restart data loading. Defaults to last_tick_timestamp when unset.', null=True),
        ),
        migrations.AddField(
            model_name='executionstate',
            name='state_version',
            field=models.PositiveBigIntegerField(default=0, help_text='Monotonic state version for optimistic locking. Incremented on every persisted state update.'),
        ),
        migrations.AddField(
            model_name='tradingtask',
            name='dispatch_idempotency_key',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Idempotency key rotated for each dispatch. Workers skip stale redeliveries with mismatched keys.'),
        ),
        migrations.CreateModel(
            name='ExecutionMetricAggregate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(max_length=32)),
                ('task_id', models.UUIDField()),
                ('execution_id', models.UUIDField(blank=True, help_text='Execution run UUID (shared with Celery task_id)', null=True)),
                ('latest_timestamp', models.DateTimeField(blank=True, help_text='Latest metric timestamp persisted for this execution', null=True)),
                ('latest_metrics', models.JSONField(blank=True, default=dict, help_text='Latest metric snapshot for this execution')),
                ('sample_count', models.PositiveIntegerField(default=0, help_text='Number of metric rows ingested into this aggregate')),
                ('continuity_warnings', models.JSONField(blank=True, default=list, help_text='Validation warnings detected during resume/aggregation continuity checks')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'execution_metric_aggregates',
                'indexes': [models.Index(fields=['task_type', 'task_id', 'execution_id'], name='execution_m_task_ty_cf7ca1_idx')],
                'constraints': [models.UniqueConstraint(fields=('task_type', 'task_id', 'execution_id'), name='uniq_execution_metric_aggregate')],
            },
        ),
    ]
