# Generated by Django 5.2.13 on 2026-04-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0051_backtesttask_dispatch_idempotency_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionmetricaggregate',
            name='balance_max',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='Maximum observed current_balance in the aggregate window', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='executionmetricaggregate',
            name='balance_min',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='Minimum observed current_balance in the aggregate window', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='executionmetricaggregate',
            name='margin_ratio_max',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='Maximum observed margin_ratio in the aggregate window', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='executionmetricaggregate',
            name='margin_ratio_min',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='Minimum observed margin_ratio in the aggregate window', max_digits=20, null=True),
        ),
    ]
