# Generated by Codex on 2026-04-24

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0052_executionmetricaggregate_balance_max_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecoveryAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this recovery attempt",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[("backtest", "Backtest"), ("trading", "Trading")],
                        db_index=True,
                        help_text="Type of task (backtest or trading)",
                        max_length=32,
                    ),
                ),
                ("task_id", models.UUIDField(db_index=True, help_text="Recovered task UUID")),
                (
                    "execution_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Execution run UUID at the time of recovery",
                        null=True,
                    ),
                ),
                ("source", models.CharField(db_index=True, max_length=64)),
                ("reason", models.CharField(blank=True, default="", max_length=128)),
                ("action", models.CharField(max_length=64)),
                ("result", models.CharField(db_index=True, max_length=32)),
                ("detail", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Recovery Attempt",
                "verbose_name_plural": "Recovery Attempts",
                "db_table": "recovery_attempts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="recoveryattempt",
            index=models.Index(
                fields=["task_type", "task_id", "created_at"],
                name="recovery_at_task_ty_040fa1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="recoveryattempt",
            index=models.Index(
                fields=["source", "result", "created_at"],
                name="recovery_at_source_b60148_idx",
            ),
        ),
    ]
