# Generated by Codex on 2026-04-24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0053_recoveryattempt"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="position",
            index=models.Index(
                fields=["task_type", "task_id", "execution_id", "updated_at"],
                name="pos_task_exec_upd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="position",
            index=models.Index(
                fields=[
                    "task_type",
                    "task_id",
                    "execution_id",
                    "is_open",
                    "direction",
                    "-entry_time",
                ],
                name="pos_task_exec_state_idx",
            ),
        ),
    ]
