# Generated by Django 5.2.13 on 2026-04-25 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0054_add_position_query_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='layer_index',
            field=models.IntegerField(blank=True, help_text='Strategy-specific layer index for layered strategies (1-based: L1, L2, ...; null for strategies that do not use layers)', null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='layer_index',
            field=models.IntegerField(blank=True, db_index=True, help_text='Strategy-specific layer index for layered strategy trades (1-based: L1, L2, ...)', null=True),
        ),
    ]
