# Generated by Django 5.2.13 on 2026-05-10 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0058_backtest_initial_positions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backtesttask',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Optional description of this task'),
        ),
        migrations.AlterField(
            model_name='backtesttask',
            name='error_message',
            field=models.TextField(blank=True, help_text='Internal failure message if task failed', null=True),
        ),
        migrations.AlterField(
            model_name='backtesttask',
            name='error_traceback',
            field=models.TextField(blank=True, help_text='Internal traceback if task failed', null=True),
        ),
        migrations.AlterField(
            model_name='backtesttask',
            name='name',
            field=models.CharField(help_text='Human-readable name for this task', max_length=255),
        ),
        migrations.AlterField(
            model_name='backtesttask',
            name='sell_on_stop',
            field=models.BooleanField(default=False, help_text='Close all positions when the task is stopped'),
        ),
        migrations.AlterField(
            model_name='tradingtask',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Optional description of this task'),
        ),
        migrations.AlterField(
            model_name='tradingtask',
            name='error_message',
            field=models.TextField(blank=True, help_text='Internal failure message if task failed', null=True),
        ),
        migrations.AlterField(
            model_name='tradingtask',
            name='error_traceback',
            field=models.TextField(blank=True, help_text='Internal traceback if task failed', null=True),
        ),
        migrations.AlterField(
            model_name='tradingtask',
            name='name',
            field=models.CharField(help_text='Human-readable name for this task', max_length=255),
        ),
        migrations.AlterField(
            model_name='tradingtask',
            name='sell_on_stop',
            field=models.BooleanField(default=False, help_text='Close all positions when the task is stopped'),
        ),
    ]
