# Generated by Django 5.2.13 on 2026-05-10 14:50

from django.db import migrations, models


def backfill_execution_balance_currency(apps, schema_editor):
    BacktestTask = apps.get_model("trading", "BacktestTask")
    TradingTask = apps.get_model("trading", "TradingTask")
    ExecutionState = apps.get_model("trading", "ExecutionState")

    for task_id, currency in (
        BacktestTask.objects.exclude(account_currency="")
        .values_list("id", "account_currency")
        .iterator(chunk_size=1000)
    ):
        currency_code = str(currency or "").strip().upper()
        if currency_code:
            ExecutionState.objects.filter(
                current_balance_currency="",
                task_type="backtest",
                task_id=task_id,
            ).update(current_balance_currency=currency_code)

    for task in (
        TradingTask.objects.select_related("oanda_account")
        .only(
            "id",
            "oanda_account__currency",
        )
        .iterator(chunk_size=1000)
    ):
        currency_code = str(getattr(task.oanda_account, "currency", "") or "").strip().upper()
        if currency_code:
            ExecutionState.objects.filter(
                current_balance_currency="",
                task_type="trading",
                task_id=task.id,
            ).update(current_balance_currency=currency_code)

    # Position and trade quote currencies are derivable from instrument, and the
    # API enrichment paths already fall back to that derivation when these new
    # fields are blank. Avoid rewriting high-volume historical rows during a
    # schema migration; new writes populate the fields directly.


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0059_alter_backtesttask_description_and_more"),
        ("trading", "0059_strategy_config_revision"),
    ]

    operations = [
        migrations.AddField(
            model_name="backtesttask",
            name="display_currency",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Preferred currency for displaying balances and PnL. Empty uses account currency.",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="executionstate",
            name="current_balance_currency",
            field=models.CharField(
                blank=True, default="", help_text="Currency code for current_balance.", max_length=3
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="unrealized_pnl_currency",
            field=models.CharField(
                blank=True, default="", help_text="Currency code for unrealized_pnl.", max_length=3
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="price_currency",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Quote currency code for price and instrument-denominated trade amounts.",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="backtesttask",
            name="pip_size",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                default=None,
                help_text="Pip size for the instrument (e.g., 0.0001 for EUR_USD, 0.01 for USD_JPY). If not provided, will be fetched from OANDA account.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tradingtask",
            name="pip_size",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                default=None,
                help_text="Pip size for the instrument (e.g., 0.0001 for EUR_USD, 0.01 for USD_JPY). If not provided, will be fetched from OANDA account.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.RunPython(backfill_execution_balance_currency, migrations.RunPython.noop),
    ]
