# Generated by Codex on 2026-05-14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0060_backtesttask_display_currency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradingtask",
            name="display_currency",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Preferred currency for displaying balances and PnL.",
                max_length=3,
            ),
        ),
    ]
