# Generated by Django 5.2.13 on 2026-05-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0063_trading_initial_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='is_initial_position_seed',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this position was created from task initial-position settings.'),
        ),
        migrations.AddField(
            model_name='trade',
            name='is_initial_position_seed',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this trade was created from task initial-position settings.'),
        ),
    ]
