# Generated by Django 5.2.13 on 2026-05-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0067_snowball_rebuild_entry_buffer_cooldown'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtesttask',
            name='excluded_dates',
            field=models.JSONField(blank=True, default=list, help_text="Additional UTC calendar dates (ISO-8601 'YYYY-MM-DD') on which the backtest should treat the market as closed. Merged with the auto-detected holiday set when ``holidays_enabled`` is True; honoured on its own when it is False."),
        ),
        migrations.AddField(
            model_name='backtesttask',
            name='holidays_enabled',
            field=models.BooleanField(default=False, help_text="Treat days where two or more major FX centres (US, UK, Germany) are observing a public holiday as market-closed during the backtest. Useful for suppressing trading on Christmas, Good Friday, New Year's Day, etc."),
        ),
    ]
