# Generated by Codex on 2026-05-20

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0001_initial"),
        ("trading", "0069_backtesttask_in_memory_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="backtesttask",
            name="spread_filter_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Skip backtest ticks whose bid/ask spread exceeds max_spread_pips.",
            ),
        ),
        migrations.AddField(
            model_name="backtesttask",
            name="max_spread_pips",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0"),
                help_text=(
                    "Maximum allowed bid/ask spread in pips when spread_filter_enabled is true. "
                    "Ticks above this threshold are skipped and logged."
                ),
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="backtesttask",
            name="oanda_candle_filter_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Compare replayed backtest ticks with OANDA candles and skip outliers.",
            ),
        ),
        migrations.AddField(
            model_name="backtesttask",
            name="oanda_candle_filter_account",
            field=models.ForeignKey(
                blank=True,
                help_text="OANDA account used to fetch candle data for backtest tick validation.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="backtest_candle_filter_tasks",
                to="market.oandaaccounts",
            ),
        ),
        migrations.AddField(
            model_name="backtesttask",
            name="oanda_candle_filter_granularity",
            field=models.CharField(
                choices=[
                    ("S5", "5 Seconds"),
                    ("S10", "10 Seconds"),
                    ("S15", "15 Seconds"),
                    ("S30", "30 Seconds"),
                    ("M1", "1 Minute"),
                    ("M5", "5 Minutes"),
                    ("M15", "15 Minutes"),
                    ("M30", "30 Minutes"),
                    ("H1", "1 Hour"),
                    ("H4", "4 Hours"),
                    ("D", "1 Day"),
                ],
                default="M1",
                help_text="OANDA candle granularity used for backtest tick validation.",
                max_length=4,
            ),
        ),
        migrations.AddField(
            model_name="backtesttask",
            name="oanda_candle_filter_tolerance_pips",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("5"),
                help_text=(
                    "Allowed distance beyond the OANDA candle high/low in pips before "
                    "a replayed tick is treated as an outlier and skipped."
                ),
                max_digits=10,
            ),
        ),
    ]
