# Generated by Django 5.2.13 on 2026-05-21 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0070_backtest_tick_quality_filters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backtesttask',
            name='excluded_dates',
            field=models.JSONField(blank=True, default=list, help_text='Additional market-closed windows for the backtest. New entries are stored as {start, end, timezone} objects; legacy YYYY-MM-DD/MM-DD strings remain supported. Merged with the auto-detected holiday set when ``holidays_enabled`` is True; honoured on its own when it is False.'),
        ),
    ]
