# Generated by Django 5.2.13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0071_alter_backtesttask_excluded_dates"),
    ]

    operations = [
        migrations.AddField(
            model_name="backtesttask",
            name="backtest_tick_batch_size",
            field=models.PositiveIntegerField(
                default=1000,
                help_text=(
                    "Number of replayed ticks delivered to the backtest executor per batch. "
                    "Larger values reduce coordination overhead but make stop responsiveness "
                    "slightly coarser. Default: 1000."
                ),
            ),
        ),
    ]
