# Generated by Django 5.2.13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0072_backtesttask_backtest_tick_batch_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradingtask",
            name="tick_granularity",
            field=models.CharField(
                choices=[
                    ("tick", "All Ticks"),
                    ("1s", "1 Second"),
                    ("10s", "10 Seconds"),
                    ("15s", "15 Seconds"),
                    ("30s", "30 Seconds"),
                    ("1m", "1 Minute"),
                    ("5m", "5 Minutes"),
                    ("15m", "15 Minutes"),
                    ("30m", "30 Minutes"),
                    ("1h", "1 Hour"),
                ],
                default="tick",
                help_text=(
                    "Live tick sampling granularity. Use 'tick' for every tick, "
                    "or a time bucket such as '1s' or '1m' to use the first tick in each bucket."
                ),
                max_length=8,
            ),
        ),
    ]
