# Generated by Django 5.2.7 on 2025-12-08 00:24

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicAccountSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "registration_enabled",
                    models.BooleanField(
                        default=True, help_text="Whether new user registration is enabled"
                    ),
                ),
                (
                    "login_enabled",
                    models.BooleanField(default=True, help_text="Whether user login is enabled"),
                ),
                (
                    "email_whitelist_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Whether email whitelist is enforced for registration/login",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp when settings were last updated"
                    ),
                ),
            ],
            options={
                "verbose_name": "Public Account Settings",
                "verbose_name_plural": "Public Account Settings",
                "db_table": "public_account_settings",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text=(
                            "Designates that this user has all permissions "
                            "without explicitly assigning them."
                        ),
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=150, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=150, verbose_name="last name"),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text=(
                            "Designates whether this user should be treated as active. "
                            "Unselect this instead of deleting accounts."
                        ),
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="User's email address (used for login)",
                        max_length=254,
                        unique=True,
                    ),
                ),
                (
                    "email_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the user's email address has been verified",
                    ),
                ),
                (
                    "email_verification_token",
                    models.CharField(
                        blank=True,
                        help_text="Token for email verification",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "email_verification_sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when verification email was last sent",
                        null=True,
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="UTC",
                        help_text="User's preferred timezone (IANA timezone identifier)",
                        max_length=50,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("ja", "Japanese")],
                        default="en",
                        help_text="User's preferred language",
                        max_length=5,
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the account is locked due to failed login attempts",
                    ),
                ),
                (
                    "failed_login_attempts",
                    models.IntegerField(
                        default=0, help_text="Number of consecutive failed login attempts"
                    ),
                ),
                (
                    "last_login_attempt",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp of the last login attempt", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when the user account was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp when the user account was last updated"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        help_text="Username (auto-generated from email if not provided)",
                        max_length=150,
                        unique=True,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text=(
                            "The groups this user belongs to. A user will get all "
                            "permissions granted to each of their groups."
                        ),
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "users",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="BlockedIP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        db_index=True, help_text="Blocked IP address", unique=True
                    ),
                ),
                ("reason", models.CharField(help_text="Reason for blocking", max_length=255)),
                (
                    "failed_attempts",
                    models.IntegerField(
                        default=0, help_text="Number of failed login attempts from this IP"
                    ),
                ),
                (
                    "blocked_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when the IP was blocked"
                    ),
                ),
                (
                    "blocked_until",
                    models.DateTimeField(help_text="Timestamp when the block expires"),
                ),
                (
                    "is_permanent",
                    models.BooleanField(default=False, help_text="Whether the block is permanent"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin user who created the block (if manual)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blocked_ips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Blocked IP",
                "verbose_name_plural": "Blocked IPs",
                "db_table": "blocked_ips",
                "ordering": ["-blocked_at"],
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        db_index=True, help_text="Django session key", max_length=255, unique=True
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(help_text="IP address of the session")),
                (
                    "user_agent",
                    models.TextField(blank=True, help_text="User agent string from the browser"),
                ),
                (
                    "login_time",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when the session was created"
                    ),
                ),
                (
                    "last_activity",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp of the last activity in this session"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the session is currently active"
                    ),
                ),
                (
                    "logout_time",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp when the session was terminated", null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User associated with this session",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Session",
                "verbose_name_plural": "User Sessions",
                "db_table": "user_sessions",
                "ordering": ["-login_time"],
            },
        ),
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "notification_enabled",
                    models.BooleanField(
                        default=True, help_text="Whether notifications are enabled"
                    ),
                ),
                (
                    "notification_email",
                    models.BooleanField(
                        default=True, help_text="Whether to send email notifications"
                    ),
                ),
                (
                    "notification_browser",
                    models.BooleanField(
                        default=True, help_text="Whether to send browser notifications"
                    ),
                ),
                (
                    "settings_json",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional settings stored as JSON"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when settings were created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp when settings were last updated"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="User associated with these settings",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Settings",
                "verbose_name_plural": "User Settings",
                "db_table": "user_settings",
            },
        ),
        migrations.CreateModel(
            name="WhitelistedEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "email_pattern",
                    models.CharField(
                        db_index=True,
                        help_text=(
                            "Email address or domain pattern "
                            "(e.g., user@example.com or *@example.com)"
                        ),
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Optional description for this whitelist entry",
                        max_length=255,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this whitelist entry is active"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when the entry was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp when the entry was last updated"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin user who created this entry",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="whitelisted_emails_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Whitelisted Email",
                "verbose_name_plural": "Whitelisted Emails",
                "db_table": "whitelisted_emails",
                "ordering": ["email_pattern"],
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="users_email_4b85f2_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["is_locked"], name="users_is_lock_f43618_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["created_at"], name="users_created_6541e9_idx"),
        ),
        migrations.AddIndex(
            model_name="blockedip",
            index=models.Index(fields=["ip_address"], name="blocked_ips_ip_addr_d839f3_idx"),
        ),
        migrations.AddIndex(
            model_name="blockedip",
            index=models.Index(fields=["blocked_until"], name="blocked_ips_blocked_aef64d_idx"),
        ),
        migrations.AddIndex(
            model_name="blockedip",
            index=models.Index(fields=["is_permanent"], name="blocked_ips_is_perm_f80ec5_idx"),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(fields=["user", "is_active"], name="user_sessio_user_id_bb1b83_idx"),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(fields=["session_key"], name="user_sessio_session_cc84b9_idx"),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(fields=["ip_address"], name="user_sessio_ip_addr_0626e4_idx"),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(fields=["login_time"], name="user_sessio_login_t_571fa8_idx"),
        ),
        migrations.AddIndex(
            model_name="whitelistedemail",
            index=models.Index(fields=["email_pattern"], name="whitelisted_email_p_8645e2_idx"),
        ),
        migrations.AddIndex(
            model_name="whitelistedemail",
            index=models.Index(fields=["is_active"], name="whitelisted_is_acti_501643_idx"),
        ),
    ]
