# Generated by Django 5.2.7 on 2026-01-20 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='accountsecurityevent',
            new_name='account_sec_categor_ebfc3a_idx',
            old_name='account_sec_categor_582846_idx',
        ),
        migrations.RenameIndex(
            model_name='accountsecurityevent',
            new_name='account_sec_severit_f21bb0_idx',
            old_name='account_sec_severit_04e69d_idx',
        ),
        migrations.RenameIndex(
            model_name='usernotification',
            new_name='user_notifi_user_id_b80f4f_idx',
            old_name='user_notif_user_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='usernotification',
            new_name='user_notifi_user_id_6c01c8_idx',
            old_name='user_notif_user_read_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='usernotification',
            new_name='user_notifi_notific_9264bf_idx',
            old_name='user_notif_type_ts_idx',
        ),
    ]
