# Generated by Django 5.2.11 on 2026-03-03 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_account_sec_categor_582846_idx_account_sec_categor_ebfc3a_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, help_text='Opaque refresh token value', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the token was issued')),
                ('expires_at', models.DateTimeField(help_text='When the token expires')),
                ('revoked_at', models.DateTimeField(blank=True, help_text='When the token was revoked (null = active)', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address that created this token', null=True)),
                ('user_agent', models.TextField(blank=True, default='', help_text='User agent that created this token')),
                ('session', models.ForeignKey(blank=True, help_text='Session that created this token (for tracking)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refresh_tokens', to='accounts.usersession')),
                ('user', models.ForeignKey(help_text='Owner of this refresh token', on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Refresh Token',
                'verbose_name_plural': 'Refresh Tokens',
                'db_table': 'refresh_tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='refresh_tok_token_e21bac_idx'), models.Index(fields=['user', 'revoked_at'], name='refresh_tok_user_id_973457_idx'), models.Index(fields=['expires_at'], name='refresh_tok_expires_a128d9_idx')],
            },
        ),
    ]
