# Generated by Django 5.2.11 on 2026-03-12 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_refresh_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='last_activity',
        ),
    ]
