# Generated by Django 5.2.7 on 2026-01-13 00:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_security_event'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='accountsecurityevent',
            new_name='account_sec_event_t_369190_idx',
            old_name='account_secur_event_ty_6c54b1_idx',
        ),
        migrations.RenameIndex(
            model_name='accountsecurityevent',
            new_name='account_sec_categor_ebfc3a_idx',
            old_name='account_secur_categor_582846_idx',
        ),
        migrations.RenameIndex(
            model_name='accountsecurityevent',
            new_name='account_sec_severit_f21bb0_idx',
            old_name='account_secur_severit_04e69d_idx',
        ),
        migrations.RenameIndex(
            model_name='usernotification',
            new_name='user_notifi_user_id_b80f4f_idx',
            old_name='user_notif_user_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='usernotification',
            new_name='user_notifi_user_id_6c01c8_idx',
            old_name='user_notif_user_read_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='usernotification',
            new_name='user_notifi_notific_9264bf_idx',
            old_name='user_notif_type_ts_idx',
        ),
        migrations.AlterField(
            model_name='accountsecurityevent',
            name='user_agent',
            field=models.TextField(blank=True, default='', help_text='User agent string (if available)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_verification_token',
            field=models.CharField(blank=True, default='', help_text='Token for email verification', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Username (auto-generated from email if not provided)', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Username can only contain letters, numbers, underscores, periods, and dashes.', regex='^[a-zA-Z0-9._-]+$')]),
        ),
    ]
