# Generated by Django 5.2.7 on 2026-01-13 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_account_secur_event_ty_6c54b1_idx_account_sec_event_t_369190_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='user_agent',
            field=models.TextField(blank=True, default='', help_text='User agent string from the browser'),
        ),
    ]
