# Generated by Django 5.2.13 on 2026-05-10 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_hash_refresh_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_token_version',
            field=models.PositiveIntegerField(default=0, help_text='Version claim used to revoke already-issued access tokens'),
        ),
    ]
