# Generated by Django 5.2.7 on 2025-12-08 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OandaAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("account_id", models.CharField(help_text="OANDA account ID", max_length=100)),
                (
                    "api_token",
                    models.CharField(help_text="Encrypted OANDA API token", max_length=500),
                ),
                (
                    "api_type",
                    models.CharField(
                        choices=[("practice", "Practice"), ("live", "Live")],
                        default="practice",
                        help_text="API endpoint type (practice or live)",
                        max_length=10,
                    ),
                ),
                (
                    "jurisdiction",
                    models.CharField(
                        choices=[
                            ("US", "United States"),
                            ("JP", "Japan"),
                            ("EU", "European Union"),
                            ("UK", "United Kingdom"),
                            ("AU", "Australia"),
                            ("OTHER", "Other/International"),
                        ],
                        default="OTHER",
                        help_text="Regulatory jurisdiction for this account",
                        max_length=10,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", help_text="Account base currency", max_length=3
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Current account balance",
                        max_digits=15,
                    ),
                ),
                (
                    "margin_used",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Margin currently used by open positions",
                        max_digits=15,
                    ),
                ),
                (
                    "margin_available",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Margin available for new positions",
                        max_digits=15,
                    ),
                ),
                (
                    "unrealized_pnl",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Unrealized profit/loss from open positions",
                        max_digits=15,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Whether the account is active"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("idle", "Idle"),
                            ("trading", "Trading"),
                            ("paused", "Paused"),
                            ("error", "Error"),
                        ],
                        default="idle",
                        help_text="Current account status",
                        max_length=20,
                    ),
                ),
                (
                    "enable_position_differentiation",
                    models.BooleanField(
                        default=False,
                        help_text="Enable automatic position differentiation for FIFO flexibility",
                    ),
                ),
                (
                    "position_diff_increment",
                    models.IntegerField(
                        default=1,
                        help_text="Increment amount for position differentiation (1-100 units)",
                    ),
                ),
                (
                    "position_diff_pattern",
                    models.CharField(
                        choices=[
                            ("increment", "Increment"),
                            ("decrement", "Decrement"),
                            ("alternating", "Alternating"),
                        ],
                        default="increment",
                        help_text="Pattern for position differentiation",
                        max_length=20,
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the default account for market data collection",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when the account was added"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp when the account was last updated"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this OANDA account",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oanda_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "OANDA Account",
                "verbose_name_plural": "OANDA Accounts",
                "db_table": "oanda_accounts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TickData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "instrument",
                    models.CharField(
                        db_index=True, help_text="Currency pair (e.g., 'EUR_USD')", max_length=10
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, help_text="Timestamp when the tick was received"
                    ),
                ),
                (
                    "bid",
                    models.DecimalField(decimal_places=5, help_text="Bid price", max_digits=10),
                ),
                (
                    "ask",
                    models.DecimalField(decimal_places=5, help_text="Ask price", max_digits=10),
                ),
                (
                    "mid",
                    models.DecimalField(
                        decimal_places=5,
                        help_text="Mid price (average of bid and ask)",
                        max_digits=10,
                    ),
                ),
                (
                    "spread",
                    models.DecimalField(
                        decimal_places=5,
                        help_text="Spread (difference between ask and bid)",
                        max_digits=10,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when the record was created"
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        help_text="OANDA account that received this tick",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tick_data",
                        to="market.oandaaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tick Data",
                "verbose_name_plural": "Tick Data",
                "db_table": "tick_data",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="oandaaccount",
            index=models.Index(fields=["user", "is_active"], name="oanda_accou_user_id_be2e7d_idx"),
        ),
        migrations.AddIndex(
            model_name="oandaaccount",
            index=models.Index(fields=["account_id"], name="oanda_accou_account_707afc_idx"),
        ),
        migrations.AddIndex(
            model_name="oandaaccount",
            index=models.Index(
                fields=["user", "is_default"], name="oanda_accou_user_id_3f5a4a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="oandaaccount",
            index=models.Index(fields=["created_at"], name="oanda_accou_created_da4c80_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="oandaaccount",
            unique_together={("user", "account_id")},
        ),
        migrations.AddIndex(
            model_name="tickdata",
            index=models.Index(fields=["instrument"], name="tick_data_instrum_7f586e_idx"),
        ),
        migrations.AddIndex(
            model_name="tickdata",
            index=models.Index(fields=["timestamp"], name="tick_data_timesta_a4b109_idx"),
        ),
        migrations.AddIndex(
            model_name="tickdata",
            index=models.Index(
                fields=["instrument", "timestamp"], name="tick_data_instrum_b325fe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tickdata",
            index=models.Index(
                fields=["account", "instrument", "timestamp"], name="tick_data_account_0fb6f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tickdata",
            index=models.Index(fields=["created_at"], name="tick_data_created_69aebd_idx"),
        ),
    ]
