# Generated by Django 5.2.7 on 2026-01-19 19:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryTaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(db_index=True, max_length=200)),
                ('instance_key', models.CharField(blank=True, db_index=True, default='default', max_length=200)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('worker', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('running', 'Running'), ('stop_requested', 'Stop Requested'), ('stopped', 'Stopped'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='running', max_length=32)),
                ('status_message', models.TextField(blank=True, default='')),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Celery Task Status',
                'verbose_name_plural': 'Celery Task Statuses',
                'db_table': 'market_celery_tasks',
                'indexes': [models.Index(fields=['task_name', 'status'], name='market_mana_task_na_57e1fc_idx'), models.Index(fields=['celery_task_id'], name='market_mana_celery__e5025a_idx'), models.Index(fields=['last_heartbeat_at'], name='market_mana_last_he_d7d6f2_idx')],
                'constraints': [models.UniqueConstraint(fields=('task_name', 'instance_key'), name='uniq_market_task_name_instance_key')],
            },
        ),
        migrations.CreateModel(
            name='OandaAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(help_text='OANDA account ID', max_length=100)),
                ('api_token', models.CharField(help_text='Encrypted OANDA API token', max_length=500)),
                ('api_type', models.CharField(choices=[('practice', 'Practice'), ('live', 'Live')], default='practice', help_text='API endpoint type (practice or live)', max_length=20)),
                ('jurisdiction', models.CharField(choices=[('US', 'United States'), ('JP', 'Japan'), ('OTHER', 'Other/International')], default='OTHER', help_text='Regulatory jurisdiction for this account', max_length=10)),
                ('currency', models.CharField(default='USD', help_text='Account base currency', max_length=3)),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='Current account balance', max_digits=15)),
                ('margin_used', models.DecimalField(decimal_places=2, default=0, help_text='Margin currently used by open positions', max_digits=15)),
                ('margin_available', models.DecimalField(decimal_places=2, default=0, help_text='Margin available for new positions', max_digits=15)),
                ('unrealized_pnl', models.DecimalField(decimal_places=2, default=0, help_text='Unrealized profit/loss from open positions', max_digits=15)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the account is active')),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default account for market data collection')),
                ('is_used', models.BooleanField(default=False, help_text='Whether this account is currently used by any running process')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the account was added')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the account was last updated')),
                ('user', models.ForeignKey(help_text='User who owns this OANDA account', on_delete=django.db.models.deletion.CASCADE, related_name='oanda_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OANDA Account',
                'verbose_name_plural': 'OANDA Accounts',
                'db_table': 'oanda_accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('category', models.CharField(db_index=True, default='market', max_length=32)),
                ('severity', models.CharField(db_index=True, default='info', max_length=16)),
                ('description', models.TextField()),
                ('instrument', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_events', to=settings.AUTH_USER_MODEL)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_events', to='market.oandaaccounts')),
            ],
            options={
                'verbose_name': 'Market Event',
                'verbose_name_plural': 'Market Events',
                'db_table': 'market_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OandaApiHealthStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(db_index=True, default=False)),
                ('checked_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_health_statuses', to='market.oandaaccounts')),
            ],
            options={
                'verbose_name': 'OANDA API Health Status',
                'verbose_name_plural': 'OANDA API Health Statuses',
                'db_table': 'oanda_api_health_statuses',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='TickData',
            fields=[
                ('instrument', models.CharField(db_index=True, help_text="Currency pair (e.g., 'EUR_USD')", max_length=10)),
                ('timestamp', models.DateTimeField(db_index=True, help_text='Timestamp when the tick was received')),
                ('pk', models.CompositePrimaryKey('instrument', 'timestamp', blank=True, editable=False, primary_key=True, serialize=False)),
                ('bid', models.DecimalField(decimal_places=5, help_text='Bid price', max_digits=10)),
                ('ask', models.DecimalField(decimal_places=5, help_text='Ask price', max_digits=10)),
                ('mid', models.DecimalField(decimal_places=5, help_text='Mid price (average of bid and ask)', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
            ],
            options={
                'verbose_name': 'Tick Data',
                'verbose_name_plural': 'Tick Data',
                'db_table': 'tick_data',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['instrument'], name='tick_data_instrum_7f586e_idx'), models.Index(fields=['timestamp'], name='tick_data_timesta_a4b109_idx'), models.Index(fields=['created_at'], name='tick_data_created_69aebd_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='oandaaccounts',
            index=models.Index(fields=['user', 'is_active'], name='oanda_accou_user_id_be2e7d_idx'),
        ),
        migrations.AddIndex(
            model_name='oandaaccounts',
            index=models.Index(fields=['account_id'], name='oanda_accou_account_707afc_idx'),
        ),
        migrations.AddIndex(
            model_name='oandaaccounts',
            index=models.Index(fields=['user', 'is_default'], name='oanda_accou_user_id_3f5a4a_idx'),
        ),
        migrations.AddIndex(
            model_name='oandaaccounts',
            index=models.Index(fields=['created_at'], name='oanda_accou_created_da4c80_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='oandaaccounts',
            unique_together={('user', 'account_id', 'api_type')},
        ),
        migrations.AddIndex(
            model_name='oandaapihealthstatus',
            index=models.Index(fields=['account', 'checked_at'], name='oanda_api_h_account_b788ad_idx'),
        ),
        migrations.AddIndex(
            model_name='oandaapihealthstatus',
            index=models.Index(fields=['account', 'is_available', 'checked_at'], name='oanda_api_h_account_14790c_idx'),
        ),
    ]
