# Generated by Django 5.2.7 on 2026-01-27 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celerytaskstatus',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('stopping', 'Stopping'), ('stopped', 'Stopped'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='running', max_length=32),
        ),
    ]
