# Generated by Django 5.2.13 on 2026-05-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_celerytaskstatus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='oandaaccounts',
            name='hedging_enabled',
            field=models.BooleanField(blank=True, help_text='Latest cached OANDA hedging capability for this account', null=True),
        ),
        migrations.AddField(
            model_name='oandaaccounts',
            name='nav',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Latest cached net asset value from OANDA', max_digits=15),
        ),
        migrations.AddField(
            model_name='oandaaccounts',
            name='open_position_count',
            field=models.PositiveIntegerField(default=0, help_text='Latest cached open position count from OANDA'),
        ),
        migrations.AddField(
            model_name='oandaaccounts',
            name='open_trade_count',
            field=models.PositiveIntegerField(default=0, help_text='Latest cached open trade count from OANDA'),
        ),
        migrations.AddField(
            model_name='oandaaccounts',
            name='pending_order_count',
            field=models.PositiveIntegerField(default=0, help_text='Latest cached pending order count from OANDA'),
        ),
        migrations.AddField(
            model_name='oandaaccounts',
            name='snapshot_refresh_error',
            field=models.CharField(blank=True, default='', help_text='Last safe error message from refreshing the OANDA account snapshot', max_length=255),
        ),
        migrations.AddField(
            model_name='oandaaccounts',
            name='snapshot_refreshed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the cached OANDA account snapshot was refreshed', null=True),
        ),
    ]
