# Generated by Django 5.2.13 on 2026-05-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0003_oandaaccounts_hedging_enabled_oandaaccounts_nav_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="oandaaccounts",
            name="snapshot_refresh_status",
            field=models.CharField(
                choices=[
                    ("idle", "Idle"),
                    ("queued", "Queued"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="idle",
                help_text="Latest manual OANDA account snapshot refresh task status",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="oandaaccounts",
            name="snapshot_refresh_task_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Latest manual OANDA account snapshot refresh Celery task ID",
                max_length=255,
            ),
        ),
    ]
