# Generated by GitHub Copilot on 2025-12-15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0003_add_oandaaccount_is_used"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="oandaaccounts",
            name="enable_position_differentiation",
        ),
        migrations.RemoveField(
            model_name="oandaaccounts",
            name="position_diff_increment",
        ),
        migrations.RemoveField(
            model_name="oandaaccounts",
            name="position_diff_pattern",
        ),
        migrations.RemoveField(
            model_name="oandaaccounts",
            name="status",
        ),
    ]
