# Generated by Django 5.2.13 on 2026-05-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0004_oandaaccounts_snapshot_refresh_task_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="oandaaccounts",
            name="snapshot_refresh_status_updated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the manual OANDA account snapshot refresh status changed",
                null=True,
            ),
        ),
    ]
