# Generated by Django 5.2.13 on 2026-05-01 20:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0005_oandaaccounts_snapshot_refresh_status_updated_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="oandaaccounts",
            index=models.Index(
                fields=["user", "snapshot_refresh_status"], name="oanda_user_refresh_stat_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="oandaaccounts",
            index=models.Index(
                fields=["user", "snapshot_refreshed_at"], name="oanda_user_snap_ref_idx"
            ),
        ),
    ]
