# Generated by Codex on 2026-05-04

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0006_oandaaccounts_snapshot_filter_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketCandle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "instrument",
                    models.CharField(
                        db_index=True, help_text="Currency pair (e.g., 'EUR_USD')", max_length=20
                    ),
                ),
                (
                    "granularity",
                    models.CharField(
                        db_index=True,
                        help_text="Candle granularity such as M1, M5, H1, H4, or D.",
                        max_length=8,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(db_index=True, help_text="UTC candle open timestamp."),
                ),
                ("open", models.DecimalField(decimal_places=10, max_digits=20)),
                ("high", models.DecimalField(decimal_places=10, max_digits=20)),
                ("low", models.DecimalField(decimal_places=10, max_digits=20)),
                ("close", models.DecimalField(decimal_places=10, max_digits=20)),
                (
                    "volume",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of source ticks or lower-granularity candles in this candle.",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="tick_data",
                        help_text="Source used to build this candle.",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "market_candles",
                "ordering": ["timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="marketcandle",
            index=models.Index(
                fields=["instrument", "granularity", "timestamp"],
                name="market_cand_instrum_7adc2c_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="marketcandle",
            constraint=models.UniqueConstraint(
                fields=("instrument", "granularity", "timestamp"),
                name="uniq_market_candle",
            ),
        ),
    ]
