# Generated by Django 5.2.13 on 2026-05-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_marketcandle'),
    ]

    operations = [
        migrations.AddField(
            model_name='oandaaccounts',
            name='live_max_estimated_exposure_units',
            field=models.PositiveIntegerField(default=200000, help_text='Account-specific maximum estimated gross units allowed when the live max exposure guard is enabled'),
        ),
        migrations.AddField(
            model_name='oandaaccounts',
            name='live_max_exposure_guard_enabled',
            field=models.BooleanField(default=False, help_text='Whether to enforce the maximum estimated gross units check before starting non-dry-run trading tasks on this account'),
        ),
    ]
