# Generated by Django 5.2.13 on 2026-05-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0008_oandaaccounts_live_max_estimated_exposure_units_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="oandaaccounts",
            name="live_max_order_units",
            field=models.PositiveIntegerField(
                default=10000,
                help_text=(
                    "Account-specific maximum absolute units allowed for a single "
                    "broker-bound order"
                ),
            ),
        ),
        migrations.AddField(
            model_name="oandaaccounts",
            name="live_max_order_guard_enabled",
            field=models.BooleanField(
                default=True,
                help_text=(
                    "Whether to enforce the account-specific maximum order units check "
                    "before submitting broker-bound orders on this account"
                ),
            ),
        ),
    ]
