# Generated by Copilot

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0008_rename_market_celery_tasks_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="OandaApiHealthStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_available", models.BooleanField(db_index=True, default=False)),
                (
                    "checked_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("latency_ms", models.IntegerField(blank=True, null=True)),
                ("http_status", models.IntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_health_statuses",
                        to="market.OandaAccounts",
                    ),
                ),
            ],
            options={
                "verbose_name": "OANDA API Health Status",
                "verbose_name_plural": "OANDA API Health Statuses",
                "db_table": "oanda_api_health_statuses",
                "ordering": ["-checked_at"],
            },
        ),
        migrations.AddIndex(
            model_name="oandaapihealthstatus",
            index=models.Index(
                fields=["account", "checked_at"], name="oanda_api_h_account_fbf8a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="oandaapihealthstatus",
            index=models.Index(
                fields=["account", "is_available", "checked_at"],
                name="oanda_api_h_account_7e63c4_idx",
            ),
        ),
    ]
