# Generated by Django 5.2.13 on 2026-05-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0009_oandaaccounts_live_max_order_units"),
    ]

    operations = [
        migrations.AddField(
            model_name="oandaaccounts",
            name="live_max_initial_order_guard_enabled",
            field=models.BooleanField(
                default=True,
                help_text=(
                    "Whether to enforce the account-specific maximum initial order units "
                    "check before starting non-dry-run trading tasks on this account"
                ),
            ),
        ),
        migrations.AddField(
            model_name="oandaaccounts",
            name="live_max_initial_order_units",
            field=models.PositiveIntegerField(
                default=10000,
                help_text=(
                    "Account-specific maximum absolute units allowed for the initial "
                    "strategy order"
                ),
            ),
        ),
        migrations.AlterField(
            model_name="oandaaccounts",
            name="live_max_order_guard_enabled",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Whether to enforce the account-specific maximum order units check "
                    "before submitting broker-bound orders on this account"
                ),
            ),
        ),
    ]
