# Generated by Django 5.2.13 on 2026-05-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_oandaaccounts_live_max_initial_order_and_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='oandaaccounts',
            name='live_tick_latency_metric_interval_seconds',
            field=models.PositiveIntegerField(default=60, help_text='Minimum interval in seconds for persisting live tick latency metrics. Set to 0 to disable periodic latency metric samples.'),
        ),
    ]
