# Generated by Django 5.2.7 on 2025-12-19 06:14

from typing import Any

from django.db import migrations, models


def _dedupe_tick_data(_apps: Any, schema_editor: Any) -> None:
    """Remove duplicate (instrument, timestamp) rows before adding composite PK.

    The production database has historically used an integer `id` primary key, so
    duplicates are possible. When switching to a composite primary key on
    (instrument, timestamp), the constraint would fail unless duplicates are
    removed.

    We keep the newest row by `id` (highest id).
    """

    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute(
        """
        DELETE FROM tick_data t1
        USING tick_data t2
        WHERE t1.instrument = t2.instrument
          AND t1.timestamp = t2.timestamp
          AND t1.id < t2.id;
        """
    )


def _ensure_sqlite_tick_data_unique_index(_apps: Any, schema_editor: Any) -> None:
    """Ensure SQLite has a UNIQUE index for (instrument, timestamp).

    SQLite has limited ALTER TABLE support, and Django's table rebuild may not
    always result in a usable PK/UNIQUE constraint for conflict targets.
    Creating an explicit UNIQUE index ensures bulk upserts using
    ON CONFLICT(instrument, timestamp) work reliably in tests.
    """

    if schema_editor.connection.vendor != "sqlite":
        return

    schema_editor.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS tick_data_instrument_timestamp_uniq_idx "
        "ON tick_data (instrument, timestamp);"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0010_oandaaccount_unique_user_accountid_apitype"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="tickdata",
            name="tick_data_instrum_b325fe_idx",
        ),
        migrations.RunPython(_dedupe_tick_data, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="tickdata",
            name="id",
        ),
        migrations.AddField(
            model_name="tickdata",
            name="pk",
            field=models.CompositePrimaryKey(
                "instrument",
                "timestamp",
                blank=True,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.RunPython(
            _ensure_sqlite_tick_data_unique_index,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
