# Generated by Django 5.2.13 on 2026-05-08 13:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0011_oandaaccounts_live_tick_latency_metric_interval_seconds"),
    ]

    operations = [
        migrations.CreateModel(
            name="OandaRetryMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "namespace",
                    models.CharField(db_index=True, default="oanda_retry_metrics", max_length=128),
                ),
                ("event_name", models.CharField(db_index=True, max_length=32)),
                ("label", models.CharField(blank=True, db_index=True, default="", max_length=255)),
                ("attempts_used", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "OANDA Retry Metric",
                "verbose_name_plural": "OANDA Retry Metrics",
                "db_table": "oanda_retry_metrics",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["namespace", "event_name", "created_at"],
                        name="oanda_retry_namespa_29d251_idx",
                    ),
                    models.Index(
                        fields=["namespace", "label", "created_at"],
                        name="oanda_retry_namespa_501207_idx",
                    ),
                ],
            },
        ),
    ]
