# Generated by GitHub Copilot on 2025-12-19

from __future__ import annotations

from typing import Any

from django.db import migrations


def _add_postgres_pk(_apps: Any, schema_editor: Any) -> None:
    if schema_editor.connection.vendor != "postgresql":
        return

    # CompositePrimaryKey is an ORM-level concept; enforce it at the DB level.
    schema_editor.execute(
        "ALTER TABLE tick_data ADD CONSTRAINT tick_data_pkey PRIMARY KEY (instrument, timestamp);"
    )


def _drop_postgres_pk(_apps: Any, schema_editor: Any) -> None:
    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute("ALTER TABLE tick_data DROP CONSTRAINT IF EXISTS tick_data_pkey;")


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0011_remove_tickdata_tick_data_instrum_b325fe_idx_and_more"),
    ]

    operations = [
        migrations.RunPython(_add_postgres_pk, reverse_code=_drop_postgres_pk),
    ]
