# Generated by Django 5.2.7 on 2026-01-13 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_tickdata_add_composite_pk_constraint'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='oandaapihealthstatus',
            new_name='oanda_api_h_account_b788ad_idx',
            old_name='oanda_api_h_account_fbf8a3_idx',
        ),
        migrations.RenameIndex(
            model_name='oandaapihealthstatus',
            new_name='oanda_api_h_account_14790c_idx',
            old_name='oanda_api_h_account_7e63c4_idx',
        ),
        migrations.AlterField(
            model_name='celerytaskstatus',
            name='celery_task_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='celerytaskstatus',
            name='status_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='celerytaskstatus',
            name='worker',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='marketevent',
            name='instrument',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='oandaaccounts',
            name='api_type',
            field=models.CharField(choices=[('practice', 'Practice'), ('live', 'Live')], default='practice', help_text='API endpoint type (practice or live)', max_length=20),
        ),
        migrations.AlterField(
            model_name='oandaaccounts',
            name='jurisdiction',
            field=models.CharField(choices=[('US', 'United States'), ('JP', 'Japan'), ('OTHER', 'Other/International')], default='OTHER', help_text='Regulatory jurisdiction for this account', max_length=10),
        ),
    ]
