# Generated by Django 5.2.7 on 2025-11-01 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Strategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "strategy_type",
                    models.CharField(
                        help_text="Type of strategy (e.g., 'floor', 'trend_following')",
                        max_length=50,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, help_text="Whether the strategy is currently active"
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        default=dict, help_text="Strategy-specific configuration parameters"
                    ),
                ),
                (
                    "instrument",
                    models.JSONField(
                        default=list,
                        help_text="List of currency pairs to trade (e.g., ['EUR_USD', 'GBP_USD'])",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp when the strategy was started", null=True
                    ),
                ),
                (
                    "stopped_at",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp when the strategy was stopped", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when the strategy was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp when the strategy was last updated"
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        help_text="OANDA account associated with this strategy",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="strategies",
                        to="accounts.oandaaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Strategy",
                "verbose_name_plural": "Strategies",
                "db_table": "strategies",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "position_id",
                    models.CharField(
                        db_index=True, help_text="OANDA position ID", max_length=100, unique=True
                    ),
                ),
                (
                    "instrument",
                    models.CharField(help_text="Currency pair (e.g., 'EUR_USD')", max_length=10),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("long", "Long"), ("short", "Short")],
                        help_text="Position direction (long or short)",
                        max_length=5,
                    ),
                ),
                (
                    "units",
                    models.DecimalField(
                        decimal_places=2, help_text="Number of units in the position", max_digits=15
                    ),
                ),
                (
                    "entry_price",
                    models.DecimalField(
                        decimal_places=5, help_text="Entry price for the position", max_digits=10
                    ),
                ),
                (
                    "current_price",
                    models.DecimalField(
                        decimal_places=5, help_text="Current market price", max_digits=10
                    ),
                ),
                (
                    "unrealized_pnl",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Unrealized profit/loss",
                        max_digits=15,
                    ),
                ),
                (
                    "layer_number",
                    models.IntegerField(
                        default=1, help_text="Layer number (for multi-layer strategies)"
                    ),
                ),
                (
                    "is_first_lot",
                    models.BooleanField(
                        default=False, help_text="Whether this is the first lot of a layer"
                    ),
                ),
                (
                    "opened_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when the position was opened"
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp when the position was closed", null=True
                    ),
                ),
                (
                    "realized_pnl",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Realized profit/loss (when closed)",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        help_text="OANDA account associated with this position",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="accounts.oandaaccount",
                    ),
                ),
                (
                    "strategy",
                    models.ForeignKey(
                        blank=True,
                        help_text="Strategy that opened this position",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="positions",
                        to="trading.strategy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Position",
                "verbose_name_plural": "Positions",
                "db_table": "positions",
                "ordering": ["-opened_at"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "order_id",
                    models.CharField(
                        db_index=True, help_text="OANDA order ID", max_length=100, unique=True
                    ),
                ),
                (
                    "instrument",
                    models.CharField(help_text="Currency pair (e.g., 'EUR_USD')", max_length=10),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[
                            ("market", "Market"),
                            ("limit", "Limit"),
                            ("stop", "Stop"),
                            ("oco", "OCO"),
                        ],
                        help_text="Type of order",
                        max_length=20,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("long", "Long"), ("short", "Short")],
                        help_text="Trade direction (long or short)",
                        max_length=5,
                    ),
                ),
                (
                    "units",
                    models.DecimalField(
                        decimal_places=2, help_text="Number of units to trade", max_digits=15
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        help_text="Order price (for limit/stop orders)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "take_profit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        help_text="Take-profit price",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "stop_loss",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        help_text="Stop-loss price",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("filled", "Filled"),
                            ("cancelled", "Cancelled"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        help_text="Current order status",
                        max_length=20,
                    ),
                ),
                (
                    "filled_at",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp when the order was filled", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when the order was created"
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        help_text="OANDA account associated with this order",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="accounts.oandaaccount",
                    ),
                ),
                (
                    "strategy",
                    models.ForeignKey(
                        blank=True,
                        help_text="Strategy that generated this order",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="trading.strategy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "db_table": "orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StrategyState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "current_layer",
                    models.IntegerField(
                        default=1, help_text="Current layer number (for multi-layer strategies)"
                    ),
                ),
                (
                    "layer_states",
                    models.JSONField(
                        default=dict,
                        help_text="State for each layer (e.g., position counts, entry prices)",
                    ),
                ),
                (
                    "atr_values",
                    models.JSONField(
                        default=dict, help_text="ATR history for volatility monitoring"
                    ),
                ),
                (
                    "normal_atr",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        help_text="Normal ATR baseline value",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "last_tick_time",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp of the last processed tick", null=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp when the state was last updated"
                    ),
                ),
                (
                    "strategy",
                    models.OneToOneField(
                        help_text="Strategy associated with this state",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state",
                        to="trading.strategy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Strategy State",
                "verbose_name_plural": "Strategy States",
                "db_table": "strategy_states",
            },
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "instrument",
                    models.CharField(help_text="Currency pair (e.g., 'EUR_USD')", max_length=10),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("long", "Long"), ("short", "Short")],
                        help_text="Trade direction (long or short)",
                        max_length=5,
                    ),
                ),
                (
                    "units",
                    models.DecimalField(
                        decimal_places=2, help_text="Number of units traded", max_digits=15
                    ),
                ),
                (
                    "entry_price",
                    models.DecimalField(decimal_places=5, help_text="Entry price", max_digits=10),
                ),
                (
                    "exit_price",
                    models.DecimalField(decimal_places=5, help_text="Exit price", max_digits=10),
                ),
                (
                    "pnl",
                    models.DecimalField(
                        decimal_places=2, help_text="Profit/loss for the trade", max_digits=15
                    ),
                ),
                (
                    "commission",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Commission paid for the trade",
                        max_digits=10,
                    ),
                ),
                (
                    "opened_at",
                    models.DateTimeField(help_text="Timestamp when the trade was opened"),
                ),
                (
                    "closed_at",
                    models.DateTimeField(help_text="Timestamp when the trade was closed"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when the trade record was created"
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        help_text="OANDA account associated with this trade",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to="accounts.oandaaccount",
                    ),
                ),
                (
                    "strategy",
                    models.ForeignKey(
                        blank=True,
                        help_text="Strategy that executed this trade",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trades",
                        to="trading.strategy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trade",
                "verbose_name_plural": "Trades",
                "db_table": "trades",
                "ordering": ["-closed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="strategy",
            index=models.Index(
                fields=["account", "is_active"], name="strategies_account_483b41_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="strategy",
            index=models.Index(fields=["strategy_type"], name="strategies_strateg_f57f49_idx"),
        ),
        migrations.AddIndex(
            model_name="strategy",
            index=models.Index(fields=["created_at"], name="strategies_created_9ee275_idx"),
        ),
        migrations.AddIndex(
            model_name="position",
            index=models.Index(
                fields=["account", "closed_at"], name="positions_account_1ace69_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="position",
            index=models.Index(fields=["position_id"], name="positions_positio_7769c5_idx"),
        ),
        migrations.AddIndex(
            model_name="position",
            index=models.Index(fields=["instrument"], name="positions_instrum_c9b3ea_idx"),
        ),
        migrations.AddIndex(
            model_name="position",
            index=models.Index(fields=["opened_at"], name="positions_opened__22a8a6_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["account", "status"], name="orders_account_ca00e7_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["order_id"], name="orders_order_i_88e57b_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["instrument"], name="orders_instrum_8d5293_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["created_at"], name="orders_created_77e2b9_idx"),
        ),
        migrations.AddIndex(
            model_name="trade",
            index=models.Index(fields=["account", "closed_at"], name="trades_account_5a01c1_idx"),
        ),
        migrations.AddIndex(
            model_name="trade",
            index=models.Index(fields=["instrument"], name="trades_instrum_67b7ff_idx"),
        ),
        migrations.AddIndex(
            model_name="trade",
            index=models.Index(fields=["opened_at"], name="trades_opened__341710_idx"),
        ),
        migrations.AddIndex(
            model_name="trade",
            index=models.Index(fields=["closed_at"], name="trades_closed__5bb666_idx"),
        ),
    ]
