# Generated by Django 5.2.7 on 2025-11-02 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0002_add_event_logging_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Backtest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "strategy_type",
                    models.CharField(
                        help_text="Type of strategy to backtest (e.g., 'floor', 'trend_following')",
                        max_length=50,
                    ),
                ),
                (
                    "config",
                    models.JSONField(default=dict, help_text="Strategy configuration parameters"),
                ),
                (
                    "instrument",
                    models.JSONField(
                        default=list,
                        help_text=(
                            "List of currency pairs to backtest " "(e.g., ['EUR_USD', 'GBP_USD'])"
                        ),
                    ),
                ),
                ("start_date", models.DateTimeField(help_text="Start date for backtest period")),
                ("end_date", models.DateTimeField(help_text="End date for backtest period")),
                (
                    "initial_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=10000,
                        help_text="Initial account balance for backtest",
                        max_digits=15,
                    ),
                ),
                (
                    "slippage_pips",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Slippage in pips to apply to each trade",
                        max_digits=5,
                    ),
                ),
                (
                    "commission_per_trade",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Commission to apply per trade",
                        max_digits=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Current backtest execution status",
                        max_length=20,
                    ),
                ),
                (
                    "progress",
                    models.IntegerField(
                        default=0, help_text="Backtest progress percentage (0-100)"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if backtest failed", null=True
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp when backtest execution started", null=True
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when backtest execution completed",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when backtest was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp when backtest was last updated"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who created this backtest",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backtests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Backtest",
                "verbose_name_plural": "Backtests",
                "db_table": "backtests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BacktestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "final_balance",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Final account balance after backtest",
                        max_digits=15,
                    ),
                ),
                (
                    "total_return",
                    models.DecimalField(
                        decimal_places=4, help_text="Total return as a percentage", max_digits=10
                    ),
                ),
                (
                    "total_pnl",
                    models.DecimalField(
                        decimal_places=2, help_text="Total profit/loss", max_digits=15
                    ),
                ),
                (
                    "max_drawdown",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Maximum drawdown as a percentage",
                        max_digits=10,
                    ),
                ),
                (
                    "max_drawdown_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Maximum drawdown in currency units",
                        max_digits=15,
                    ),
                ),
                (
                    "sharpe_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Sharpe ratio (risk-adjusted return)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "total_trades",
                    models.IntegerField(default=0, help_text="Total number of trades executed"),
                ),
                (
                    "winning_trades",
                    models.IntegerField(default=0, help_text="Number of winning trades"),
                ),
                (
                    "losing_trades",
                    models.IntegerField(default=0, help_text="Number of losing trades"),
                ),
                (
                    "win_rate",
                    models.DecimalField(
                        decimal_places=2, help_text="Win rate as a percentage", max_digits=5
                    ),
                ),
                (
                    "average_win",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Average profit per winning trade",
                        max_digits=15,
                    ),
                ),
                (
                    "average_loss",
                    models.DecimalField(
                        decimal_places=2, help_text="Average loss per losing trade", max_digits=15
                    ),
                ),
                (
                    "largest_win",
                    models.DecimalField(
                        decimal_places=2, help_text="Largest winning trade", max_digits=15
                    ),
                ),
                (
                    "largest_loss",
                    models.DecimalField(
                        decimal_places=2, help_text="Largest losing trade", max_digits=15
                    ),
                ),
                (
                    "profit_factor",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Profit factor (gross profit / gross loss)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "average_trade_duration",
                    models.DurationField(
                        blank=True, help_text="Average duration of trades", null=True
                    ),
                ),
                (
                    "equity_curve",
                    models.JSONField(
                        default=list,
                        help_text="Equity curve data as list of {timestamp, balance} objects",
                    ),
                ),
                (
                    "trade_log",
                    models.JSONField(
                        default=list, help_text="Detailed trade log as list of trade objects"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when results were created"
                    ),
                ),
                (
                    "backtest",
                    models.OneToOneField(
                        help_text="Backtest associated with these results",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="trading.backtest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Backtest Result",
                "verbose_name_plural": "Backtest Results",
                "db_table": "backtest_results",
            },
        ),
        migrations.AddIndex(
            model_name="backtest",
            index=models.Index(fields=["user", "status"], name="backtests_user_id_0ff5fa_idx"),
        ),
        migrations.AddIndex(
            model_name="backtest",
            index=models.Index(fields=["strategy_type"], name="backtests_strateg_d11027_idx"),
        ),
        migrations.AddIndex(
            model_name="backtest",
            index=models.Index(fields=["created_at"], name="backtests_created_b543a8_idx"),
        ),
        migrations.AddIndex(
            model_name="backtest",
            index=models.Index(fields=["status", "created_at"], name="backtests_status_3a9d7b_idx"),
        ),
    ]
