# Generated by Django 5.2.7 on 2025-11-02 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_add_system_settings"),
        ("trading", "0003_backtest_backtestresult_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TickData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "instrument",
                    models.CharField(
                        db_index=True, help_text="Currency pair (e.g., 'EUR_USD')", max_length=10
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, help_text="Timestamp when the tick was received"
                    ),
                ),
                (
                    "bid",
                    models.DecimalField(decimal_places=5, help_text="Bid price", max_digits=10),
                ),
                (
                    "ask",
                    models.DecimalField(decimal_places=5, help_text="Ask price", max_digits=10),
                ),
                (
                    "mid",
                    models.DecimalField(
                        decimal_places=5,
                        help_text="Mid price (average of bid and ask)",
                        max_digits=10,
                    ),
                ),
                (
                    "spread",
                    models.DecimalField(
                        decimal_places=5,
                        help_text="Spread (difference between ask and bid)",
                        max_digits=10,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when the record was created"
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        help_text="OANDA account that received this tick",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tick_data",
                        to="accounts.oandaaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tick Data",
                "verbose_name_plural": "Tick Data",
                "db_table": "tick_data",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(fields=["instrument"], name="tick_data_instrum_7f586e_idx"),
                    models.Index(fields=["timestamp"], name="tick_data_timesta_a4b109_idx"),
                    models.Index(
                        fields=["instrument", "timestamp"], name="tick_data_instrum_b325fe_idx"
                    ),
                    models.Index(
                        fields=["account", "instrument", "timestamp"],
                        name="tick_data_account_0fb6f6_idx",
                    ),
                    models.Index(fields=["created_at"], name="tick_data_created_69aebd_idx"),
                ],
            },
        ),
    ]
