# Generated by Django 5.2.7 on 2025-11-03 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0005_add_backtest_resource_tracking"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StrategyComparison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "strategy_configs",
                    models.JSONField(help_text="List of strategy configurations to compare"),
                ),
                ("instrument", models.JSONField(help_text="List of currency pairs")),
                ("start_date", models.DateTimeField(help_text="Start date for comparison period")),
                ("end_date", models.DateTimeField(help_text="End date for comparison period")),
                (
                    "initial_balance",
                    models.DecimalField(decimal_places=2, default=10000, max_digits=15),
                ),
                ("slippage_pips", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                (
                    "commission_per_trade",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "results",
                    models.JSONField(
                        blank=True,
                        help_text="Comparison results including metrics table and equity curves",
                        null=True,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="strategy_comparisons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "strategy_comparisons",
                "ordering": ["-created_at"],
            },
        ),
    ]
