# Generated by Django 5.2.7 on 2025-11-08 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_add_email_whitelist"),
        ("trading", "0008_add_data_source_to_backtest"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategy",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("running", "Running"),
                    ("stopped", "Stopped"),
                    ("paused", "Paused"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="created",
                help_text="Current strategy status",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="backtest",
            name="data_source",
            field=models.CharField(
                choices=[("postgresql", "PostgreSQL"), ("athena", "AWS Athena")],
                default="postgresql",
                help_text="Data source for historical tick data",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="backtest",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("running", "Running"),
                    ("stopped", "Stopped"),
                    ("paused", "Paused"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="created",
                help_text="Current backtest execution status",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="strategy",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="Whether the strategy is currently active (deprecated, use status field)",
            ),
        ),
        migrations.AlterField(
            model_name="strategycomparison",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("running", "Running"),
                    ("stopped", "Stopped"),
                    ("paused", "Paused"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="created",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="strategy",
            index=models.Index(fields=["account", "status"], name="strategies_account_e7d812_idx"),
        ),
    ]
