# Generated by Django 5.2.7 on 2025-11-08 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0011_add_strategy_config_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[("backtest", "Backtest"), ("trading", "Trading")],
                        help_text="Type of task (backtest or trading)",
                        max_length=20,
                    ),
                ),
                ("task_id", models.IntegerField(help_text="ID of the parent task")),
                (
                    "execution_number",
                    models.IntegerField(help_text="Sequential execution number for the task"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("running", "Running"),
                            ("stopped", "Stopped"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="created",
                        help_text="Current execution status",
                        max_length=20,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, help_text="Execution start timestamp", null=True
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="Execution completion timestamp", null=True
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, default="", help_text="Error message if execution failed"
                    ),
                ),
                (
                    "error_traceback",
                    models.TextField(
                        blank=True, default="", help_text="Full traceback for debugging"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Record creation timestamp"),
                ),
            ],
            options={
                "verbose_name": "Task Execution",
                "verbose_name_plural": "Task Executions",
                "db_table": "task_executions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["task_type", "task_id", "created_at"],
                        name="task_execut_task_ty_0aacb9_idx",
                    ),
                    models.Index(fields=["status"], name="task_execut_status_7b46d5_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("task_type", "task_id", "execution_number"),
                        name="unique_task_execution",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ExecutionMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "total_return",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total return percentage",
                        max_digits=10,
                    ),
                ),
                (
                    "total_pnl",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="Total profit/loss", max_digits=15
                    ),
                ),
                (
                    "total_trades",
                    models.IntegerField(default=0, help_text="Number of trades executed"),
                ),
                (
                    "winning_trades",
                    models.IntegerField(default=0, help_text="Number of winning trades"),
                ),
                (
                    "losing_trades",
                    models.IntegerField(default=0, help_text="Number of losing trades"),
                ),
                (
                    "win_rate",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="Win rate percentage", max_digits=5
                    ),
                ),
                (
                    "max_drawdown",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Maximum drawdown percentage",
                        max_digits=10,
                    ),
                ),
                (
                    "sharpe_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Sharpe ratio (risk-adjusted return)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "profit_factor",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Profit factor (gross profit / gross loss)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "average_win",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Average profit per winning trade",
                        max_digits=15,
                    ),
                ),
                (
                    "average_loss",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Average loss per losing trade",
                        max_digits=15,
                    ),
                ),
                (
                    "equity_curve",
                    models.JSONField(default=list, help_text="Array of equity curve data points"),
                ),
                ("trade_log", models.JSONField(default=list, help_text="Array of trade details")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Record creation timestamp"),
                ),
                (
                    "execution",
                    models.OneToOneField(
                        help_text="Associated task execution",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="trading.taskexecution",
                    ),
                ),
            ],
            options={
                "verbose_name": "Execution Metrics",
                "verbose_name_plural": "Execution Metrics",
                "db_table": "execution_metrics",
                "indexes": [
                    models.Index(fields=["execution"], name="execution_m_executi_fe5c91_idx")
                ],
            },
        ),
    ]
