# Generated by Django 5.2.7 on 2025-11-08 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_add_email_whitelist"),
        ("trading", "0013_backtest_task_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TradingTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name for this trading task", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional description of this trading task",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("running", "Running"),
                            ("stopped", "Stopped"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="created",
                        help_text="Current task status",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when the task was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp when the task was last updated"
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        help_text="OANDA account used for trading",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trading_tasks",
                        to="accounts.oandaaccount",
                    ),
                ),
                (
                    "config",
                    models.ForeignKey(
                        help_text="Strategy configuration used by this task",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trading_tasks",
                        to="trading.strategyconfig",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who created this trading task",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trading_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Trading Task",
                "verbose_name_plural": "Trading Tasks",
                "db_table": "trading_tasks",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "status"], name="trading_tas_user_id_83de91_idx"),
                    models.Index(fields=["user", "config"], name="trading_tas_user_id_3c6fc1_idx"),
                    models.Index(
                        fields=["account", "status"], name="trading_tas_account_db7fc9_idx"
                    ),
                    models.Index(fields=["created_at"], name="trading_tas_created_e23628_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "name"), name="unique_user_trading_task_name"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("status__in", ["created", "running", "stopped", "paused", "failed"])
                        ),
                        name="valid_trading_task_status",
                    ),
                ],
            },
        ),
    ]
