# Generated by Django 5.2.7 on 2025-11-12 00:42

from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps


def rename_and_convert_instruments_column(
    apps: StateApps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    """
    Rename 'instruments' to 'instrument' and convert from JSONField to VARCHAR.

    Args:
        apps: Django apps registry (unused but required by migration signature)
        schema_editor: Database schema editor for executing SQL
    """
    del apps  # Unused but required by Django migration signature
    with schema_editor.connection.cursor() as cursor:
        tables = ["backtests", "strategy_comparisons", "strategies"]

        for table in tables:
            cursor.execute(
                """
                SELECT column_name
                FROM information_schema.columns
                WHERE table_name=%s AND column_name='instruments'
            """,
                [table],
            )

            if cursor.fetchone():
                cursor.execute(f"ALTER TABLE {table} RENAME COLUMN instruments TO instrument")
                cursor.execute(
                    f"""
                    ALTER TABLE {table}
                    ALTER COLUMN instrument TYPE VARCHAR(10)
                    USING CASE
                        WHEN jsonb_typeof(instrument) = 'array' THEN
                            COALESCE(instrument->>0, 'USD_JPY')
                        WHEN jsonb_typeof(instrument) = 'string' THEN
                            instrument::text
                        ELSE 'USD_JPY'
                    END
                """
                )
                cursor.execute(f"ALTER TABLE {table} ALTER COLUMN instrument SET DEFAULT 'USD_JPY'")


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0014_tradingtask"),
    ]

    operations = [
        migrations.RunPython(
            rename_and_convert_instruments_column,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name="backtesttask",
            name="instrument",
            field=models.CharField(
                default="USD_JPY",
                help_text="Currency pair to backtest (e.g., 'USD_JPY', 'EUR_USD')",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="backtest",
            name="instrument",
            field=models.CharField(
                default="USD_JPY",
                help_text="Currency pair to backtest (e.g., 'USD_JPY', 'EUR_USD')",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="strategycomparison",
            name="instrument",
            field=models.CharField(
                default="USD_JPY", help_text="Currency pair for comparison", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="strategy",
            name="instrument",
            field=models.CharField(
                default="USD_JPY",
                help_text="Currency pair to trade (e.g., 'USD_JPY', 'EUR_USD')",
                max_length=10,
            ),
        ),
    ]
