# Generated by Django 5.2.7 on 2025-11-12 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0014_tradingtask"),
    ]

    operations = [
        migrations.AddField(
            model_name="backtesttask",
            name="instrument",
            field=models.CharField(
                default="USD_JPY",
                help_text="Currency pair to backtest (e.g., 'USD_JPY', 'EUR_USD')",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="backtest",
            name="instrument",
            field=models.CharField(
                default="USD_JPY",
                help_text="Currency pair to backtest (e.g., 'USD_JPY', 'EUR_USD')",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="strategy",
            name="instrument",
            field=models.CharField(
                default="USD_JPY",
                help_text="Currency pair to trade (e.g., 'USD_JPY', 'EUR_USD')",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="strategycomparison",
            name="instrument",
            field=models.CharField(
                default="USD_JPY", help_text="Currency pair for comparison", max_length=10
            ),
        ),
    ]
