# Generated by Django 5.2.7 on 2025-11-12 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_add_aws_credential_methods"),
        ("trading", "0015_convert_instrument_to_charfield"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="tradingtask",
            name="trading_tas_account_db7fc9_idx",
        ),
        migrations.RenameField(
            model_name="tradingtask",
            old_name="account",
            new_name="oanda_account",
        ),
        migrations.AddField(
            model_name="backtesttask",
            name="oanda_account",
            field=models.ForeignKey(
                blank=True,
                help_text="OANDA account used for this backtest (practice accounts only)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="backtest_tasks",
                to="accounts.oandaaccount",
            ),
        ),
        migrations.AddIndex(
            model_name="tradingtask",
            index=models.Index(
                fields=["oanda_account", "status"], name="trading_tas_oanda_a_4cf7d8_idx"
            ),
        ),
    ]
