# Generated by Django 5.2.7 on 2025-11-14 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0016_remove_tradingtask_trading_tas_account_db7fc9_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskexecution",
            name="progress",
            field=models.IntegerField(default=0, help_text="Execution progress percentage (0-100)"),
        ),
    ]
