# Generated by Django 5.2.7 on 2025-12-02 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0024_change_default_data_source_to_athena"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="trading_task",
            field=models.ForeignKey(
                blank=True,
                help_text="Trading task that generated this order",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="trading.tradingtask",
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="trading_task",
            field=models.ForeignKey(
                blank=True,
                help_text="Trading task that opened this position",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="positions",
                to="trading.tradingtask",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="strategy",
            field=models.ForeignKey(
                blank=True,
                help_text="Strategy that generated this order (legacy mode)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="trading.strategy",
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="strategy",
            field=models.ForeignKey(
                blank=True,
                help_text="Strategy that opened this position (legacy mode)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="positions",
                to="trading.strategy",
            ),
        ),
    ]
