"""
URL configuration for trading app.

This module defines URL patterns for trading data and strategy endpoints.
"""

from django.urls import path

from apps.trading.views import (
    BacktestTaskCopyView,
    BacktestTaskDetailView,
    BacktestTaskExecutionsView,
    BacktestTaskRestartView,
    BacktestTaskResumeView,
    BacktestTaskStartView,
    BacktestTaskStatusView,
    BacktestTaskStopView,
    BacktestTaskView,
    ExecutionDetailView,
    ExecutionEquityView,
    ExecutionEventsView,
    ExecutionLatestMetricsView,
    ExecutionLogsView,
    ExecutionMetricsView,
    ExecutionStatusView,
    ExecutionTradesView,
    StrategyConfigDetailView,
    StrategyConfigView,
    StrategyDefaultsView,
    StrategyView,
    TradingTaskCopyView,
    TradingTaskDetailView,
    TradingTaskExecutionsView,
    TradingTaskRestartView,
    TradingTaskResumeView,
    TradingTaskStartView,
    TradingTaskStatusView,
    TradingTaskStopView,
    TradingTaskView,
)

app_name = "trading"

urlpatterns = [
    path("strategies/", StrategyView.as_view(), name="strategy_list"),
    path(
        "strategies/<str:strategy_id>/defaults/",
        StrategyDefaultsView.as_view(),
        name="strategy_defaults",
    ),
    # Strategy configuration endpoints
    path(
        "strategy-configs/",
        StrategyConfigView.as_view(),
        name="strategy_config_list_create",
    ),
    path(
        "strategy-configs/<int:config_id>/",
        StrategyConfigDetailView.as_view(),
        name="strategy_config_detail",
    ),
    # Backtest task endpoints
    path(
        "backtest-tasks/",
        BacktestTaskView.as_view(),
        name="backtest_task_list_create",
    ),
    path(
        "backtest-tasks/<int:task_id>/",
        BacktestTaskDetailView.as_view(),
        name="backtest_task_detail",
    ),
    path(
        "backtest-tasks/<int:task_id>/copy/",
        BacktestTaskCopyView.as_view(),
        name="backtest_task_copy",
    ),
    path(
        "backtest-tasks/<int:task_id>/start/",
        BacktestTaskStartView.as_view(),
        name="backtest_task_start",
    ),
    path(
        "backtest-tasks/<int:task_id>/stop/",
        BacktestTaskStopView.as_view(),
        name="backtest_task_stop",
    ),
    path(
        "backtest-tasks/<int:task_id>/resume/",
        BacktestTaskResumeView.as_view(),
        name="backtest_task_resume",
    ),
    path(
        "backtest-tasks/<int:task_id>/restart/",
        BacktestTaskRestartView.as_view(),
        name="backtest_task_restart",
    ),
    path(
        "backtest-tasks/<int:task_id>/status/",
        BacktestTaskStatusView.as_view(),
        name="backtest_task_status",
    ),
    path(
        "backtest-tasks/<int:task_id>/executions/",
        BacktestTaskExecutionsView.as_view(),
        name="backtest_task_executions",
    ),
    # Trading task endpoints
    path(
        "trading-tasks/",
        TradingTaskView.as_view(),
        name="trading_task_list_create",
    ),
    path(
        "trading-tasks/<int:task_id>/",
        TradingTaskDetailView.as_view(),
        name="trading_task_detail",
    ),
    path(
        "trading-tasks/<int:task_id>/copy/",
        TradingTaskCopyView.as_view(),
        name="trading_task_copy",
    ),
    path(
        "trading-tasks/<int:task_id>/start/",
        TradingTaskStartView.as_view(),
        name="trading_task_start",
    ),
    path(
        "trading-tasks/<int:task_id>/stop/",
        TradingTaskStopView.as_view(),
        name="trading_task_stop",
    ),
    path(
        "trading-tasks/<int:task_id>/resume/",
        TradingTaskResumeView.as_view(),
        name="trading_task_resume",
    ),
    path(
        "trading-tasks/<int:task_id>/restart/",
        TradingTaskRestartView.as_view(),
        name="trading_task_restart",
    ),
    path(
        "trading-tasks/<int:task_id>/status/",
        TradingTaskStatusView.as_view(),
        name="trading_task_status",
    ),
    path(
        "trading-tasks/<int:task_id>/executions/",
        TradingTaskExecutionsView.as_view(),
        name="trading_task_executions",
    ),
    # Execution-specific endpoints (task 14)
    path(
        "executions/<int:execution_id>/",
        ExecutionDetailView.as_view(),
        name="execution_detail",
    ),
    path(
        "executions/<int:execution_id>/logs/",
        ExecutionLogsView.as_view(),
        name="execution_logs",
    ),
    path(
        "executions/<int:execution_id>/status/",
        ExecutionStatusView.as_view(),
        name="execution_status",
    ),
    path(
        "executions/<int:execution_id>/events/",
        ExecutionEventsView.as_view(),
        name="execution_events",
    ),
    path(
        "executions/<int:execution_id>/trades/",
        ExecutionTradesView.as_view(),
        name="execution_trades",
    ),
    path(
        "executions/<int:execution_id>/equity/",
        ExecutionEquityView.as_view(),
        name="execution_equity",
    ),
    path(
        "executions/<int:execution_id>/metrics/",
        ExecutionMetricsView.as_view(),
        name="execution_metrics",
    ),
    path(
        "executions/<int:execution_id>/metrics/latest/",
        ExecutionLatestMetricsView.as_view(),
        name="execution_metrics_latest",
    ),
]
